//! Auto-generated API module for gcp/travelimpactmodel flights:computeTypicalFlightEmissions.
//!
//! Generated by `cargo run --bin ewe_platform gen_api`.
//! DO NOT EDIT MANUALLY.
//!
//! Feature flag: `gcp_travelimpactmodel_flights_compute_typical_flight_emissions `

#![cfg(feature = "gcp_travelimpactmodel_flights_compute_typical_flight_emissions")]
#![allow(clippy::too_many_arguments, clippy::type_complexity)]
#![allow(
    clippy::missing_errors_doc,
    clippy::doc_markdown,
    clippy::useless_format
)]
#![allow(unused_imports)]

use foundation_core::valtron::{TaskIterator, TaskIteratorExt};
use foundation_core::wire::simple_http::client::{ClientRequestBuilder, SimpleHttpClient};
use foundation_macros::JsonHash;
use serde::{Deserialize, Serialize};

use super::shared::ApiResponse;

// =============================================================================
// TYPE DECLARATIONS
// =============================================================================

/// `ModelVersion` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct ModelVersion {
    /// dated property.
    pub dated: Option<String>,
    /// major property.
    pub major: Option<i64>,
    /// minor property.
    pub minor: Option<i64>,
    /// patch property.
    pub patch: Option<i64>,
}

/// `TypicalFlightEmissions` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct TypicalFlightEmissions {
    /// emissionsGramsPerPax property.
    pub emissions_grams_per_pax: Option<EmissionsGramsPerPax>,
    /// market property.
    pub market: Option<Market>,
}

/// `ComputeTypicalFlightEmissionsResponse` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct ComputeTypicalFlightEmissionsResponse {
    /// modelVersion property.
    pub model_version: Option<ModelVersion>,
    /// typicalFlightEmissions property.
    pub typical_flight_emissions: Option<Vec<TypicalFlightEmissions>>,
}

/// `EmissionsGramsPerPax` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct EmissionsGramsPerPax {
    /// business property.
    pub business: Option<i64>,
    /// economy property.
    pub economy: Option<i64>,
    /// first property.
    pub first: Option<i64>,
    /// premiumEconomy property.
    pub premium_economy: Option<i64>,
}

/// `Market` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct Market {
    /// destination property.
    pub destination: Option<String>,
    /// origin property.
    pub origin: Option<String>,
}

// =============================================================================
// ARGS TYPES (per-endpoint)
// =============================================================================

// =============================================================================
// CLIENT FUNCTIONS (per-endpoint)
// =============================================================================

// -----------------------------------------------------------------------------
// POST v1/flights:computeTypicalFlightEmissions
// -----------------------------------------------------------------------------

/// POST v1/flights:computeTypicalFlightEmissions.
///
/// Takes client and args, builds the request, optionally applies modifications,
/// and returns a `TaskIterator` for execution.
///
/// # Arguments
///
/// * `client` - HTTP client for making the request
/// * `builder_mod` - Optional closure to modify the request builder (e.g., add headers)
///
/// # Example
///
/// ```ignore
/// let task = travelimpactmodel_flights_compute_typical_flight_emissions_request(&client, &args, Some(|b| {
///     b.header("X-Custom-Header", "value")
/// }))?;
/// ```
#[inline]
pub fn travelimpactmodel_flights_compute_typical_flight_emissions_request<R, F>(
    client: &SimpleHttpClient<R>,
    builder_mod: Option<F>,
) -> Result<
    impl TaskIterator<
            Ready = Result<
                ApiResponse<ComputeTypicalFlightEmissionsResponse>,
                super::shared::ApiError,
            >,
            Pending = super::shared::ApiPending,
            Spawner = super::shared::BoxedSendExecutionAction,
        > + Send
        + 'static,
    super::shared::ApiError,
>
where
    R: foundation_core::wire::simple_http::client::DnsResolver + Clone + Default + 'static,
    F: FnOnce(&mut ClientRequestBuilder<R>),
{
    let endpoint_url = format!(
        "https://travelimpactmodel.googleapis.com/v1/flights:computeTypicalFlightEmissions",
    );

    let mut builder = client
        .post(&endpoint_url)
        .map_err(|e| super::shared::ApiError::RequestBuildFailed(e.to_string()))?;

    if let Some(f) = builder_mod {
        f(&mut builder);
    }

    Ok(builder
        .build_send_request()
        .map_err(|e: foundation_core::wire::simple_http::HttpClientError| {
            super::shared::ApiError::RequestBuildFailed(e.to_string())
        })?
        .map_ready(|intro| match intro {
            super::shared::RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status: usize = intro.0.into();
                if status < 200 || status >= 300 {
                    return Err(super::shared::ApiError::HttpStatus {
                        code: status as u16,
                        headers: headers.clone(),
                        body: None,
                    });
                }
                let body =
                    foundation_core::wire::simple_http::client::body_reader::collect_string(stream);
                let parsed: ComputeTypicalFlightEmissionsResponse = serde_json::from_str(&body)
                    .map_err(|e: serde_json::Error| {
                        super::shared::ApiError::ParseFailed(e.to_string())
                    })?;
                Ok(ApiResponse {
                    status: status as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            super::shared::RequestIntro::Failed(e) => {
                Err(super::shared::ApiError::RequestSendFailed(e.to_string()))
            }
        })
        .map_pending(|_| super::shared::ApiPending::Sending))
}
