[package]
name = "create"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
clap = { version = "4.5.18", features = ["derive"]}

[lints]
workspace = true
