[package]
name = "template"
version = "0.1.0"
authors = [
    "Brook Heisler <brookheisler@gmail.com>",
    "Ewetumo Alexander <alex.ewetumo@gmail.com>",
]
edition.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
keywords.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
