//! Auto-generated API module for gcp/places places.
//!
//! Generated by `cargo run --bin ewe_platform gen_api`.
//! DO NOT EDIT MANUALLY.
//!
//! Feature flag: `gcp_places_places `

#![cfg(feature = "gcp_places_places")]
#![allow(clippy::too_many_arguments, clippy::type_complexity)]
#![allow(
    clippy::missing_errors_doc,
    clippy::doc_markdown,
    clippy::useless_format
)]

use foundation_core::valtron::{execute, StreamIterator, TaskIterator, TaskIteratorExt};
use foundation_core::wire::simple_http::client::{ClientRequestBuilder, SimpleHttpClient};
use foundation_macros::JsonHash;
use serde::{Deserialize, Serialize};

use super::shared::{ApiError, ApiPending, ApiResponse};

// =============================================================================
// TYPE DECLARATIONS
// =============================================================================

/// `GoogleMapsPlacesV1Review` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1Review {
    /// authorAttribution property.
    pub author_attribution: Option<GoogleMapsPlacesV1AuthorAttribution>,
    /// flagContentUri property.
    pub flag_content_uri: Option<String>,
    /// googleMapsUri property.
    pub google_maps_uri: Option<String>,
    /// name property.
    pub name: Option<String>,
    /// originalText property.
    pub original_text: Option<GoogleTypeLocalizedText>,
    /// publishTime property.
    pub publish_time: Option<String>,
    /// rating property.
    pub rating: Option<f64>,
    /// relativePublishTimeDescription property.
    pub relative_publish_time_description: Option<String>,
    /// text property.
    pub text: Option<GoogleTypeLocalizedText>,
    /// visitDate property.
    pub visit_date: Option<GoogleTypeDate>,
}

/// `GoogleMapsPlacesV1PlaceOpeningHours` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1PlaceOpeningHours {
    /// nextCloseTime property.
    pub next_close_time: Option<String>,
    /// nextOpenTime property.
    pub next_open_time: Option<String>,
    /// openNow property.
    pub open_now: Option<bool>,
    /// periods property.
    pub periods: Option<Vec<GoogleMapsPlacesV1PlaceOpeningHoursPeriod>>,
    /// secondaryHoursType property.
    pub secondary_hours_type: Option<String>,
    /// specialDays property.
    pub special_days: Option<Vec<GoogleMapsPlacesV1PlaceOpeningHoursSpecialDay>>,
    /// weekdayDescriptions property.
    pub weekday_descriptions: Option<Vec<String>>,
}

/// `GoogleMapsPlacesV1PlaceReviewSummary` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1PlaceReviewSummary {
    /// disclosureText property.
    pub disclosure_text: Option<GoogleTypeLocalizedText>,
    /// flagContentUri property.
    pub flag_content_uri: Option<String>,
    /// reviewsUri property.
    pub reviews_uri: Option<String>,
    /// text property.
    pub text: Option<GoogleTypeLocalizedText>,
}

/// `GoogleMapsPlacesV1PlaceSubDestination` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1PlaceSubDestination {
    /// id property.
    pub id: Option<String>,
    /// name property.
    pub name: Option<String>,
}

/// `GoogleMapsPlacesV1AuthorAttribution` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1AuthorAttribution {
    /// displayName property.
    pub display_name: Option<String>,
    /// photoUri property.
    pub photo_uri: Option<String>,
    /// uri property.
    pub uri: Option<String>,
}

/// `GoogleGeoTypeViewport` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleGeoTypeViewport {
    /// high property.
    pub high: Option<GoogleTypeLatLng>,
    /// low property.
    pub low: Option<GoogleTypeLatLng>,
}

/// `GoogleMapsPlacesV1PlaceOpeningHoursPeriodPoint` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1PlaceOpeningHoursPeriodPoint {
    /// date property.
    pub date: Option<GoogleTypeDate>,
    /// day property.
    pub day: Option<i64>,
    /// hour property.
    pub hour: Option<i64>,
    /// minute property.
    pub minute: Option<i64>,
    /// truncated property.
    pub truncated: Option<bool>,
}

/// `GoogleMapsPlacesV1PlaceConsumerAlertDetailsLink` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1PlaceConsumerAlertDetailsLink {
    /// title property.
    pub title: Option<String>,
    /// uri property.
    pub uri: Option<String>,
}

/// `GoogleMapsPlacesV1PlaceEvChargeAmenitySummary` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1PlaceEvChargeAmenitySummary {
    /// coffee property.
    pub coffee: Option<GoogleMapsPlacesV1ContentBlock>,
    /// disclosureText property.
    pub disclosure_text: Option<GoogleTypeLocalizedText>,
    /// flagContentUri property.
    pub flag_content_uri: Option<String>,
    /// overview property.
    pub overview: Option<GoogleMapsPlacesV1ContentBlock>,
    /// restaurant property.
    pub restaurant: Option<GoogleMapsPlacesV1ContentBlock>,
    /// store property.
    pub store: Option<GoogleMapsPlacesV1ContentBlock>,
}

/// `GoogleMapsPlacesV1Photo` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1Photo {
    /// authorAttributions property.
    pub author_attributions: Option<Vec<GoogleMapsPlacesV1AuthorAttribution>>,
    /// flagContentUri property.
    pub flag_content_uri: Option<String>,
    /// googleMapsUri property.
    pub google_maps_uri: Option<String>,
    /// heightPx property.
    pub height_px: Option<i64>,
    /// name property.
    pub name: Option<String>,
    /// widthPx property.
    pub width_px: Option<i64>,
}

/// `GoogleTypeDate` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleTypeDate {
    /// day property.
    pub day: Option<i64>,
    /// month property.
    pub month: Option<i64>,
    /// year property.
    pub year: Option<i64>,
}

/// `GoogleMapsPlacesV1PlacePlusCode` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1PlacePlusCode {
    /// compoundCode property.
    pub compound_code: Option<String>,
    /// globalCode property.
    pub global_code: Option<String>,
}

/// `GoogleTypeTimeZone` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleTypeTimeZone {
    /// id property.
    pub id: Option<String>,
    /// version property.
    pub version: Option<String>,
}

/// `GoogleTypeMoney` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleTypeMoney {
    /// currencyCode property.
    pub currency_code: Option<String>,
    /// nanos property.
    pub nanos: Option<i64>,
    /// units property.
    pub units: Option<String>,
}

/// `GoogleMapsPlacesV1PlaceOpeningHoursPeriod` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1PlaceOpeningHoursPeriod {
    /// close property.
    pub close: Option<GoogleMapsPlacesV1PlaceOpeningHoursPeriodPoint>,
    /// open property.
    pub open: Option<GoogleMapsPlacesV1PlaceOpeningHoursPeriodPoint>,
}

/// `GoogleTypeLatLng` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleTypeLatLng {
    /// latitude property.
    pub latitude: Option<f64>,
    /// longitude property.
    pub longitude: Option<f64>,
}

/// `GoogleMapsPlacesV1PlacePaymentOptions` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1PlacePaymentOptions {
    /// acceptsCashOnly property.
    pub accepts_cash_only: Option<bool>,
    /// acceptsCreditCards property.
    pub accepts_credit_cards: Option<bool>,
    /// acceptsDebitCards property.
    pub accepts_debit_cards: Option<bool>,
    /// acceptsNfc property.
    pub accepts_nfc: Option<bool>,
}

/// `GoogleMapsPlacesV1AddressDescriptorArea` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1AddressDescriptorArea {
    /// containment property.
    pub containment: Option<String>,
    /// displayName property.
    pub display_name: Option<GoogleTypeLocalizedText>,
    /// name property.
    pub name: Option<String>,
    /// placeId property.
    pub place_id: Option<String>,
}

/// `GoogleTypePostalAddress` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleTypePostalAddress {
    /// addressLines property.
    pub address_lines: Option<Vec<String>>,
    /// administrativeArea property.
    pub administrative_area: Option<String>,
    /// languageCode property.
    pub language_code: Option<String>,
    /// locality property.
    pub locality: Option<String>,
    /// organization property.
    pub organization: Option<String>,
    /// postalCode property.
    pub postal_code: Option<String>,
    /// recipients property.
    pub recipients: Option<Vec<String>>,
    /// regionCode property.
    pub region_code: Option<String>,
    /// revision property.
    pub revision: Option<i64>,
    /// sortingCode property.
    pub sorting_code: Option<String>,
    /// sublocality property.
    pub sublocality: Option<String>,
}

/// `GoogleMapsPlacesV1AddressDescriptor` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1AddressDescriptor {
    /// areas property.
    pub areas: Option<Vec<GoogleMapsPlacesV1AddressDescriptorArea>>,
    /// landmarks property.
    pub landmarks: Option<Vec<GoogleMapsPlacesV1AddressDescriptorLandmark>>,
}

/// `GoogleMapsPlacesV1PlaceAddressComponent` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1PlaceAddressComponent {
    /// languageCode property.
    pub language_code: Option<String>,
    /// longText property.
    pub long_text: Option<String>,
    /// shortText property.
    pub short_text: Option<String>,
    /// types property.
    pub types: Option<Vec<String>>,
}

/// `GoogleMapsPlacesV1PlaceNeighborhoodSummary` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1PlaceNeighborhoodSummary {
    /// description property.
    pub description: Option<GoogleMapsPlacesV1ContentBlock>,
    /// disclosureText property.
    pub disclosure_text: Option<GoogleTypeLocalizedText>,
    /// flagContentUri property.
    pub flag_content_uri: Option<String>,
    /// overview property.
    pub overview: Option<GoogleMapsPlacesV1ContentBlock>,
}

/// `GoogleMapsPlacesV1Place` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1Place {
    /// accessibilityOptions property.
    pub accessibility_options: Option<GoogleMapsPlacesV1PlaceAccessibilityOptions>,
    /// addressComponents property.
    pub address_components: Option<Vec<GoogleMapsPlacesV1PlaceAddressComponent>>,
    /// addressDescriptor property.
    pub address_descriptor: Option<GoogleMapsPlacesV1AddressDescriptor>,
    /// adrFormatAddress property.
    pub adr_format_address: Option<String>,
    /// allowsDogs property.
    pub allows_dogs: Option<bool>,
    /// attributions property.
    pub attributions: Option<Vec<GoogleMapsPlacesV1PlaceAttribution>>,
    /// businessStatus property.
    pub business_status: Option<String>,
    /// consumerAlert property.
    pub consumer_alert: Option<GoogleMapsPlacesV1PlaceConsumerAlert>,
    /// containingPlaces property.
    pub containing_places: Option<Vec<GoogleMapsPlacesV1PlaceContainingPlace>>,
    /// curbsidePickup property.
    pub curbside_pickup: Option<bool>,
    /// currentOpeningHours property.
    pub current_opening_hours: Option<GoogleMapsPlacesV1PlaceOpeningHours>,
    /// currentSecondaryOpeningHours property.
    pub current_secondary_opening_hours: Option<Vec<GoogleMapsPlacesV1PlaceOpeningHours>>,
    /// delivery property.
    pub delivery: Option<bool>,
    /// dineIn property.
    pub dine_in: Option<bool>,
    /// displayName property.
    pub display_name: Option<GoogleTypeLocalizedText>,
    /// editorialSummary property.
    pub editorial_summary: Option<GoogleTypeLocalizedText>,
    /// evChargeAmenitySummary property.
    pub ev_charge_amenity_summary: Option<GoogleMapsPlacesV1PlaceEvChargeAmenitySummary>,
    /// evChargeOptions property.
    pub ev_charge_options: Option<GoogleMapsPlacesV1EVChargeOptions>,
    /// formattedAddress property.
    pub formatted_address: Option<String>,
    /// fuelOptions property.
    pub fuel_options: Option<GoogleMapsPlacesV1FuelOptions>,
    /// generativeSummary property.
    pub generative_summary: Option<GoogleMapsPlacesV1PlaceGenerativeSummary>,
    /// goodForChildren property.
    pub good_for_children: Option<bool>,
    /// goodForGroups property.
    pub good_for_groups: Option<bool>,
    /// goodForWatchingSports property.
    pub good_for_watching_sports: Option<bool>,
    /// googleMapsLinks property.
    pub google_maps_links: Option<GoogleMapsPlacesV1PlaceGoogleMapsLinks>,
    /// googleMapsTypeLabel property.
    pub google_maps_type_label: Option<GoogleTypeLocalizedText>,
    /// googleMapsUri property.
    pub google_maps_uri: Option<String>,
    /// iconBackgroundColor property.
    pub icon_background_color: Option<String>,
    /// iconMaskBaseUri property.
    pub icon_mask_base_uri: Option<String>,
    /// id property.
    pub id: Option<String>,
    /// internationalPhoneNumber property.
    pub international_phone_number: Option<String>,
    /// liveMusic property.
    pub live_music: Option<bool>,
    /// location property.
    pub location: Option<GoogleTypeLatLng>,
    /// menuForChildren property.
    pub menu_for_children: Option<bool>,
    /// movedPlace property.
    pub moved_place: Option<String>,
    /// movedPlaceId property.
    pub moved_place_id: Option<String>,
    /// name property.
    pub name: Option<String>,
    /// nationalPhoneNumber property.
    pub national_phone_number: Option<String>,
    /// neighborhoodSummary property.
    pub neighborhood_summary: Option<GoogleMapsPlacesV1PlaceNeighborhoodSummary>,
    /// openingDate property.
    pub opening_date: Option<GoogleTypeDate>,
    /// outdoorSeating property.
    pub outdoor_seating: Option<bool>,
    /// parkingOptions property.
    pub parking_options: Option<GoogleMapsPlacesV1PlaceParkingOptions>,
    /// paymentOptions property.
    pub payment_options: Option<GoogleMapsPlacesV1PlacePaymentOptions>,
    /// photos property.
    pub photos: Option<Vec<GoogleMapsPlacesV1Photo>>,
    /// plusCode property.
    pub plus_code: Option<GoogleMapsPlacesV1PlacePlusCode>,
    /// postalAddress property.
    pub postal_address: Option<GoogleTypePostalAddress>,
    /// priceLevel property.
    pub price_level: Option<String>,
    /// priceRange property.
    pub price_range: Option<GoogleMapsPlacesV1PriceRange>,
    /// primaryType property.
    pub primary_type: Option<String>,
    /// primaryTypeDisplayName property.
    pub primary_type_display_name: Option<GoogleTypeLocalizedText>,
    /// pureServiceAreaBusiness property.
    pub pure_service_area_business: Option<bool>,
    /// rating property.
    pub rating: Option<f64>,
    /// regularOpeningHours property.
    pub regular_opening_hours: Option<GoogleMapsPlacesV1PlaceOpeningHours>,
    /// regularSecondaryOpeningHours property.
    pub regular_secondary_opening_hours: Option<Vec<GoogleMapsPlacesV1PlaceOpeningHours>>,
    /// reservable property.
    pub reservable: Option<bool>,
    /// restroom property.
    pub restroom: Option<bool>,
    /// reviewSummary property.
    pub review_summary: Option<GoogleMapsPlacesV1PlaceReviewSummary>,
    /// reviews property.
    pub reviews: Option<Vec<GoogleMapsPlacesV1Review>>,
    /// servesBeer property.
    pub serves_beer: Option<bool>,
    /// servesBreakfast property.
    pub serves_breakfast: Option<bool>,
    /// servesBrunch property.
    pub serves_brunch: Option<bool>,
    /// servesCocktails property.
    pub serves_cocktails: Option<bool>,
    /// servesCoffee property.
    pub serves_coffee: Option<bool>,
    /// servesDessert property.
    pub serves_dessert: Option<bool>,
    /// servesDinner property.
    pub serves_dinner: Option<bool>,
    /// servesLunch property.
    pub serves_lunch: Option<bool>,
    /// servesVegetarianFood property.
    pub serves_vegetarian_food: Option<bool>,
    /// servesWine property.
    pub serves_wine: Option<bool>,
    /// shortFormattedAddress property.
    pub short_formatted_address: Option<String>,
    /// subDestinations property.
    pub sub_destinations: Option<Vec<GoogleMapsPlacesV1PlaceSubDestination>>,
    /// takeout property.
    pub takeout: Option<bool>,
    /// timeZone property.
    pub time_zone: Option<GoogleTypeTimeZone>,
    /// types property.
    pub types: Option<Vec<String>>,
    /// userRatingCount property.
    pub user_rating_count: Option<i64>,
    /// utcOffsetMinutes property.
    pub utc_offset_minutes: Option<i64>,
    /// viewport property.
    pub viewport: Option<GoogleGeoTypeViewport>,
    /// websiteUri property.
    pub website_uri: Option<String>,
}

/// `GoogleMapsPlacesV1PlaceAttribution` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1PlaceAttribution {
    /// provider property.
    pub provider: Option<String>,
    /// providerUri property.
    pub provider_uri: Option<String>,
}

/// `GoogleMapsPlacesV1PlaceGoogleMapsLinks` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1PlaceGoogleMapsLinks {
    /// directionsUri property.
    pub directions_uri: Option<String>,
    /// photosUri property.
    pub photos_uri: Option<String>,
    /// placeUri property.
    pub place_uri: Option<String>,
    /// reviewsUri property.
    pub reviews_uri: Option<String>,
    /// writeAReviewUri property.
    pub write_a_review_uri: Option<String>,
}

/// `GoogleMapsPlacesV1PlaceConsumerAlert` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1PlaceConsumerAlert {
    /// details property.
    pub details: Option<GoogleMapsPlacesV1PlaceConsumerAlertDetails>,
    /// languageCode property.
    pub language_code: Option<String>,
    /// overview property.
    pub overview: Option<String>,
}

/// `GoogleMapsPlacesV1FuelOptions` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1FuelOptions {
    /// fuelPrices property.
    pub fuel_prices: Option<Vec<GoogleMapsPlacesV1FuelOptionsFuelPrice>>,
}

/// `GoogleMapsPlacesV1PlaceAccessibilityOptions` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1PlaceAccessibilityOptions {
    /// wheelchairAccessibleEntrance property.
    pub wheelchair_accessible_entrance: Option<bool>,
    /// wheelchairAccessibleParking property.
    pub wheelchair_accessible_parking: Option<bool>,
    /// wheelchairAccessibleRestroom property.
    pub wheelchair_accessible_restroom: Option<bool>,
    /// wheelchairAccessibleSeating property.
    pub wheelchair_accessible_seating: Option<bool>,
}

/// `GoogleMapsPlacesV1FuelOptionsFuelPrice` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1FuelOptionsFuelPrice {
    /// price property.
    pub price: Option<GoogleTypeMoney>,
    /// type property.
    pub r#type: Option<String>,
    /// updateTime property.
    pub update_time: Option<String>,
}

/// `GoogleMapsPlacesV1EVChargeOptionsConnectorAggregation` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1EVChargeOptionsConnectorAggregation {
    /// availabilityLastUpdateTime property.
    pub availability_last_update_time: Option<String>,
    /// availableCount property.
    pub available_count: Option<i64>,
    /// count property.
    pub count: Option<i64>,
    /// maxChargeRateKw property.
    pub max_charge_rate_kw: Option<f64>,
    /// outOfServiceCount property.
    pub out_of_service_count: Option<i64>,
    /// type property.
    pub r#type: Option<String>,
}

/// `GoogleMapsPlacesV1ContentBlock` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1ContentBlock {
    /// content property.
    pub content: Option<GoogleTypeLocalizedText>,
    /// referencedPlaces property.
    pub referenced_places: Option<Vec<String>>,
}

/// `GoogleMapsPlacesV1PlaceContainingPlace` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1PlaceContainingPlace {
    /// id property.
    pub id: Option<String>,
    /// name property.
    pub name: Option<String>,
}

/// `GoogleMapsPlacesV1PlaceConsumerAlertDetails` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1PlaceConsumerAlertDetails {
    /// aboutLink property.
    pub about_link: Option<GoogleMapsPlacesV1PlaceConsumerAlertDetailsLink>,
    /// description property.
    pub description: Option<String>,
    /// title property.
    pub title: Option<String>,
}

/// `GoogleMapsPlacesV1PlaceParkingOptions` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1PlaceParkingOptions {
    /// freeGarageParking property.
    pub free_garage_parking: Option<bool>,
    /// freeParkingLot property.
    pub free_parking_lot: Option<bool>,
    /// freeStreetParking property.
    pub free_street_parking: Option<bool>,
    /// paidGarageParking property.
    pub paid_garage_parking: Option<bool>,
    /// paidParkingLot property.
    pub paid_parking_lot: Option<bool>,
    /// paidStreetParking property.
    pub paid_street_parking: Option<bool>,
    /// valetParking property.
    pub valet_parking: Option<bool>,
}

/// `GoogleMapsPlacesV1AddressDescriptorLandmark` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1AddressDescriptorLandmark {
    /// displayName property.
    pub display_name: Option<GoogleTypeLocalizedText>,
    /// name property.
    pub name: Option<String>,
    /// placeId property.
    pub place_id: Option<String>,
    /// spatialRelationship property.
    pub spatial_relationship: Option<String>,
    /// straightLineDistanceMeters property.
    pub straight_line_distance_meters: Option<f64>,
    /// travelDistanceMeters property.
    pub travel_distance_meters: Option<f64>,
    /// types property.
    pub types: Option<Vec<String>>,
}

/// `GoogleMapsPlacesV1EVChargeOptions` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1EVChargeOptions {
    /// connectorAggregation property.
    pub connector_aggregation: Option<Vec<GoogleMapsPlacesV1EVChargeOptionsConnectorAggregation>>,
    /// connectorCount property.
    pub connector_count: Option<i64>,
}

/// `GoogleMapsPlacesV1PlaceOpeningHoursSpecialDay` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1PlaceOpeningHoursSpecialDay {
    /// date property.
    pub date: Option<GoogleTypeDate>,
}

/// `GoogleMapsPlacesV1PriceRange` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1PriceRange {
    /// endPrice property.
    pub end_price: Option<GoogleTypeMoney>,
    /// startPrice property.
    pub start_price: Option<GoogleTypeMoney>,
}

/// `GoogleMapsPlacesV1PlaceGenerativeSummary` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleMapsPlacesV1PlaceGenerativeSummary {
    /// disclosureText property.
    pub disclosure_text: Option<GoogleTypeLocalizedText>,
    /// overview property.
    pub overview: Option<GoogleTypeLocalizedText>,
    /// overviewFlagContentUri property.
    pub overview_flag_content_uri: Option<String>,
}

/// `GoogleTypeLocalizedText` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleTypeLocalizedText {
    /// languageCode property.
    pub language_code: Option<String>,
    /// text property.
    pub text: Option<String>,
}

// =============================================================================
// ARGS TYPES (per-endpoint)
// =============================================================================

/// Arguments for [`places.places.get_builder`].
#[derive(Debug, Clone, Serialize, JsonHash)]
pub struct PlacesPlacesGetArgs {
    /// Path parameter: `name`.
    pub name: String,
    /// Query parameter: `languageCode`.
    pub language_code: Option<String>,
    /// Query parameter: `regionCode`.
    pub region_code: Option<String>,
    /// Query parameter: `sessionToken`.
    pub session_token: Option<String>,
}

// =============================================================================
// CLIENT FUNCTIONS (per-endpoint)
// =============================================================================

// -----------------------------------------------------------------------------
// GET v1/places/{placesId}
// -----------------------------------------------------------------------------

/// GET v1/places/{placesId}.
///
/// Takes client and args, builds the request, optionally applies modifications,
/// and returns a `TaskIterator` for execution.
///
/// # Arguments
///
/// * `client` - HTTP client for making the request
/// * `builder_mod` - Optional closure to modify the request builder (e.g., add headers)
///
/// # Example
///
/// ```ignore
/// let task = places_places_get_request(&client, &args, Some(|b| {
///     b.header("X-Custom-Header", "value")
/// }))?;
/// ```
#[inline]
pub fn places_places_get_request<R, F>(
    client: &SimpleHttpClient<R>,
    builder_mod: Option<F>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<GoogleMapsPlacesV1Place>, super::shared::ApiError>,
            Pending = super::shared::ApiPending,
            Spawner = super::shared::BoxedSendExecutionAction,
        > + Send
        + 'static,
    super::shared::ApiError,
>
where
    R: foundation_core::wire::simple_http::client::DnsResolver + Clone + Default + 'static,
    F: FnOnce(&mut ClientRequestBuilder<R>),
{
    let endpoint_url = format!("https://places.googleapis.com/v1/places/{{placesId}}",);

    let mut builder = client
        .get(&endpoint_url)
        .map_err(|e| super::shared::ApiError::RequestBuildFailed(e.to_string()))?;

    if let Some(f) = builder_mod {
        f(&mut builder);
    }

    Ok(builder
        .build_send_request()
        .map_err(|e: foundation_core::wire::simple_http::HttpClientError| {
            super::shared::ApiError::RequestBuildFailed(e.to_string())
        })?
        .map_ready(|intro| match intro {
            super::shared::RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status: usize = intro.0.into();
                if status < 200 || status >= 300 {
                    return Err(super::shared::ApiError::HttpStatus {
                        code: status as u16,
                        headers: headers.clone(),
                        body: None,
                    });
                }
                let body =
                    foundation_core::wire::simple_http::client::body_reader::collect_string(stream);
                let parsed: GoogleMapsPlacesV1Place =
                    serde_json::from_str(&body).map_err(|e: serde_json::Error| {
                        super::shared::ApiError::ParseFailed(e.to_string())
                    })?;
                Ok(ApiResponse {
                    status: status as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            super::shared::RequestIntro::Failed(e) => {
                Err(super::shared::ApiError::RequestSendFailed(e.to_string()))
            }
        })
        .map_pending(|_| super::shared::ApiPending::Sending))
}
