[package]
name = "intro"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords = ["Wasm_demo", "intro"]

[dependencies]
foundation_nostd = { workspace = true }
foundation_wasm = { workspace = true }


[lib]
crate-type = ["cdylib"]

[lints]
workspace = true
