[workspace]
# usually this iset to 1
resolver = "2"
# set members of your workspace
members = ["bin/*", "crates/*", "examples/todo", "examples/template/*"]

[workspace.package]
authors = ["EweStudios Consulting Limited"]
edition = "2021"
repository = "https://github.com/ewestudios/primal_web"
license = "Apache-2.0"
rust-version = "1.75"
keywords = ["ewe_platform", "ewestudios platform", "ewe"]

# -- global dev dependencies
[workspace.dev_dependencies]
trybuild = "1.0.63"
cargo-expand = { version = "1.0.85" }
tokio-test = { version = "0.4" }
cargo-watch = { version = "8.5.2" }
cargo-machete = { version = "0.6.2" }
wasm-pack = { version = "0.12.1" }
wasm-bindgen-cli = { version = "0.2.29" }
wasm-bindgen-test = { version = "0.3.42" }

# -- global dependencies
[workspace.dependencies]
# general crates
cfg-if = { version = "1.0" }

# -- async crates
rand = { version = "0.8.5" }
futures = { verison = "0.3" }
crossbeam = { version = "0.8" }
lazy_static = { version = "1.4.0" }
async-channel = { version = "2.2" }
tokio = { version = "1.36", features = ["full"] }
tokio-test = { version = "0.4" }

# -- error crates
anyhow = { version = "1.0.80" }
thiserror = { version = "1.0.57" }

# -- serialization crates
toml = { version = "0.8.10" }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0.114" }
serde_with = { version = "3.6.1" }


# -- tracing crates
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18" }

[workspace.lints.rust]
unsafe_code = "forbid"
unused = "warn"        # for experimental dev

[workspace.lints.clippy]
pedantic = "warn"
