[workspace]
# usually this iset to 1
resolver = "2"
# set members of your workspace
members = ["bin/*", "crates/*", "backends/*", "examples/template/*"]
exclude = ["crates/html-macro"]

[workspace.package]
edition = "2021"
rust-version = "1.75"
license = "Apache-2.0"
authors = ["EweStudios Consulting Limited"]
repository = "https://github.com/ewestudios/primal_web"
keywords = ["ewe_platform", "ewestudios platform", "ewe"]


# -- global dependencies
[workspace.dependencies]
# internal packages so others can use them
ewe-web = { path = "./crates/web" }
ewe-logs = { path = "./crates/logs", default-features = false }
ewe-spawn = { path = "./crates/spawn" }
ewe-watchers = { path = "./crates/watchers" }
ewe-temple = { path = "./crates/temple" }
ewe-templates = { path = "./crates/templates" }
ewe-templates-macro = { path = "./crates/template-macro" }
ewe-mem = { path = "./crates/mem" }
ewe-routing = { path = "./crates/routing" }
ewe-html = { path = "./crates/html" }
ewe-html-macro = { path = "./crates/html-macro" }
ewe-platform = { path = "./crates/platform" }
ewe-channels = { path = "./crates/channels" }
ewe-domain = { path = "./crates/domain" }
ewe-domain-macro = { path = "./crates/domain-macro" }

[workspace.lints.rust]
unsafe_code = "forbid"
unused = "allow"       # for experimental dev

[workspace.lints.clippy]
pedantic = "warn"
