[workspace]
# usually this iset to 1
resolver = "2"
# set members of your workspace
members = ["bin/*", "crates/*"]

[workspace.package]
authors = ["EweStudios Consulting Limited"]
edition = "2021"
repository = "https://github.com/ewestudios/primal_web"
license = "Apache-2.0"
rust-version = "1.75"
keywords = [
    "watcher",
    "watchful",
    "file watcher",
    "command runner",
    "change watcher",
]

# -- global dev dependencies
[workspace.dev_dependencies]
cargo-watch = { version = "8.5.2" }

# -- global dependencies
[workspace.dependencies]
# -- async crates
futures = { verison = "0.3" }
crossbeam = { version = "0.8" }
tokio = { version = "1", features = ["full"] }

# -- error crates
anyhow = { version = "1.0.80" }
thiserror = { version = "1.0.57" }

# -- serialization crates
toml = { version = "0.8.10" }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0.114" }
serde_with = { version = "3.6.1" }


# -- tracing crates
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18" }

[workspace.lints.rust]
unsafe_code = "forbid"
unused = "allow"       # for experimental dev

[workspace.lints.clippy]
pedantic = "warn"
