[package]
name = "ewe_html_macro"
version = "0.0.1"
description = "Macro package for the ewe_html crate"
edition.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
keywords.workspace = true
authors = ["Tomas Vallotton <tvallotton@uc.cl>", "alex.ewetumo@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.40"
quote = "1.0.20"
syn = { version = "2.0.60", features = ["full"] }

[dev-dependencies]
trybuild = "1.0.63"
