[workspace]
members = ["retro_project"]
resolver = "2"

[workspace.package]
authors = ["EweStudios Consulting Limited"]
edition = "2021"
keywords = ["workspace_project"]
license = "Apache-2.0"
repository = "https://github.com/ewe-studios/ewe_platform"
rust-version = "1.75"

[workspace.lints.clippy]
blocks_in_conditions = "allow"
items-after-statements = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"
must_use_candidate = "allow"
no-effect-underscore-binding = "allow"
pedantic = "warn"
