[package]
name = "foundation_deployment_neon"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]

[features]
neon = []
neon_all = [
    "neon_api",
    "neon_auth",
    "neon_compute",
    "neon_invitations",
    "neon_keys",
    "neon_me",
    "neon_members",
    "neon_organizations",
    "neon_projects",
    "neon_regions",
]
neon_api = []
neon_auth = []
neon_compute = []
neon_invitations = []
neon_keys = []
neon_me = []
neon_members = []
neon_organizations = []
neon_projects = []
neon_regions = []

[lints]
workspace = true
