[package]
name = "platform_ios"
version = "0.1.0"
edition = "2021"
rust-version = "1.87"
publish = false

[lib]
name = "platform_ios_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[[bin]]
name = "platform_ios"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = ["codegen"] }
foundation_platform = { path = "../../../backends/foundation_platform" }

[dependencies]
tauri = { version = "2.11.5", features = [] }
foundation_core = { path = "../../../backends/foundation_core", version = "0.0.3", features = ["multi"] }
foundation_platform = { path = "../../../backends/foundation_platform" }
foundation_ui_traits = { path = "../../../backends/foundation_ui_traits" }
foundation_wasm = { path = "../../../backends/foundation_wasm" }
foundation_macros = { path = "../../../backends/foundation_macros" }
foundation_nostd = { path = "../../../backends/foundation_nostd" }
foundation_wasm_ui = { path = "../../../backends/foundation_wasm_ui" }
serde = { workspace = true }
serde_json = { workspace = true }
