[package]
name = "clonables"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords = ["clonable", "clonable-types"]

[dependencies]

[lints]
workspace = true
