[package]
name = "platform_demo"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
foundation_platform = { path = "../../backends/foundation_platform" }
tauri = { version = "2.11.5", features = [] }
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
foundation_platform = { path = "../../backends/foundation_platform" }

[lints]
workspace = true
