[package]
name = "foundation_wasm_testbed"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "CLI-driven test harness for wasm32-unknown-unknown"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = { workspace = true }
walrus = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1", features = ["full"] }
foundation_macros = { workspace = true }
foundation_nostd = { workspace = true }
tempfile = "3"
which = "7"
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
indicatif = { workspace = true }
portpicker = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "json"] }
fs_extra = { workspace = true }
tiny_http = { workspace = true }

[dev-dependencies]
tracing-test = { version = "0.2", features = ["no-env-filter"] }
serial_test = { workspace = true }

[lints]
workspace = true
