//! Auto-generated API module for gcp/displayvideo sites.
//!
//! Generated by `cargo run --bin ewe_platform gen_api`.
//! DO NOT EDIT MANUALLY.
//!
//! Feature flag: `gcp_displayvideo_sites `

#![cfg(feature = "gcp_displayvideo_sites")]
#![allow(clippy::too_many_arguments, clippy::type_complexity)]
#![allow(
    clippy::missing_errors_doc,
    clippy::doc_markdown,
    clippy::useless_format
)]
#![allow(unused_imports)]

use foundation_core::valtron::{TaskIterator, TaskIteratorExt};
use foundation_core::wire::simple_http::client::{ClientRequestBuilder, SimpleHttpClient};
use foundation_macros::JsonHash;
use serde::{Deserialize, Serialize};

// Import shared types used by this module
use super::shared::Empty;

use super::shared::ApiResponse;

// =============================================================================
// TYPE DECLARATIONS
// =============================================================================

/// `ListSitesResponse` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct ListSitesResponse {
    /// nextPageToken property.
    pub next_page_token: Option<String>,
    /// sites property.
    pub sites: Option<Vec<Site>>,
}

/// `Site` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct Site {
    /// name property.
    pub name: Option<String>,
    /// urlOrAppId property.
    pub url_or_app_id: Option<String>,
}

// =============================================================================
// ARGS TYPES (per-endpoint)
// =============================================================================

/// Arguments for [`displayvideo.advertisers.channels.sites.create_builder`].
#[derive(Debug, Clone, Serialize, JsonHash)]
pub struct DisplayvideoAdvertisersChannelsSitesCreateArgs {
    /// Path parameter: `advertiserId`.
    pub advertiser_id: String,
    /// Path parameter: `channelId`.
    pub channel_id: String,
    /// Query parameter: `partnerId`.
    pub partner_id: Option<String>,
}

/// Arguments for [`displayvideo.advertisers.channels.sites.delete_builder`].
#[derive(Debug, Clone, Serialize, JsonHash)]
pub struct DisplayvideoAdvertisersChannelsSitesDeleteArgs {
    /// Path parameter: `advertiserId`.
    pub advertiser_id: String,
    /// Path parameter: `channelId`.
    pub channel_id: String,
    /// Path parameter: `urlOrAppId`.
    pub url_or_app_id: String,
    /// Query parameter: `partnerId`.
    pub partner_id: Option<String>,
}

/// Arguments for [`displayvideo.advertisers.channels.sites.list_builder`].
#[derive(Debug, Clone, Serialize, JsonHash)]
pub struct DisplayvideoAdvertisersChannelsSitesListArgs {
    /// Path parameter: `advertiserId`.
    pub advertiser_id: String,
    /// Path parameter: `channelId`.
    pub channel_id: String,
    /// Query parameter: `filter`.
    pub filter: Option<String>,
    /// Query parameter: `orderBy`.
    pub order_by: Option<String>,
    /// Query parameter: `pageSize`.
    pub page_size: Option<String>,
    /// Query parameter: `pageToken`.
    pub page_token: Option<String>,
    /// Query parameter: `partnerId`.
    pub partner_id: Option<String>,
}

/// Arguments for [`displayvideo.partners.channels.sites.create_builder`].
#[derive(Debug, Clone, Serialize, JsonHash)]
pub struct DisplayvideoPartnersChannelsSitesCreateArgs {
    /// Path parameter: `partnerId`.
    pub partner_id: String,
    /// Path parameter: `channelId`.
    pub channel_id: String,
    /// Query parameter: `advertiserId`.
    pub advertiser_id: Option<String>,
}

/// Arguments for [`displayvideo.partners.channels.sites.delete_builder`].
#[derive(Debug, Clone, Serialize, JsonHash)]
pub struct DisplayvideoPartnersChannelsSitesDeleteArgs {
    /// Path parameter: `partnerId`.
    pub partner_id: String,
    /// Path parameter: `channelId`.
    pub channel_id: String,
    /// Path parameter: `urlOrAppId`.
    pub url_or_app_id: String,
    /// Query parameter: `advertiserId`.
    pub advertiser_id: Option<String>,
}

/// Arguments for [`displayvideo.partners.channels.sites.list_builder`].
#[derive(Debug, Clone, Serialize, JsonHash)]
pub struct DisplayvideoPartnersChannelsSitesListArgs {
    /// Path parameter: `partnerId`.
    pub partner_id: String,
    /// Path parameter: `channelId`.
    pub channel_id: String,
    /// Query parameter: `advertiserId`.
    pub advertiser_id: Option<String>,
    /// Query parameter: `filter`.
    pub filter: Option<String>,
    /// Query parameter: `orderBy`.
    pub order_by: Option<String>,
    /// Query parameter: `pageSize`.
    pub page_size: Option<String>,
    /// Query parameter: `pageToken`.
    pub page_token: Option<String>,
}

// =============================================================================
// CLIENT FUNCTIONS (per-endpoint)
// =============================================================================

// -----------------------------------------------------------------------------
// POST v4/advertisers/{advertiserId}/channels/{channelsId}/sites
// -----------------------------------------------------------------------------

/// POST v4/advertisers/{advertiserId}/channels/{channelsId}/sites.
///
/// Takes client and args, builds the request, optionally applies modifications,
/// and returns a `TaskIterator` for execution.
///
/// # Arguments
///
/// * `client` - HTTP client for making the request
/// * `args` - Request arguments (path params, query params, body)
/// * `builder_mod` - Optional closure to modify the request builder (e.g., add headers)
///
/// # Example
///
/// ```ignore
/// let task = displayvideo_advertisers_channels_sites_create_request(&client, &args, Some(|b| {
///     b.header("X-Custom-Header", "value")
/// }))?;
/// ```
#[inline]
pub fn displayvideo_advertisers_channels_sites_create_request<R, F>(
    client: &SimpleHttpClient<R>,
    args: &DisplayvideoAdvertisersChannelsSitesCreateArgs,
    builder_mod: Option<F>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<Site>, super::shared::ApiError>,
            Pending = super::shared::ApiPending,
            Spawner = super::shared::BoxedSendExecutionAction,
        > + Send
        + 'static,
    super::shared::ApiError,
>
where
    R: foundation_core::wire::simple_http::client::DnsResolver + Clone + Default + 'static,
    F: FnOnce(&mut ClientRequestBuilder<R>),
{
    let endpoint_url = format!(
        "https://displayvideo.googleapis.com/v4/advertisers/{}/channels/{{channelsId}}/sites",
        args.advertiser_id,
    );

    let mut builder = client
        .post(&endpoint_url)
        .map_err(|e| super::shared::ApiError::RequestBuildFailed(e.to_string()))?;

    if let Some(f) = builder_mod {
        f(&mut builder);
    }

    Ok(builder
        .build_send_request()
        .map_err(|e: foundation_core::wire::simple_http::HttpClientError| {
            super::shared::ApiError::RequestBuildFailed(e.to_string())
        })?
        .map_ready(|intro| match intro {
            super::shared::RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status: usize = intro.0.into();
                if status < 200 || status >= 300 {
                    return Err(super::shared::ApiError::HttpStatus {
                        code: status as u16,
                        headers: headers.clone(),
                        body: None,
                    });
                }
                let body =
                    foundation_core::wire::simple_http::client::body_reader::collect_string(stream);
                let parsed: Site =
                    serde_json::from_str(&body).map_err(|e: serde_json::Error| {
                        super::shared::ApiError::ParseFailed(e.to_string())
                    })?;
                Ok(ApiResponse {
                    status: status as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            super::shared::RequestIntro::Failed(e) => {
                Err(super::shared::ApiError::RequestSendFailed(e.to_string()))
            }
        })
        .map_pending(|_| super::shared::ApiPending::Sending))
}

// -----------------------------------------------------------------------------
// DELETE v4/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}
// -----------------------------------------------------------------------------

/// DELETE v4/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}.
///
/// Takes client and args, builds the request, optionally applies modifications,
/// and returns a `TaskIterator` for execution.
///
/// # Arguments
///
/// * `client` - HTTP client for making the request
/// * `args` - Request arguments (path params, query params, body)
/// * `builder_mod` - Optional closure to modify the request builder (e.g., add headers)
///
/// # Example
///
/// ```ignore
/// let task = displayvideo_advertisers_channels_sites_delete_request(&client, &args, Some(|b| {
///     b.header("X-Custom-Header", "value")
/// }))?;
/// ```
#[inline]
pub fn displayvideo_advertisers_channels_sites_delete_request<R, F>(
    client: &SimpleHttpClient<R>,
    args: &DisplayvideoAdvertisersChannelsSitesDeleteArgs,
    builder_mod: Option<F>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<Empty>, super::shared::ApiError>,
            Pending = super::shared::ApiPending,
            Spawner = super::shared::BoxedSendExecutionAction,
        > + Send
        + 'static,
    super::shared::ApiError,
>
where
    R: foundation_core::wire::simple_http::client::DnsResolver + Clone + Default + 'static,
    F: FnOnce(&mut ClientRequestBuilder<R>),
{
    let endpoint_url = format!(
        "https://displayvideo.googleapis.com/v4/advertisers/{}/channels/{{channelsId}}/sites/{{sitesId}}",
        args.advertiser_id,
    );

    let mut builder = client
        .delete(&endpoint_url)
        .map_err(|e| super::shared::ApiError::RequestBuildFailed(e.to_string()))?;

    if let Some(f) = builder_mod {
        f(&mut builder);
    }

    Ok(builder
        .build_send_request()
        .map_err(|e: foundation_core::wire::simple_http::HttpClientError| {
            super::shared::ApiError::RequestBuildFailed(e.to_string())
        })?
        .map_ready(|intro| match intro {
            super::shared::RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status: usize = intro.0.into();
                if status < 200 || status >= 300 {
                    return Err(super::shared::ApiError::HttpStatus {
                        code: status as u16,
                        headers: headers.clone(),
                        body: None,
                    });
                }
                let body =
                    foundation_core::wire::simple_http::client::body_reader::collect_string(stream);
                let parsed: Empty =
                    serde_json::from_str(&body).map_err(|e: serde_json::Error| {
                        super::shared::ApiError::ParseFailed(e.to_string())
                    })?;
                Ok(ApiResponse {
                    status: status as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            super::shared::RequestIntro::Failed(e) => {
                Err(super::shared::ApiError::RequestSendFailed(e.to_string()))
            }
        })
        .map_pending(|_| super::shared::ApiPending::Sending))
}

// -----------------------------------------------------------------------------
// GET v4/advertisers/{advertisersId}/channels/{channelsId}/sites
// -----------------------------------------------------------------------------

/// GET v4/advertisers/{advertisersId}/channels/{channelsId}/sites.
///
/// Takes client and args, builds the request, optionally applies modifications,
/// and returns a `TaskIterator` for execution.
///
/// # Arguments
///
/// * `client` - HTTP client for making the request
/// * `builder_mod` - Optional closure to modify the request builder (e.g., add headers)
///
/// # Example
///
/// ```ignore
/// let task = displayvideo_advertisers_channels_sites_list_request(&client, &args, Some(|b| {
///     b.header("X-Custom-Header", "value")
/// }))?;
/// ```
#[inline]
pub fn displayvideo_advertisers_channels_sites_list_request<R, F>(
    client: &SimpleHttpClient<R>,
    builder_mod: Option<F>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<ListSitesResponse>, super::shared::ApiError>,
            Pending = super::shared::ApiPending,
            Spawner = super::shared::BoxedSendExecutionAction,
        > + Send
        + 'static,
    super::shared::ApiError,
>
where
    R: foundation_core::wire::simple_http::client::DnsResolver + Clone + Default + 'static,
    F: FnOnce(&mut ClientRequestBuilder<R>),
{
    let endpoint_url = format!(
        "https://displayvideo.googleapis.com/v4/advertisers/{{advertisersId}}/channels/{{channelsId}}/sites",
    );

    let mut builder = client
        .get(&endpoint_url)
        .map_err(|e| super::shared::ApiError::RequestBuildFailed(e.to_string()))?;

    if let Some(f) = builder_mod {
        f(&mut builder);
    }

    Ok(builder
        .build_send_request()
        .map_err(|e: foundation_core::wire::simple_http::HttpClientError| {
            super::shared::ApiError::RequestBuildFailed(e.to_string())
        })?
        .map_ready(|intro| match intro {
            super::shared::RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status: usize = intro.0.into();
                if status < 200 || status >= 300 {
                    return Err(super::shared::ApiError::HttpStatus {
                        code: status as u16,
                        headers: headers.clone(),
                        body: None,
                    });
                }
                let body =
                    foundation_core::wire::simple_http::client::body_reader::collect_string(stream);
                let parsed: ListSitesResponse =
                    serde_json::from_str(&body).map_err(|e: serde_json::Error| {
                        super::shared::ApiError::ParseFailed(e.to_string())
                    })?;
                Ok(ApiResponse {
                    status: status as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            super::shared::RequestIntro::Failed(e) => {
                Err(super::shared::ApiError::RequestSendFailed(e.to_string()))
            }
        })
        .map_pending(|_| super::shared::ApiPending::Sending))
}

// -----------------------------------------------------------------------------
// POST v4/partners/{partnerId}/channels/{channelsId}/sites
// -----------------------------------------------------------------------------

/// POST v4/partners/{partnerId}/channels/{channelsId}/sites.
///
/// Takes client and args, builds the request, optionally applies modifications,
/// and returns a `TaskIterator` for execution.
///
/// # Arguments
///
/// * `client` - HTTP client for making the request
/// * `args` - Request arguments (path params, query params, body)
/// * `builder_mod` - Optional closure to modify the request builder (e.g., add headers)
///
/// # Example
///
/// ```ignore
/// let task = displayvideo_partners_channels_sites_create_request(&client, &args, Some(|b| {
///     b.header("X-Custom-Header", "value")
/// }))?;
/// ```
#[inline]
pub fn displayvideo_partners_channels_sites_create_request<R, F>(
    client: &SimpleHttpClient<R>,
    args: &DisplayvideoPartnersChannelsSitesCreateArgs,
    builder_mod: Option<F>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<Site>, super::shared::ApiError>,
            Pending = super::shared::ApiPending,
            Spawner = super::shared::BoxedSendExecutionAction,
        > + Send
        + 'static,
    super::shared::ApiError,
>
where
    R: foundation_core::wire::simple_http::client::DnsResolver + Clone + Default + 'static,
    F: FnOnce(&mut ClientRequestBuilder<R>),
{
    let endpoint_url = format!(
        "https://displayvideo.googleapis.com/v4/partners/{}/channels/{{channelsId}}/sites",
        args.partner_id,
    );

    let mut builder = client
        .post(&endpoint_url)
        .map_err(|e| super::shared::ApiError::RequestBuildFailed(e.to_string()))?;

    if let Some(f) = builder_mod {
        f(&mut builder);
    }

    Ok(builder
        .build_send_request()
        .map_err(|e: foundation_core::wire::simple_http::HttpClientError| {
            super::shared::ApiError::RequestBuildFailed(e.to_string())
        })?
        .map_ready(|intro| match intro {
            super::shared::RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status: usize = intro.0.into();
                if status < 200 || status >= 300 {
                    return Err(super::shared::ApiError::HttpStatus {
                        code: status as u16,
                        headers: headers.clone(),
                        body: None,
                    });
                }
                let body =
                    foundation_core::wire::simple_http::client::body_reader::collect_string(stream);
                let parsed: Site =
                    serde_json::from_str(&body).map_err(|e: serde_json::Error| {
                        super::shared::ApiError::ParseFailed(e.to_string())
                    })?;
                Ok(ApiResponse {
                    status: status as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            super::shared::RequestIntro::Failed(e) => {
                Err(super::shared::ApiError::RequestSendFailed(e.to_string()))
            }
        })
        .map_pending(|_| super::shared::ApiPending::Sending))
}

// -----------------------------------------------------------------------------
// DELETE v4/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}
// -----------------------------------------------------------------------------

/// DELETE v4/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}.
///
/// Takes client and args, builds the request, optionally applies modifications,
/// and returns a `TaskIterator` for execution.
///
/// # Arguments
///
/// * `client` - HTTP client for making the request
/// * `args` - Request arguments (path params, query params, body)
/// * `builder_mod` - Optional closure to modify the request builder (e.g., add headers)
///
/// # Example
///
/// ```ignore
/// let task = displayvideo_partners_channels_sites_delete_request(&client, &args, Some(|b| {
///     b.header("X-Custom-Header", "value")
/// }))?;
/// ```
#[inline]
pub fn displayvideo_partners_channels_sites_delete_request<R, F>(
    client: &SimpleHttpClient<R>,
    args: &DisplayvideoPartnersChannelsSitesDeleteArgs,
    builder_mod: Option<F>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<Empty>, super::shared::ApiError>,
            Pending = super::shared::ApiPending,
            Spawner = super::shared::BoxedSendExecutionAction,
        > + Send
        + 'static,
    super::shared::ApiError,
>
where
    R: foundation_core::wire::simple_http::client::DnsResolver + Clone + Default + 'static,
    F: FnOnce(&mut ClientRequestBuilder<R>),
{
    let endpoint_url = format!(
        "https://displayvideo.googleapis.com/v4/partners/{}/channels/{{channelsId}}/sites/{{sitesId}}",
        args.partner_id,
    );

    let mut builder = client
        .delete(&endpoint_url)
        .map_err(|e| super::shared::ApiError::RequestBuildFailed(e.to_string()))?;

    if let Some(f) = builder_mod {
        f(&mut builder);
    }

    Ok(builder
        .build_send_request()
        .map_err(|e: foundation_core::wire::simple_http::HttpClientError| {
            super::shared::ApiError::RequestBuildFailed(e.to_string())
        })?
        .map_ready(|intro| match intro {
            super::shared::RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status: usize = intro.0.into();
                if status < 200 || status >= 300 {
                    return Err(super::shared::ApiError::HttpStatus {
                        code: status as u16,
                        headers: headers.clone(),
                        body: None,
                    });
                }
                let body =
                    foundation_core::wire::simple_http::client::body_reader::collect_string(stream);
                let parsed: Empty =
                    serde_json::from_str(&body).map_err(|e: serde_json::Error| {
                        super::shared::ApiError::ParseFailed(e.to_string())
                    })?;
                Ok(ApiResponse {
                    status: status as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            super::shared::RequestIntro::Failed(e) => {
                Err(super::shared::ApiError::RequestSendFailed(e.to_string()))
            }
        })
        .map_pending(|_| super::shared::ApiPending::Sending))
}

// -----------------------------------------------------------------------------
// GET v4/partners/{partnersId}/channels/{channelsId}/sites
// -----------------------------------------------------------------------------

/// GET v4/partners/{partnersId}/channels/{channelsId}/sites.
///
/// Takes client and args, builds the request, optionally applies modifications,
/// and returns a `TaskIterator` for execution.
///
/// # Arguments
///
/// * `client` - HTTP client for making the request
/// * `builder_mod` - Optional closure to modify the request builder (e.g., add headers)
///
/// # Example
///
/// ```ignore
/// let task = displayvideo_partners_channels_sites_list_request(&client, &args, Some(|b| {
///     b.header("X-Custom-Header", "value")
/// }))?;
/// ```
#[inline]
pub fn displayvideo_partners_channels_sites_list_request<R, F>(
    client: &SimpleHttpClient<R>,
    builder_mod: Option<F>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<ListSitesResponse>, super::shared::ApiError>,
            Pending = super::shared::ApiPending,
            Spawner = super::shared::BoxedSendExecutionAction,
        > + Send
        + 'static,
    super::shared::ApiError,
>
where
    R: foundation_core::wire::simple_http::client::DnsResolver + Clone + Default + 'static,
    F: FnOnce(&mut ClientRequestBuilder<R>),
{
    let endpoint_url = format!(
        "https://displayvideo.googleapis.com/v4/partners/{{partnersId}}/channels/{{channelsId}}/sites",
    );

    let mut builder = client
        .get(&endpoint_url)
        .map_err(|e| super::shared::ApiError::RequestBuildFailed(e.to_string()))?;

    if let Some(f) = builder_mod {
        f(&mut builder);
    }

    Ok(builder
        .build_send_request()
        .map_err(|e: foundation_core::wire::simple_http::HttpClientError| {
            super::shared::ApiError::RequestBuildFailed(e.to_string())
        })?
        .map_ready(|intro| match intro {
            super::shared::RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status: usize = intro.0.into();
                if status < 200 || status >= 300 {
                    return Err(super::shared::ApiError::HttpStatus {
                        code: status as u16,
                        headers: headers.clone(),
                        body: None,
                    });
                }
                let body =
                    foundation_core::wire::simple_http::client::body_reader::collect_string(stream);
                let parsed: ListSitesResponse =
                    serde_json::from_str(&body).map_err(|e: serde_json::Error| {
                        super::shared::ApiError::ParseFailed(e.to_string())
                    })?;
                Ok(ApiResponse {
                    status: status as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            super::shared::RequestIntro::Failed(e) => {
                Err(super::shared::ApiError::RequestSendFailed(e.to_string()))
            }
        })
        .map_pending(|_| super::shared::ApiPending::Sending))
}
