name = "foundation-keychain"
main = "build/index.js"
compatibility_date = "2025-07-19"

[[d1_databases]]
binding = "KEYCHAIN_DB"
database_name = "keychain-db"
database_id = "keychain-db-local"

[[kv_namespaces]]
binding = "KEYCHAIN_KV"
id = "keychain-kv-local"

[[durable_objects.bindings]]
name = "SIGNALR_HUB"
class_name = "SignalRHub"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SignalRHub"]
