[package]
description = "Foundation deployment providers for multi-cloud deployments"
keywords = [
    "ewe-platform",
    "deployment",
    "cloud",
    "infrastructure",
]
name = "foundation_deployment"
version = "0.0.1"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.license]
workspace = true

[package.repository]
workspace = true

[package.rust-version]
workspace = true

[dependencies]
base85rs = "0.1"
dirs = "5.0"
http = "1.4.0"
regex = "1.10"
serde_yaml = "0.9"
sha2 = "0.10"
toml = "0.8"
urlencoding = "2.1"
walkdir = "2.5"

[dependencies.chrono]
workspace = true

[dependencies.derive_more]
workspace = true

[dependencies.foundation_core]
workspace = true

[dependencies.foundation_netio]
features = ["ssl", "multi"]
workspace = true

[dependencies.foundation_db]
workspace = true

[dependencies.foundation_macros]
workspace = true

[dependencies.serde]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.tracing]
workspace = true

[dev-dependencies]
tracing-subscriber = "0.3"
tracing-test = "0.2"

[features]
default = []
multi = ["foundation_core/multi", "foundation_netio/multi", "foundation_db/multi"]
aws = []
huggingface = []
mongodb = []
standard = []

[lints]
workspace = true
