//! Auto-generated API module for gcp/agentregistry mcpServers:search.
//!
//! Generated by `cargo run --bin ewe_platform gen_api`.
//! DO NOT EDIT MANUALLY.
//!
//! Feature flag: `gcp_agentregistry_mcp_servers_search `

#![cfg(feature = "gcp_agentregistry_mcp_servers_search")]
#![allow(clippy::too_many_arguments, clippy::type_complexity)]
#![allow(
    clippy::missing_errors_doc,
    clippy::doc_markdown,
    clippy::useless_format
)]

use foundation_core::valtron::{execute, StreamIterator, TaskIterator, TaskIteratorExt};
use foundation_core::wire::simple_http::client::{ClientRequestBuilder, SimpleHttpClient};
use foundation_macros::JsonHash;
use serde::{Deserialize, Serialize};

use super::shared::{ApiError, ApiPending, ApiResponse};

// =============================================================================
// TYPE DECLARATIONS
// =============================================================================

/// `McpServer` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct McpServer {
    /// attributes property.
    pub attributes: Option<serde_json::Value>,
    /// createTime property.
    pub create_time: Option<String>,
    /// description property.
    pub description: Option<String>,
    /// displayName property.
    pub display_name: Option<String>,
    /// interfaces property.
    pub interfaces: Option<Vec<Interface>>,
    /// mcpServerId property.
    pub mcp_server_id: Option<String>,
    /// name property.
    pub name: Option<String>,
    /// tools property.
    pub tools: Option<Vec<Tool>>,
    /// updateTime property.
    pub update_time: Option<String>,
}

/// `SearchMcpServersResponse` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct SearchMcpServersResponse {
    /// mcpServers property.
    pub mcp_servers: Option<Vec<McpServer>>,
    /// nextPageToken property.
    pub next_page_token: Option<String>,
}

/// `Annotations` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct Annotations {
    /// destructiveHint property.
    pub destructive_hint: Option<bool>,
    /// idempotentHint property.
    pub idempotent_hint: Option<bool>,
    /// openWorldHint property.
    pub open_world_hint: Option<bool>,
    /// readOnlyHint property.
    pub read_only_hint: Option<bool>,
    /// title property.
    pub title: Option<String>,
}

/// `Interface` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct Interface {
    /// protocolBinding property.
    pub protocol_binding: Option<String>,
    /// url property.
    pub url: Option<String>,
}

/// `Tool` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct Tool {
    /// annotations property.
    pub annotations: Option<Annotations>,
    /// description property.
    pub description: Option<String>,
    /// name property.
    pub name: Option<String>,
}

// =============================================================================
// ARGS TYPES (per-endpoint)
// =============================================================================

/// Arguments for [`agentregistry.projects.locations.mcpServers.search_builder`].
#[derive(Debug, Clone, Serialize, JsonHash)]
pub struct AgentregistryProjectsLocationsMcpServersSearchArgs {
    /// Path parameter: `parent`.
    pub parent: String,
}

// =============================================================================
// CLIENT FUNCTIONS (per-endpoint)
// =============================================================================

// -----------------------------------------------------------------------------
// POST v1alpha/projects/{projectsId}/locations/{locationsId}/mcpServers:search
// -----------------------------------------------------------------------------

/// POST v1alpha/projects/{projectsId}/locations/{locationsId}/mcpServers:search.
///
/// Takes client and args, builds the request, optionally applies modifications,
/// and returns a `TaskIterator` for execution.
///
/// # Arguments
///
/// * `client` - HTTP client for making the request
/// * `builder_mod` - Optional closure to modify the request builder (e.g., add headers)
///
/// # Example
///
/// ```ignore
/// let task = agentregistry_projects_locations_mcp_servers_search_request(&client, &args, Some(|b| {
///     b.header("X-Custom-Header", "value")
/// }))?;
/// ```
#[inline]
pub fn agentregistry_projects_locations_mcp_servers_search_request<R, F>(
    client: &SimpleHttpClient<R>,
    builder_mod: Option<F>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<SearchMcpServersResponse>, super::shared::ApiError>,
            Pending = super::shared::ApiPending,
            Spawner = super::shared::BoxedSendExecutionAction,
        > + Send
        + 'static,
    super::shared::ApiError,
>
where
    R: foundation_core::wire::simple_http::client::DnsResolver + Clone + Default + 'static,
    F: FnOnce(&mut ClientRequestBuilder<R>),
{
    let endpoint_url = format!(
        "https://agentregistry.googleapis.com/v1alpha/projects/{{projectsId}}/locations/{{locationsId}}/mcpServers:search",
    );

    let mut builder = client
        .post(&endpoint_url)
        .map_err(|e| super::shared::ApiError::RequestBuildFailed(e.to_string()))?;

    if let Some(f) = builder_mod {
        f(&mut builder);
    }

    Ok(builder
        .build_send_request()
        .map_err(|e: foundation_core::wire::simple_http::HttpClientError| {
            super::shared::ApiError::RequestBuildFailed(e.to_string())
        })?
        .map_ready(|intro| match intro {
            super::shared::RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status: usize = intro.0.into();
                if status < 200 || status >= 300 {
                    return Err(super::shared::ApiError::HttpStatus {
                        code: status as u16,
                        headers: headers.clone(),
                        body: None,
                    });
                }
                let body =
                    foundation_core::wire::simple_http::client::body_reader::collect_string(stream);
                let parsed: SearchMcpServersResponse =
                    serde_json::from_str(&body).map_err(|e: serde_json::Error| {
                        super::shared::ApiError::ParseFailed(e.to_string())
                    })?;
                Ok(ApiResponse {
                    status: status as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            super::shared::RequestIntro::Failed(e) => {
                Err(super::shared::ApiError::RequestSendFailed(e.to_string()))
            }
        })
        .map_pending(|_| super::shared::ApiPending::Sending))
}
