[env]
ENVIRONMENT = { value = "dev" }
CONFIG_DIR = { value = "./config"}
PUBLIC_DIR = { value = "./public"}
BINARY_NAME = { value ="app", force = true }
PROJECT_DIRECTORY = { value =".", relative = true, force = true }

[alias]
