//! Auto-generated provider module for gcp/bigtableadmin.
//!
//! Generated by `cargo run --bin ewe_platform gen_api`.
//! DO NOT EDIT MANUALLY.

#![cfg(feature = "gcp_bigtableadmin")]
#![allow(clippy::too_many_arguments, clippy::type_complexity)]
#![allow(clippy::missing_errors_doc, clippy::doc_markdown, clippy::useless_format)]
#![allow(unused_imports)]

pub mod shared;

#[cfg(feature = "gcp_bigtableadmin_app_profiles")]
pub mod app_profiles;
#[cfg(feature = "gcp_bigtableadmin_authorized_views")]
pub mod authorized_views;
#[cfg(feature = "gcp_bigtableadmin_backups")]
pub mod backups;
#[cfg(feature = "gcp_bigtableadmin_backups_copy")]
pub mod backups_copy;
#[cfg(feature = "gcp_bigtableadmin_clusters")]
pub mod clusters;
#[cfg(feature = "gcp_bigtableadmin_hot_tablets")]
pub mod hot_tablets;
#[cfg(feature = "gcp_bigtableadmin_instances")]
pub mod instances;
#[cfg(feature = "gcp_bigtableadmin_locations")]
pub mod locations;
#[cfg(feature = "gcp_bigtableadmin_logical_views")]
pub mod logical_views;
#[cfg(feature = "gcp_bigtableadmin_materialized_views")]
pub mod materialized_views;
#[cfg(feature = "gcp_bigtableadmin_memory_layer")]
pub mod memory_layer;
#[cfg(feature = "gcp_bigtableadmin_memory_layers")]
pub mod memory_layers;
#[cfg(feature = "gcp_bigtableadmin_operations")]
pub mod operations;
#[cfg(feature = "gcp_bigtableadmin_schema_bundles")]
pub mod schema_bundles;
#[cfg(feature = "gcp_bigtableadmin_tables")]
pub mod tables;
#[cfg(feature = "gcp_bigtableadmin_tables_restore")]
pub mod tables_restore;
