[package]
name = "foundation_nostd"
version = "0.0.4"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Foundational nostd core implementation for the ewe_platform project"
keywords = ["foundation_nostd"]

[features]
default = []
std = []
js-event-loop = []

[lints]
workspace = true

[dev-dependencies]
serial_test = { workspace = true }
tracing-test = { version = "0.2",  features = ["no-env-filter"] }
tracing-subscriber = "0.3"
ntest = { workspace = true }
foundation_testing = { path = "../foundation_testing" }
