[package]
name = "wello"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
# dev-server
ewe_logs = { workspace = true, features = ["standard"] }
ewe_devserver.workspace = true

# directory embedding
rust-embed = "8.5.0"

# -- tokio, axum and tower
tokio = { version = "1.36", default-features = true, features=["io-util", "rt"] }
http = { version = "1.1.0" }
tower = { version = "0.4.13" }
axum = { version = "0.7.5", default-features = true }

# -- serve# -- serve
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0.114" }
serde_with = { version = "3.6.1" }

# -- error crates
anyhow = { version = "1.0.80" }
thiserror = { version = "1.0.57" }

# -- tracing crates
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18" }

[features]
default = ["ewe_logs/standard"]

[lints]
workspace = true
