//! Auto-generated provider module for gcp/youtubeAnalytics.
//!
//! Generated by `cargo run --bin ewe_platform gen_api`.
//! DO NOT EDIT MANUALLY.

#![cfg(feature = "gcp_youtubeAnalytics")]
#![allow(clippy::too_many_arguments, clippy::type_complexity)]
#![allow(clippy::missing_errors_doc, clippy::doc_markdown, clippy::useless_format)]

pub mod shared;

#[cfg(feature = "gcp_youtubeAnalytics_group_items")]
pub mod group_items;
#[cfg(feature = "gcp_youtubeAnalytics_groups")]
pub mod groups;
#[cfg(feature = "gcp_youtubeAnalytics_reports")]
pub mod reports;
