//! BuildKit gRPC client — communicates with `buildkitd` over a Unix socket.
//!
//! WHY: BuildKit is Docker's next-gen build engine. Unlike the classic Docker API,
//! BuildKit uses gRPC on a Unix socket (`/run/buildkit/buildkitd.sock`). This
//! module wraps `foundation_connectrpc::Client<Req, Res>` per service method.
//!
//! WHAT: [`BuildKitClient`] holds three typed `Client`s (Solve, Status, Info)
//! keyed by the buildkit Control service. Each is constructed with
//! `ProcedureCodecs` + `H1Transport` over our `DynNetClient` Unix-socket path.
//!
//! HOW: `BuildKitClient::connect(socket_path)` builds an `H1Transport` via
//! `HttpClientBuilder::new().unix_socket(path).build()`, then constructs
//! `Client<Req, Res>::new(...)` for each RPC.
//!
//! ## Proto codegen
//!
//! The gRPC message types (`SolveRequest`, `StatusResponse`, etc.) and their
//! `buffa::Message` + `ProcedureCodecs` impls are generated by
//! `foundation_connectrpc_codegen` from the vendored proto files in
//! `specs/buildkit/`. To regenerate:
//!
//! ```bash
//! protoc \
//!   -I specs/buildkit \
//!   --connect-ewe_out=src/buildkit/generated \
//!   specs/buildkit/moby/buildkit/api/services/control/control.proto \
//!   ... (remaining protos)
//! ```
//!
//! Until codegen is run, the `[buildkit]` feature produces stub types (see
//! `types.rs`) that satisfy the trait bounds and allow the client structure
//! to compile and the transport wiring to be tested.

pub mod types;

use foundation_connectrpc::{
    Client, ClientOptions, Ctx, H1Transport, JsonCodec, ProcedureCodecs, Request, Transport,
};
use foundation_netio::{DynNetClient, HttpClientBuilder};
use std::path::Path;
use std::sync::Arc;

use crate::buildkit::types::{
    InfoRequest, InfoResponse, SolveRequest, SolveResponse, StatusRequest, StatusResponse,
};

/// BuildKit daemon client over a Unix socket.
///
/// Holds one [`Client<Req, Res>`] per gRPC method — all sharing the same
/// `H1Transport` (which wraps a `DynNetClient` dialing the buildkitd socket).
///
/// Uses `ProcedureCodecs::only(JsonCodec)` to avoid requiring `buffa::Message`
/// impls on the request/response types — these will be added when proto codegen
/// runs (switch to `.defaults()` then, which adds `ProtoCodec`).
pub struct BuildKitClient {
    /// Bidi-streaming build execution.
    pub solve: Client<SolveRequest, SolveResponse>,
    /// Server-streaming build progress.
    pub status: Client<StatusRequest, StatusResponse>,
    /// Unary server info.
    pub info: Client<InfoRequest, InfoResponse>,
}

impl BuildKitClient {
    /// Connect to `buildkitd` at the given Unix socket path.
    ///
    /// # Errors
    ///
    /// Returns an error if the socket cannot be dialed or the client cannot be
    /// constructed.
    pub fn connect(socket_path: impl AsRef<Path>) -> Result<Self, Box<dyn std::error::Error + Send + Sync>> {
        let path = socket_path.as_ref();
        let http: DynNetClient = HttpClientBuilder::new().unix_socket(path).build();

        let transport: Arc<dyn Transport> = Arc::new(H1Transport::new(http));

        let base_url = "http://localhost/moby.buildkit.v1.Control";
        let opts = || ClientOptions::new().with_grpc();
        // Use JsonCodec only — avoids requiring buffa::Message on types pending codegen.
        let codecs = ProcedureCodecs::only(JsonCodec);

        let info = Client::<InfoRequest, InfoResponse>::new(
            Arc::clone(&transport),
            &format!("{base_url}/Info"),
            codecs,
            opts(),
        )?;

        let status = Client::<StatusRequest, StatusResponse>::new(
            Arc::clone(&transport),
            &format!("{base_url}/Status"),
            ProcedureCodecs::only(JsonCodec),
            opts(),
        )?;

        let solve = Client::<SolveRequest, SolveResponse>::new(
            transport,
            &format!("{base_url}/Solve"),
            ProcedureCodecs::only(JsonCodec),
            opts(),
        )?;

        Ok(Self { solve, status, info })
    }

    /// Get buildkitd info (unary, requires no auth).
    ///
    /// # Errors
    ///
    /// Returns a [`ConnectError`] trace on transport failure or non-OK status.
    pub async fn info(&self) -> Result<InfoResponse, Box<dyn std::error::Error + Send + Sync>> {
        let ctx = Ctx::background();
        let response = self.info.unary(ctx, Request::new(InfoRequest::default())).await?;
        Ok(response.msg)
    }
}
