[package]
name = "ewe-watch-utils"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
ewe-logs.workspace = true
tracing.workspace = true
anyhow.workspace = true

# -- error crates
thiserror = { version = "1.0.57" }

# -- watcher
notify = { version = "6.1.1", features = [] }
notify-debouncer-full = { version = "0.3.1", default-features = false }

[dev-dependencies]
tracing-test = { version = "0.2.5" }

[features]
macos_kqueue = ["notify/macos_kqueue"]

[lints]
workspace = true
