[package]
name = "ewe_platform"
version = "0.0.2"
description = "ewe_platform binary CLi"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords = [
    "ewe-platform",
    "ewe-platform-cli",
    "ewe-platform-binary",
]

[dependencies]
# -- workspace dependency
ewe_temple = { workspace = true }
ewe_watch_utils = { workspace = true }
ewe_watchers = { workspace = true }
ewe_devserver = { workspace = true  }
ewe_trace = { workspace = true,  features = ["standard"]}
foundations_ext = { workspace = true }

# base crates
derive_more.workspace = true
tracing = { workspace = true }

# asset embedding
rust-embed = { version = "8.5", features = ["interpolate-folder-path"]}

# cli
clap = { version = "4.5.20", features = ["derive"] }
signal-hook = { version = "0.3.17" }

# -- tokio, axum and tower
crossbeam = { version = "0.8" }
axum = { version = "0.7.5" }
tokio = { version = "1.36", features = ["full"], default-features = true }

# -- http and hyper
bytes = { version = "1.6.1" }
http = { version = "1.1" }
http-body = { version = "1.0" }
hyper = { version = "1.4.1", features = ["full"]}
hyper-util = { version = "0.1.7"}
http-body-util = { version = "0.1.2" }

# -- serve# -- serve
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0.114" }
serde_with = { version = "3.6.1" }

# -- error crates
anyhow = { version = "1.0.80" }
thiserror = { version = "1.0.57" }

# -- tracing crates
tracing-subscriber = { version = "0.3.18", features = ["fmt"]}

[features]
debug_trace = ["ewe_trace/debug_trace"]

[lints]
workspace = true
