[package]
name = "static-html-app"
version = "0.0.1"
edition = "2021"
rust-version = "1.75"
license = "Apache-2.0"
authors = ["EweStudios Consulting Limited"]
repository = "{{GITHUB_NAMESPACE}}/{{PROJECT_NAME}}"
keywords = ["static-html-app", "static html app"]

[dependencies]
# dev-server
ewe_devserver = { version = "0.0.1" }
ewe_trace = { version = "0.0.1", features = ["standard"] }

# directory embedding
rust-embed = "8.5.0"

# -- tokio, axum and tower
tokio = { version = "1.36", default-features = true, features=["io-util", "rt"] }
http = { version = "1.1.0" }
tower = { version = "0.4.13" }
axum = { version = "0.7.5", default-features = true }

# -- serve# -- serve
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0.114" }
serde_with = { version = "3.6.1" }

# -- error crates
anyhow = { version = "1.0.80" }
thiserror = { version = "1.0.57" }

# -- tracing crates
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18" }

[features]
default = ["ewe_trace/standard"]

[lints]
workspace = true
