[package]
name = "ewe-routing"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
ewe-logs.workspace = true
ewe-mem.workspace = true

http = { version = "1.1.0" }
tower = { version = "0.4.13" }
regex = { version = "1.10" }
lazy-regex = { version = "3.1" }
lazy_static = { version = "1.4.0" }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0.114" }
serde_with = { version = "3.6.1" }
tracing = { version = "0.1.40" }
tokio = { version = "1.36", features = ["rt", "macros"] }
anyhow = { version = "1.0.80" }
thiserror = { version = "1.0.57" }

[dev-dependencies]
tokio = { version = "1.36", features = ["full"] }
criterion = { version = "0.5", features = ["html_reports"] }
tokio-test = { version = "0.4" }
tracing-test = { version = "0.2.5" }

[lints]
workspace = true

[features]
debug_trace = ["ewe-logs/debug_trace"]
