[package]
name = "routing"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
http = "1.1.0"
regex = { version = "1.10" }
lazy-regex = { version = "3.1" }

# workspace dependencies
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
anyhow.workspace = true
thiserror.workspace = true
ewe-logs.workspace = true
ewe-mem.workspace = true

[lints]
workspace = true
