[package]
name = "foundation_shell"
version = "0.0.1"
description = "A nushell integrated library for integrating nushell as a library in any project"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords = ["foundation_shell", "foundation_nushell"]

[dependencies]
foundation_core = { workspace = true }
foundation_errstacks = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }

regex = { version = "1.12" }
bytes = { version = "1.5" }
sha1 = "0.10"
base64 = "0.22"
tracing = "0.1"
uuid = { version = "1.6", features = ["v4"] }

[dev-dependencies]
foundation_testing = { workspace=true }
tracing-test = { version = "0.2",  features = ["no-env-filter"] }
serial_test = { version = "3" }

[lints]
workspace = true
