//! Auto-generated API module for gcp/saasservicemgmt rolloutKinds.
//!
//! Generated by `cargo run --bin ewe_platform gen_api`.
//! DO NOT EDIT MANUALLY.
//!
//! Feature flag: `gcp_saasservicemgmt_rollout_kinds `

#![cfg(feature = "gcp_saasservicemgmt_rollout_kinds")]
#![allow(clippy::too_many_arguments, clippy::type_complexity)]
#![allow(
    clippy::missing_errors_doc,
    clippy::doc_markdown,
    clippy::useless_format
)]
#![allow(unused_imports)]

use foundation_core::valtron::{TaskIterator, TaskIteratorExt};
use foundation_core::wire::simple_http::client::{ClientRequestBuilder, SimpleHttpClient};
use foundation_macros::JsonHash;
use serde::{Deserialize, Serialize};

// Import shared types used by this module
use super::shared::Empty;

use super::shared::ApiResponse;

// =============================================================================
// TYPE DECLARATIONS
// =============================================================================

/// `ErrorBudget` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct ErrorBudget {
    /// allowedCount property.
    pub allowed_count: Option<i64>,
    /// allowedPercentage property.
    pub allowed_percentage: Option<i64>,
}

/// `ListRolloutKindsResponse` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct ListRolloutKindsResponse {
    /// nextPageToken property.
    pub next_page_token: Option<String>,
    /// rolloutKinds property.
    pub rollout_kinds: Option<Vec<RolloutKind>>,
    /// unreachable property.
    pub unreachable: Option<Vec<String>>,
}

/// `RolloutKind` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct RolloutKind {
    /// annotations property.
    pub annotations: Option<serde_json::Value>,
    /// createTime property.
    pub create_time: Option<String>,
    /// errorBudget property.
    pub error_budget: Option<ErrorBudget>,
    /// etag property.
    pub etag: Option<String>,
    /// labels property.
    pub labels: Option<serde_json::Value>,
    /// name property.
    pub name: Option<String>,
    /// rolloutOrchestrationStrategy property.
    pub rollout_orchestration_strategy: Option<String>,
    /// uid property.
    pub uid: Option<String>,
    /// unitFilter property.
    pub unit_filter: Option<String>,
    /// unitKind property.
    pub unit_kind: Option<String>,
    /// updateTime property.
    pub update_time: Option<String>,
    /// updateUnitKindStrategy property.
    pub update_unit_kind_strategy: Option<String>,
}

// =============================================================================
// ARGS TYPES (per-endpoint)
// =============================================================================

/// Arguments for [`saasservicemgmt.projects.locations.rolloutKinds.create_builder`].
#[derive(Debug, Clone, Serialize, JsonHash)]
pub struct SaasservicemgmtProjectsLocationsRolloutKindsCreateArgs {
    /// Path parameter: `parent`.
    pub parent: String,
    /// Query parameter: `requestId`.
    pub request_id: Option<String>,
    /// Query parameter: `rolloutKindId`.
    pub rollout_kind_id: Option<String>,
    /// Query parameter: `validateOnly`.
    pub validate_only: Option<String>,
}

/// Arguments for [`saasservicemgmt.projects.locations.rolloutKinds.delete_builder`].
#[derive(Debug, Clone, Serialize, JsonHash)]
pub struct SaasservicemgmtProjectsLocationsRolloutKindsDeleteArgs {
    /// Path parameter: `name`.
    pub name: String,
    /// Query parameter: `etag`.
    pub etag: Option<String>,
    /// Query parameter: `requestId`.
    pub request_id: Option<String>,
    /// Query parameter: `validateOnly`.
    pub validate_only: Option<String>,
}

/// Arguments for [`saasservicemgmt.projects.locations.rolloutKinds.get_builder`].
#[derive(Debug, Clone, Serialize, JsonHash)]
pub struct SaasservicemgmtProjectsLocationsRolloutKindsGetArgs {
    /// Path parameter: `name`.
    pub name: String,
}

/// Arguments for [`saasservicemgmt.projects.locations.rolloutKinds.list_builder`].
#[derive(Debug, Clone, Serialize, JsonHash)]
pub struct SaasservicemgmtProjectsLocationsRolloutKindsListArgs {
    /// Path parameter: `parent`.
    pub parent: String,
    /// Query parameter: `filter`.
    pub filter: Option<String>,
    /// Query parameter: `orderBy`.
    pub order_by: Option<String>,
    /// Query parameter: `pageSize`.
    pub page_size: Option<String>,
    /// Query parameter: `pageToken`.
    pub page_token: Option<String>,
}

/// Arguments for [`saasservicemgmt.projects.locations.rolloutKinds.patch_builder`].
#[derive(Debug, Clone, Serialize, JsonHash)]
pub struct SaasservicemgmtProjectsLocationsRolloutKindsPatchArgs {
    /// Path parameter: `name`.
    pub name: String,
    /// Query parameter: `requestId`.
    pub request_id: Option<String>,
    /// Query parameter: `updateMask`.
    pub update_mask: Option<String>,
    /// Query parameter: `validateOnly`.
    pub validate_only: Option<String>,
}

// =============================================================================
// CLIENT FUNCTIONS (per-endpoint)
// =============================================================================

// -----------------------------------------------------------------------------
// POST v1/projects/{projectsId}/locations/{locationsId}/rolloutKinds
// -----------------------------------------------------------------------------

/// POST v1/projects/{projectsId}/locations/{locationsId}/rolloutKinds.
///
/// Takes client and args, builds the request, optionally applies modifications,
/// and returns a `TaskIterator` for execution.
///
/// # Arguments
///
/// * `client` - HTTP client for making the request
/// * `builder_mod` - Optional closure to modify the request builder (e.g., add headers)
///
/// # Example
///
/// ```ignore
/// let task = saasservicemgmt_projects_locations_rollout_kinds_create_request(&client, &args, Some(|b| {
///     b.header("X-Custom-Header", "value")
/// }))?;
/// ```
#[inline]
pub fn saasservicemgmt_projects_locations_rollout_kinds_create_request<R, F>(
    client: &SimpleHttpClient<R>,
    builder_mod: Option<F>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<RolloutKind>, super::shared::ApiError>,
            Pending = super::shared::ApiPending,
            Spawner = super::shared::BoxedSendExecutionAction,
        > + Send
        + 'static,
    super::shared::ApiError,
>
where
    R: foundation_core::wire::simple_http::client::DnsResolver + Clone + Default + 'static,
    F: FnOnce(&mut ClientRequestBuilder<R>),
{
    let endpoint_url = format!(
        "https://saasservicemgmt.googleapis.com/v1/projects/{{projectsId}}/locations/{{locationsId}}/rolloutKinds",
    );

    let mut builder = client
        .post(&endpoint_url)
        .map_err(|e| super::shared::ApiError::RequestBuildFailed(e.to_string()))?;

    if let Some(f) = builder_mod {
        f(&mut builder);
    }

    Ok(builder
        .build_send_request()
        .map_err(|e: foundation_core::wire::simple_http::HttpClientError| {
            super::shared::ApiError::RequestBuildFailed(e.to_string())
        })?
        .map_ready(|intro| match intro {
            super::shared::RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status: usize = intro.0.into();
                if status < 200 || status >= 300 {
                    return Err(super::shared::ApiError::HttpStatus {
                        code: status as u16,
                        headers: headers.clone(),
                        body: None,
                    });
                }
                let body =
                    foundation_core::wire::simple_http::client::body_reader::collect_string(stream);
                let parsed: RolloutKind =
                    serde_json::from_str(&body).map_err(|e: serde_json::Error| {
                        super::shared::ApiError::ParseFailed(e.to_string())
                    })?;
                Ok(ApiResponse {
                    status: status as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            super::shared::RequestIntro::Failed(e) => {
                Err(super::shared::ApiError::RequestSendFailed(e.to_string()))
            }
        })
        .map_pending(|_| super::shared::ApiPending::Sending))
}

// -----------------------------------------------------------------------------
// DELETE v1/projects/{projectsId}/locations/{locationsId}/rolloutKinds/{rolloutKindsId}
// -----------------------------------------------------------------------------

/// DELETE v1/projects/{projectsId}/locations/{locationsId}/rolloutKinds/{rolloutKindsId}.
///
/// Takes client and args, builds the request, optionally applies modifications,
/// and returns a `TaskIterator` for execution.
///
/// # Arguments
///
/// * `client` - HTTP client for making the request
/// * `builder_mod` - Optional closure to modify the request builder (e.g., add headers)
///
/// # Example
///
/// ```ignore
/// let task = saasservicemgmt_projects_locations_rollout_kinds_delete_request(&client, &args, Some(|b| {
///     b.header("X-Custom-Header", "value")
/// }))?;
/// ```
#[inline]
pub fn saasservicemgmt_projects_locations_rollout_kinds_delete_request<R, F>(
    client: &SimpleHttpClient<R>,
    builder_mod: Option<F>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<Empty>, super::shared::ApiError>,
            Pending = super::shared::ApiPending,
            Spawner = super::shared::BoxedSendExecutionAction,
        > + Send
        + 'static,
    super::shared::ApiError,
>
where
    R: foundation_core::wire::simple_http::client::DnsResolver + Clone + Default + 'static,
    F: FnOnce(&mut ClientRequestBuilder<R>),
{
    let endpoint_url = format!(
        "https://saasservicemgmt.googleapis.com/v1/projects/{{projectsId}}/locations/{{locationsId}}/rolloutKinds/{{rolloutKindsId}}",
    );

    let mut builder = client
        .delete(&endpoint_url)
        .map_err(|e| super::shared::ApiError::RequestBuildFailed(e.to_string()))?;

    if let Some(f) = builder_mod {
        f(&mut builder);
    }

    Ok(builder
        .build_send_request()
        .map_err(|e: foundation_core::wire::simple_http::HttpClientError| {
            super::shared::ApiError::RequestBuildFailed(e.to_string())
        })?
        .map_ready(|intro| match intro {
            super::shared::RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status: usize = intro.0.into();
                if status < 200 || status >= 300 {
                    return Err(super::shared::ApiError::HttpStatus {
                        code: status as u16,
                        headers: headers.clone(),
                        body: None,
                    });
                }
                let body =
                    foundation_core::wire::simple_http::client::body_reader::collect_string(stream);
                let parsed: Empty =
                    serde_json::from_str(&body).map_err(|e: serde_json::Error| {
                        super::shared::ApiError::ParseFailed(e.to_string())
                    })?;
                Ok(ApiResponse {
                    status: status as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            super::shared::RequestIntro::Failed(e) => {
                Err(super::shared::ApiError::RequestSendFailed(e.to_string()))
            }
        })
        .map_pending(|_| super::shared::ApiPending::Sending))
}

// -----------------------------------------------------------------------------
// GET v1/projects/{projectsId}/locations/{locationsId}/rolloutKinds/{rolloutKindsId}
// -----------------------------------------------------------------------------

/// GET v1/projects/{projectsId}/locations/{locationsId}/rolloutKinds/{rolloutKindsId}.
///
/// Takes client and args, builds the request, optionally applies modifications,
/// and returns a `TaskIterator` for execution.
///
/// # Arguments
///
/// * `client` - HTTP client for making the request
/// * `builder_mod` - Optional closure to modify the request builder (e.g., add headers)
///
/// # Example
///
/// ```ignore
/// let task = saasservicemgmt_projects_locations_rollout_kinds_get_request(&client, &args, Some(|b| {
///     b.header("X-Custom-Header", "value")
/// }))?;
/// ```
#[inline]
pub fn saasservicemgmt_projects_locations_rollout_kinds_get_request<R, F>(
    client: &SimpleHttpClient<R>,
    builder_mod: Option<F>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<RolloutKind>, super::shared::ApiError>,
            Pending = super::shared::ApiPending,
            Spawner = super::shared::BoxedSendExecutionAction,
        > + Send
        + 'static,
    super::shared::ApiError,
>
where
    R: foundation_core::wire::simple_http::client::DnsResolver + Clone + Default + 'static,
    F: FnOnce(&mut ClientRequestBuilder<R>),
{
    let endpoint_url = format!(
        "https://saasservicemgmt.googleapis.com/v1/projects/{{projectsId}}/locations/{{locationsId}}/rolloutKinds/{{rolloutKindsId}}",
    );

    let mut builder = client
        .get(&endpoint_url)
        .map_err(|e| super::shared::ApiError::RequestBuildFailed(e.to_string()))?;

    if let Some(f) = builder_mod {
        f(&mut builder);
    }

    Ok(builder
        .build_send_request()
        .map_err(|e: foundation_core::wire::simple_http::HttpClientError| {
            super::shared::ApiError::RequestBuildFailed(e.to_string())
        })?
        .map_ready(|intro| match intro {
            super::shared::RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status: usize = intro.0.into();
                if status < 200 || status >= 300 {
                    return Err(super::shared::ApiError::HttpStatus {
                        code: status as u16,
                        headers: headers.clone(),
                        body: None,
                    });
                }
                let body =
                    foundation_core::wire::simple_http::client::body_reader::collect_string(stream);
                let parsed: RolloutKind =
                    serde_json::from_str(&body).map_err(|e: serde_json::Error| {
                        super::shared::ApiError::ParseFailed(e.to_string())
                    })?;
                Ok(ApiResponse {
                    status: status as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            super::shared::RequestIntro::Failed(e) => {
                Err(super::shared::ApiError::RequestSendFailed(e.to_string()))
            }
        })
        .map_pending(|_| super::shared::ApiPending::Sending))
}

// -----------------------------------------------------------------------------
// GET v1/projects/{projectsId}/locations/{locationsId}/rolloutKinds
// -----------------------------------------------------------------------------

/// GET v1/projects/{projectsId}/locations/{locationsId}/rolloutKinds.
///
/// Takes client and args, builds the request, optionally applies modifications,
/// and returns a `TaskIterator` for execution.
///
/// # Arguments
///
/// * `client` - HTTP client for making the request
/// * `builder_mod` - Optional closure to modify the request builder (e.g., add headers)
///
/// # Example
///
/// ```ignore
/// let task = saasservicemgmt_projects_locations_rollout_kinds_list_request(&client, &args, Some(|b| {
///     b.header("X-Custom-Header", "value")
/// }))?;
/// ```
#[inline]
pub fn saasservicemgmt_projects_locations_rollout_kinds_list_request<R, F>(
    client: &SimpleHttpClient<R>,
    builder_mod: Option<F>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<ListRolloutKindsResponse>, super::shared::ApiError>,
            Pending = super::shared::ApiPending,
            Spawner = super::shared::BoxedSendExecutionAction,
        > + Send
        + 'static,
    super::shared::ApiError,
>
where
    R: foundation_core::wire::simple_http::client::DnsResolver + Clone + Default + 'static,
    F: FnOnce(&mut ClientRequestBuilder<R>),
{
    let endpoint_url = format!(
        "https://saasservicemgmt.googleapis.com/v1/projects/{{projectsId}}/locations/{{locationsId}}/rolloutKinds",
    );

    let mut builder = client
        .get(&endpoint_url)
        .map_err(|e| super::shared::ApiError::RequestBuildFailed(e.to_string()))?;

    if let Some(f) = builder_mod {
        f(&mut builder);
    }

    Ok(builder
        .build_send_request()
        .map_err(|e: foundation_core::wire::simple_http::HttpClientError| {
            super::shared::ApiError::RequestBuildFailed(e.to_string())
        })?
        .map_ready(|intro| match intro {
            super::shared::RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status: usize = intro.0.into();
                if status < 200 || status >= 300 {
                    return Err(super::shared::ApiError::HttpStatus {
                        code: status as u16,
                        headers: headers.clone(),
                        body: None,
                    });
                }
                let body =
                    foundation_core::wire::simple_http::client::body_reader::collect_string(stream);
                let parsed: ListRolloutKindsResponse =
                    serde_json::from_str(&body).map_err(|e: serde_json::Error| {
                        super::shared::ApiError::ParseFailed(e.to_string())
                    })?;
                Ok(ApiResponse {
                    status: status as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            super::shared::RequestIntro::Failed(e) => {
                Err(super::shared::ApiError::RequestSendFailed(e.to_string()))
            }
        })
        .map_pending(|_| super::shared::ApiPending::Sending))
}

// -----------------------------------------------------------------------------
// PATCH v1/projects/{projectsId}/locations/{locationsId}/rolloutKinds/{rolloutKindsId}
// -----------------------------------------------------------------------------

/// PATCH v1/projects/{projectsId}/locations/{locationsId}/rolloutKinds/{rolloutKindsId}.
///
/// Takes client and args, builds the request, optionally applies modifications,
/// and returns a `TaskIterator` for execution.
///
/// # Arguments
///
/// * `client` - HTTP client for making the request
/// * `builder_mod` - Optional closure to modify the request builder (e.g., add headers)
///
/// # Example
///
/// ```ignore
/// let task = saasservicemgmt_projects_locations_rollout_kinds_patch_request(&client, &args, Some(|b| {
///     b.header("X-Custom-Header", "value")
/// }))?;
/// ```
#[inline]
pub fn saasservicemgmt_projects_locations_rollout_kinds_patch_request<R, F>(
    client: &SimpleHttpClient<R>,
    builder_mod: Option<F>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<RolloutKind>, super::shared::ApiError>,
            Pending = super::shared::ApiPending,
            Spawner = super::shared::BoxedSendExecutionAction,
        > + Send
        + 'static,
    super::shared::ApiError,
>
where
    R: foundation_core::wire::simple_http::client::DnsResolver + Clone + Default + 'static,
    F: FnOnce(&mut ClientRequestBuilder<R>),
{
    let endpoint_url = format!(
        "https://saasservicemgmt.googleapis.com/v1/projects/{{projectsId}}/locations/{{locationsId}}/rolloutKinds/{{rolloutKindsId}}",
    );

    let mut builder = client
        .patch(&endpoint_url)
        .map_err(|e| super::shared::ApiError::RequestBuildFailed(e.to_string()))?;

    if let Some(f) = builder_mod {
        f(&mut builder);
    }

    Ok(builder
        .build_send_request()
        .map_err(|e: foundation_core::wire::simple_http::HttpClientError| {
            super::shared::ApiError::RequestBuildFailed(e.to_string())
        })?
        .map_ready(|intro| match intro {
            super::shared::RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status: usize = intro.0.into();
                if status < 200 || status >= 300 {
                    return Err(super::shared::ApiError::HttpStatus {
                        code: status as u16,
                        headers: headers.clone(),
                        body: None,
                    });
                }
                let body =
                    foundation_core::wire::simple_http::client::body_reader::collect_string(stream);
                let parsed: RolloutKind =
                    serde_json::from_str(&body).map_err(|e: serde_json::Error| {
                        super::shared::ApiError::ParseFailed(e.to_string())
                    })?;
                Ok(ApiResponse {
                    status: status as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            super::shared::RequestIntro::Failed(e) => {
                Err(super::shared::ApiError::RequestSendFailed(e.to_string()))
            }
        })
        .map_pending(|_| super::shared::ApiPending::Sending))
}
