//! Auto-generated API module for gcp/digitalassetlinks digitalassetlinks.
//!
//! Generated by `cargo run --bin ewe_platform gen_api`.
//! DO NOT EDIT MANUALLY.
//!
//! Feature flag: `gcp_digitalassetlinks_digitalassetlinks `

#![cfg(feature = "gcp_digitalassetlinks_digitalassetlinks")]
#![allow(clippy::too_many_arguments, clippy::type_complexity)]
#![allow(
    clippy::missing_errors_doc,
    clippy::doc_markdown,
    clippy::useless_format
)]
#![allow(unused_imports)]

use foundation_core::valtron::{TaskIterator, TaskIteratorExt};
use foundation_core::wire::simple_http::client::{ClientRequestBuilder, SimpleHttpClient};
use foundation_macros::JsonHash;
use serde::{Deserialize, Serialize};

use super::shared::ApiResponse;

// =============================================================================
// TYPE DECLARATIONS
// =============================================================================

/// `CheckResponse` type.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonHash)]
pub struct CheckResponse {
    /// debugString property.
    pub debug_string: Option<String>,
    /// errorCode property.
    pub error_code: Option<Vec<String>>,
    /// linked property.
    pub linked: Option<bool>,
    /// maxAge property.
    pub max_age: Option<String>,
    /// relationExtensions property.
    pub relation_extensions: Option<Vec<serde_json::Value>>,
}

/// `Statement` type.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonHash)]
pub struct Statement {
    /// relation property.
    pub relation: Option<String>,
    /// relationExtensions property.
    pub relation_extensions: Option<serde_json::Value>,
    /// source property.
    pub source: Option<Asset>,
    /// target property.
    pub target: Option<Asset>,
}

/// `WebAsset` type.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonHash)]
pub struct WebAsset {
    /// site property.
    pub site: Option<String>,
}

/// `Asset` type.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonHash)]
pub struct Asset {
    /// androidApp property.
    pub android_app: Option<AndroidAppAsset>,
    /// web property.
    pub web: Option<WebAsset>,
}

/// `AndroidAppAsset` type.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonHash)]
pub struct AndroidAppAsset {
    /// certificate property.
    pub certificate: Option<CertificateInfo>,
    /// packageName property.
    pub package_name: Option<String>,
}

/// `ListResponse` type.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonHash)]
pub struct ListResponse {
    /// debugString property.
    pub debug_string: Option<String>,
    /// errorCode property.
    pub error_code: Option<Vec<String>>,
    /// maxAge property.
    pub max_age: Option<String>,
    /// statements property.
    pub statements: Option<Vec<Statement>>,
}

/// `CertificateInfo` type.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonHash)]
pub struct CertificateInfo {
    /// sha256Fingerprint property.
    pub sha256_fingerprint: Option<String>,
}

/// `BulkCheckRequest` type.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonHash)]
pub struct BulkCheckRequest {
    /// defaultRelation property.
    pub default_relation: Option<String>,
    /// defaultSource property.
    pub default_source: Option<Asset>,
    /// defaultTarget property.
    pub default_target: Option<Asset>,
    /// returnRelationExtensions property.
    pub return_relation_extensions: Option<bool>,
    /// statements property.
    pub statements: Option<Vec<StatementTemplate>>,
}

/// `BulkCheckResponse` type.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonHash)]
pub struct BulkCheckResponse {
    /// bulkErrorCode property.
    pub bulk_error_code: Option<String>,
    /// checkResults property.
    pub check_results: Option<Vec<CheckResponse>>,
}

/// `StatementTemplate` type.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonHash)]
pub struct StatementTemplate {
    /// relation property.
    pub relation: Option<String>,
    /// source property.
    pub source: Option<Asset>,
    /// target property.
    pub target: Option<Asset>,
}

// =============================================================================
// ARGS TYPES (per-endpoint)
// =============================================================================

/// Arguments for [`digitalassetlinks.assetlinks.bulkCheck_builder`].
#[derive(Debug, Clone, Default, Serialize, JsonHash)]
pub struct DigitalassetlinksAssetlinksBulkCheckArgs {
    /// Request body.
    pub body: BulkCheckRequest,
}

/// Arguments for [`digitalassetlinks.assetlinks.check_builder`].
#[derive(Debug, Clone, Default, Serialize, JsonHash)]
pub struct DigitalassetlinksAssetlinksCheckArgs {
    /// Query parameter: `relation`.
    pub relation: Option<String>,
    /// Query parameter: `returnRelationExtensions`.
    pub return_relation_extensions: Option<String>,
    /// Query parameter: `source.androidApp.certificate.sha256Fingerprint`.
    pub source_android_app_certificate_sha256_fingerprint: Option<String>,
    /// Query parameter: `source.androidApp.packageName`.
    pub source_android_app_package_name: Option<String>,
    /// Query parameter: `source.web.site`.
    pub source_web_site: Option<String>,
    /// Query parameter: `target.androidApp.certificate.sha256Fingerprint`.
    pub target_android_app_certificate_sha256_fingerprint: Option<String>,
    /// Query parameter: `target.androidApp.packageName`.
    pub target_android_app_package_name: Option<String>,
    /// Query parameter: `target.web.site`.
    pub target_web_site: Option<String>,
}

/// Arguments for [`digitalassetlinks.statements.list_builder`].
#[derive(Debug, Clone, Default, Serialize, JsonHash)]
pub struct DigitalassetlinksStatementsListArgs {
    /// Query parameter: `relation`.
    pub relation: Option<String>,
    /// Query parameter: `returnRelationExtensions`.
    pub return_relation_extensions: Option<String>,
    /// Query parameter: `source.androidApp.certificate.sha256Fingerprint`.
    pub source_android_app_certificate_sha256_fingerprint: Option<String>,
    /// Query parameter: `source.androidApp.packageName`.
    pub source_android_app_package_name: Option<String>,
    /// Query parameter: `source.web.site`.
    pub source_web_site: Option<String>,
}

// =============================================================================
// CLIENT FUNCTIONS (per-endpoint)
// =============================================================================

// -----------------------------------------------------------------------------
// POST v1/assetlinks:bulkCheck
// -----------------------------------------------------------------------------

/// POST v1/assetlinks:bulkCheck.
///
/// Takes client and args, builds the request, optionally applies modifications,
/// and returns a `TaskIterator` for execution.
///
/// # Arguments
///
/// * `client` - HTTP client for making the request
/// * `args` - Request arguments (path params, query params, body)
/// * `builder_mod` - Optional closure to modify the request builder (e.g., add headers)
///
/// # Example
///
/// ```ignore
/// let task = digitalassetlinks_assetlinks_bulk_check_request(&client, &args, Some(|b| {
///     b.header("X-Custom-Header", "value")
/// }))?;
/// ```
#[inline]
pub fn digitalassetlinks_assetlinks_bulk_check_request<R, F>(
    client: &SimpleHttpClient<R>,
    args: &DigitalassetlinksAssetlinksBulkCheckArgs,
    builder_mod: Option<F>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<BulkCheckResponse>, super::shared::ApiError>,
            Pending = super::shared::ApiPending,
            Spawner = super::shared::BoxedSendExecutionAction,
        > + Send
        + 'static,
    super::shared::ApiError,
>
where
    R: foundation_core::wire::simple_http::client::DnsResolver + Clone + Default + 'static,
    F: FnOnce(&mut ClientRequestBuilder<R>),
{
    let endpoint_url = format!("https://digitalassetlinks.googleapis.com/v1/assetlinks:bulkCheck",);

    let mut builder = client
        .post(&endpoint_url)
        .map_err(|e| super::shared::ApiError::RequestBuildFailed(e.to_string()))?;

    builder = builder
        .body_json(&args.body)
        .map_err(|e| super::shared::ApiError::RequestBuildFailed(e.to_string()))?;

    if let Some(f) = builder_mod {
        f(&mut builder);
    }

    Ok(builder
        .build_send_request()
        .map_err(|e: foundation_core::wire::simple_http::HttpClientError| {
            super::shared::ApiError::RequestBuildFailed(e.to_string())
        })?
        .map_ready(|intro| match intro {
            super::shared::RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status: usize = intro.0.into();
                if status < 200 || status >= 300 {
                    return Err(super::shared::ApiError::HttpStatus {
                        code: status as u16,
                        headers: headers.clone(),
                        body: None,
                    });
                }
                let body =
                    foundation_core::wire::simple_http::client::body_reader::collect_string(stream);
                let parsed: BulkCheckResponse =
                    serde_json::from_str(&body).map_err(|e: serde_json::Error| {
                        super::shared::ApiError::ParseFailed(e.to_string())
                    })?;
                Ok(ApiResponse {
                    status: status as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            super::shared::RequestIntro::Failed(e) => {
                Err(super::shared::ApiError::RequestSendFailed(e.to_string()))
            }
        })
        .map_pending(|_| super::shared::ApiPending::Sending))
}

// -----------------------------------------------------------------------------
// GET v1/assetlinks:check
// -----------------------------------------------------------------------------

/// GET v1/assetlinks:check.
///
/// Takes client and args, builds the request, optionally applies modifications,
/// and returns a `TaskIterator` for execution.
///
/// # Arguments
///
/// * `client` - HTTP client for making the request
/// * `args` - Request arguments (path params, query params, body)
/// * `builder_mod` - Optional closure to modify the request builder (e.g., add headers)
///
/// # Example
///
/// ```ignore
/// let task = digitalassetlinks_assetlinks_check_request(&client, &args, Some(|b| {
///     b.header("X-Custom-Header", "value")
/// }))?;
/// ```
#[inline]
pub fn digitalassetlinks_assetlinks_check_request<R, F>(
    client: &SimpleHttpClient<R>,
    args: &DigitalassetlinksAssetlinksCheckArgs,
    builder_mod: Option<F>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<CheckResponse>, super::shared::ApiError>,
            Pending = super::shared::ApiPending,
            Spawner = super::shared::BoxedSendExecutionAction,
        > + Send
        + 'static,
    super::shared::ApiError,
>
where
    R: foundation_core::wire::simple_http::client::DnsResolver + Clone + Default + 'static,
    F: FnOnce(&mut ClientRequestBuilder<R>),
{
    let endpoint_url = format!("https://digitalassetlinks.googleapis.com/v1/assetlinks:check",);

    let endpoint_url = {
        let mut url = endpoint_url;
        let mut first = true;
        if let Some(ref v) = args.relation {
            if first {
                url.push('?');
                first = false;
            } else {
                url.push('&');
            }
            url.push_str("relation=");
            url.push_str(&urlencoding::encode(v));
        }
        if let Some(ref v) = args.return_relation_extensions {
            if first {
                url.push('?');
                first = false;
            } else {
                url.push('&');
            }
            url.push_str("returnRelationExtensions=");
            url.push_str(&urlencoding::encode(v));
        }
        if let Some(ref v) = args.source_android_app_certificate_sha256_fingerprint {
            if first {
                url.push('?');
                first = false;
            } else {
                url.push('&');
            }
            url.push_str("source_androidApp_certificate_sha256Fingerprint=");
            url.push_str(&urlencoding::encode(v));
        }
        if let Some(ref v) = args.source_android_app_package_name {
            if first {
                url.push('?');
                first = false;
            } else {
                url.push('&');
            }
            url.push_str("source_androidApp_packageName=");
            url.push_str(&urlencoding::encode(v));
        }
        if let Some(ref v) = args.source_web_site {
            if first {
                url.push('?');
                first = false;
            } else {
                url.push('&');
            }
            url.push_str("source_web_site=");
            url.push_str(&urlencoding::encode(v));
        }
        if let Some(ref v) = args.target_android_app_certificate_sha256_fingerprint {
            if first {
                url.push('?');
                first = false;
            } else {
                url.push('&');
            }
            url.push_str("target_androidApp_certificate_sha256Fingerprint=");
            url.push_str(&urlencoding::encode(v));
        }
        if let Some(ref v) = args.target_android_app_package_name {
            if first {
                url.push('?');
                first = false;
            } else {
                url.push('&');
            }
            url.push_str("target_androidApp_packageName=");
            url.push_str(&urlencoding::encode(v));
        }
        if let Some(ref v) = args.target_web_site {
            if first {
                url.push('?');
                first = false;
            } else {
                url.push('&');
            }
            url.push_str("target_web_site=");
            url.push_str(&urlencoding::encode(v));
        }
        url
    };

    let mut builder = client
        .get(&endpoint_url)
        .map_err(|e| super::shared::ApiError::RequestBuildFailed(e.to_string()))?;

    if let Some(f) = builder_mod {
        f(&mut builder);
    }

    Ok(builder
        .build_send_request()
        .map_err(|e: foundation_core::wire::simple_http::HttpClientError| {
            super::shared::ApiError::RequestBuildFailed(e.to_string())
        })?
        .map_ready(|intro| match intro {
            super::shared::RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status: usize = intro.0.into();
                if status < 200 || status >= 300 {
                    return Err(super::shared::ApiError::HttpStatus {
                        code: status as u16,
                        headers: headers.clone(),
                        body: None,
                    });
                }
                let body =
                    foundation_core::wire::simple_http::client::body_reader::collect_string(stream);
                let parsed: CheckResponse =
                    serde_json::from_str(&body).map_err(|e: serde_json::Error| {
                        super::shared::ApiError::ParseFailed(e.to_string())
                    })?;
                Ok(ApiResponse {
                    status: status as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            super::shared::RequestIntro::Failed(e) => {
                Err(super::shared::ApiError::RequestSendFailed(e.to_string()))
            }
        })
        .map_pending(|_| super::shared::ApiPending::Sending))
}

// -----------------------------------------------------------------------------
// GET v1/statements:list
// -----------------------------------------------------------------------------

/// GET v1/statements:list.
///
/// Takes client and args, builds the request, optionally applies modifications,
/// and returns a `TaskIterator` for execution.
///
/// # Arguments
///
/// * `client` - HTTP client for making the request
/// * `args` - Request arguments (path params, query params, body)
/// * `builder_mod` - Optional closure to modify the request builder (e.g., add headers)
///
/// # Example
///
/// ```ignore
/// let task = digitalassetlinks_statements_list_request(&client, &args, Some(|b| {
///     b.header("X-Custom-Header", "value")
/// }))?;
/// ```
#[inline]
pub fn digitalassetlinks_statements_list_request<R, F>(
    client: &SimpleHttpClient<R>,
    args: &DigitalassetlinksStatementsListArgs,
    builder_mod: Option<F>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<ListResponse>, super::shared::ApiError>,
            Pending = super::shared::ApiPending,
            Spawner = super::shared::BoxedSendExecutionAction,
        > + Send
        + 'static,
    super::shared::ApiError,
>
where
    R: foundation_core::wire::simple_http::client::DnsResolver + Clone + Default + 'static,
    F: FnOnce(&mut ClientRequestBuilder<R>),
{
    let endpoint_url = format!("https://digitalassetlinks.googleapis.com/v1/statements:list",);

    let endpoint_url = {
        let mut url = endpoint_url;
        let mut first = true;
        if let Some(ref v) = args.relation {
            if first {
                url.push('?');
                first = false;
            } else {
                url.push('&');
            }
            url.push_str("relation=");
            url.push_str(&urlencoding::encode(v));
        }
        if let Some(ref v) = args.return_relation_extensions {
            if first {
                url.push('?');
                first = false;
            } else {
                url.push('&');
            }
            url.push_str("returnRelationExtensions=");
            url.push_str(&urlencoding::encode(v));
        }
        if let Some(ref v) = args.source_android_app_certificate_sha256_fingerprint {
            if first {
                url.push('?');
                first = false;
            } else {
                url.push('&');
            }
            url.push_str("source_androidApp_certificate_sha256Fingerprint=");
            url.push_str(&urlencoding::encode(v));
        }
        if let Some(ref v) = args.source_android_app_package_name {
            if first {
                url.push('?');
                first = false;
            } else {
                url.push('&');
            }
            url.push_str("source_androidApp_packageName=");
            url.push_str(&urlencoding::encode(v));
        }
        if let Some(ref v) = args.source_web_site {
            if first {
                url.push('?');
                first = false;
            } else {
                url.push('&');
            }
            url.push_str("source_web_site=");
            url.push_str(&urlencoding::encode(v));
        }
        url
    };

    let mut builder = client
        .get(&endpoint_url)
        .map_err(|e| super::shared::ApiError::RequestBuildFailed(e.to_string()))?;

    if let Some(f) = builder_mod {
        f(&mut builder);
    }

    Ok(builder
        .build_send_request()
        .map_err(|e: foundation_core::wire::simple_http::HttpClientError| {
            super::shared::ApiError::RequestBuildFailed(e.to_string())
        })?
        .map_ready(|intro| match intro {
            super::shared::RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status: usize = intro.0.into();
                if status < 200 || status >= 300 {
                    return Err(super::shared::ApiError::HttpStatus {
                        code: status as u16,
                        headers: headers.clone(),
                        body: None,
                    });
                }
                let body =
                    foundation_core::wire::simple_http::client::body_reader::collect_string(stream);
                let parsed: ListResponse =
                    serde_json::from_str(&body).map_err(|e: serde_json::Error| {
                        super::shared::ApiError::ParseFailed(e.to_string())
                    })?;
                Ok(ApiResponse {
                    status: status as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            super::shared::RequestIntro::Failed(e) => {
                Err(super::shared::ApiError::RequestSendFailed(e.to_string()))
            }
        })
        .map_pending(|_| super::shared::ApiPending::Sending))
}
