[package]
name = "watchful"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
keywords.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# workspace dependencies
serde.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

# -- App Libs
ewe-watchers = { path = "../../crates/watchers" }

# -- Others

[lints]
workspace = true
