[package]
name = "http-app"
version = "0.0.1"
edition = "2021"
rust-version = "1.75"
license = "Apache-2.0"
authors = ["EweStudios Consulting Limited"]
repository = "{{GITHUB_NAMESPACE}}/{{PROJECT_NAME}}"
keywords = ["http-app"]

[dependencies]

# -- tokio & axum
axum = { version = "0.7.5" }
tokio = { version = "1.36", features = ["full"], default-features = true }

# -- tracing crates
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18" }

[lints]
workspace = true
