//! PowService + AsyncPowService tests — both sync and async surfaces.

use foundation_auth::server::services::pow_service::{
    AsyncPowService, PowChallenge, PowService, PowSolution,
};
use foundation_db::{AsyncKeyValueStore, KeyValueStore, MemoryStorage};
use futures_lite::future::block_on;
use sha2::{Digest, Sha256};

fn count_leading_zero_bytes(hash: &[u8]) -> u32 {
    let mut count = 0;
    for &byte in hash {
        if byte == 0 {
            count += 8;
        } else {
            count += byte.leading_zeros();
            break;
        }
    }
    count
}

// ─── Sync PowService tests ──────────────────────────────────────────────────

#[test]
fn sync_generate_and_verify_easy_pow() {
    let service = PowService::new(MemoryStorage::new(), 8, 300, 600);
    let challenge = service.generate_challenge().expect("generate challenge");
    assert_eq!(challenge.difficulty, 8);
    assert_eq!(challenge.expires_in, 300);

    let sol = find_nonce(&challenge.challenge, 1).expect("should find nonce");
    assert!(service.verify_solution(&PowSolution {
        challenge: challenge.challenge,
        solution: sol,
    }));
}

#[test]
fn sync_reuse_solution_fails() {
    let service = PowService::new(MemoryStorage::new(), 8, 300, 600);
    let challenge = service.generate_challenge().expect("generate challenge");
    let sol = find_nonce(&challenge.challenge, 1).expect("should find nonce");

    assert!(service.verify_solution(&PowSolution {
        challenge: challenge.challenge.clone(),
        solution: sol.clone(),
    }));
    assert!(!service.verify_solution(&PowSolution {
        challenge: challenge.challenge,
        solution: sol,
    }));
}

#[test]
fn sync_unknown_challenge_returns_false() {
    let service = PowService::new(MemoryStorage::new(), 8, 300, 600);
    // Never generated, just a fake challenge string
    assert!(!service.verify_solution(&PowSolution {
        challenge: "nonexistent_challenge".into(),
        solution: "0".into(),
    }));
}

// ─── Async PowService tests ─────────────────────────────────────────────────

#[test]
fn async_generate_and_verify_easy_pow() {
    block_on(async {
        let service = AsyncPowService::new(MemoryStorage::new(), 8, 300, 600);
        let challenge = service.generate_challenge().await.expect("generate challenge");
        assert_eq!(challenge.difficulty, 8);
        assert_eq!(challenge.expires_in, 300);

        let sol = find_nonce(&challenge.challenge, 1).expect("should find nonce");
        assert!(service.verify_solution(&PowSolution {
            challenge: challenge.challenge,
            solution: sol,
        }).await);
    });
}

#[test]
fn async_reuse_solution_fails() {
    block_on(async {
        let service = AsyncPowService::new(MemoryStorage::new(), 8, 300, 600);
        let challenge = service.generate_challenge().await.expect("generate challenge");
        let sol = find_nonce(&challenge.challenge, 1).expect("should find nonce");

        assert!(service.verify_solution(&PowSolution {
            challenge: challenge.challenge.clone(),
            solution: sol.clone(),
        }).await);
        assert!(!service.verify_solution(&PowSolution {
            challenge: challenge.challenge,
            solution: sol,
        }).await);
    });
}

#[test]
fn async_unknown_challenge_returns_false() {
    block_on(async {
        let service = AsyncPowService::new(MemoryStorage::new(), 8, 300, 600);
        assert!(!service.verify_solution(&PowSolution {
            challenge: "nonexistent_challenge".into(),
            solution: "0".into(),
        }).await);
    });
}

// ─── Cross-instance isolation test ──────────────────────────────────────────
// Verifies the original bug: two separate service instances sharing the same
// cache can still match a challenge generated by one and verified by the other.

#[test]
fn sync_cross_instance_challenge_match() {
    let cache = MemoryStorage::new();
    // Instance A generates the challenge
    let service_a = PowService::new(cache.clone(), 8, 300, 600);
    let challenge = service_a.generate_challenge().expect("generate");

    // Instance B (different struct, same cache) verifies it
    let service_b = PowService::new(cache, 8, 300, 600);
    let sol = find_nonce(&challenge.challenge, 1).expect("should find nonce");
    assert!(service_b.verify_solution(&PowSolution {
        challenge: challenge.challenge,
        solution: sol,
    }));
}

#[test]
fn async_cross_instance_challenge_match() {
    block_on(async {
        let cache = MemoryStorage::new();
        let service_a = AsyncPowService::new(cache.clone(), 8, 300, 600);
        let challenge = service_a.generate_challenge().await.expect("generate");

        let service_b = AsyncPowService::new(cache, 8, 300, 600);
        let sol = find_nonce(&challenge.challenge, 1).expect("should find nonce");
        assert!(service_b.verify_solution(&PowSolution {
            challenge: challenge.challenge,
            solution: sol,
        }).await);
    });
}

// ─── Helper ─────────────────────────────────────────────────────────────────

fn find_nonce(challenge: &str, min_zero_bits: u32) -> Option<String> {
    let mut nonce = 0u64;
    for _ in 0..100_000 {
        let input = format!("{challenge}{nonce}");
        let hash = Sha256::digest(input.as_bytes());
        if count_leading_zero_bytes(&hash) >= min_zero_bits {
            return Some(nonce.to_string());
        }
        nonce += 1;
    }
    None
}
