//! Auto-generated API module for gcp/chromemanagement reports:enumeratePrintJobs.
//!
//! Generated by `cargo run --bin ewe_platform gen_api`.
//! DO NOT EDIT MANUALLY.
//!
//! Feature flag: `gcp_chromemanagement_reports_enumerate_print_jobs `

#![cfg(feature = "gcp_chromemanagement_reports_enumerate_print_jobs")]
#![allow(clippy::too_many_arguments, clippy::type_complexity)]
#![allow(
    clippy::missing_errors_doc,
    clippy::doc_markdown,
    clippy::useless_format
)]
#![allow(unused_imports)]

use foundation_core::valtron::{TaskIterator, TaskIteratorExt};
use foundation_core::wire::simple_http::client::{ClientRequestBuilder, SimpleHttpClient};
use foundation_macros::JsonHash;
use serde::{Deserialize, Serialize};

use super::shared::ApiResponse;

// =============================================================================
// TYPE DECLARATIONS
// =============================================================================

/// `GoogleChromeManagementV1EnumeratePrintJobsResponse` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleChromeManagementV1EnumeratePrintJobsResponse {
    /// nextPageToken property.
    pub next_page_token: Option<String>,
    /// printJobs property.
    pub print_jobs: Option<Vec<GoogleChromeManagementV1PrintJob>>,
    /// totalSize property.
    pub total_size: Option<String>,
}

/// `GoogleChromeManagementV1PrintJob` type.
#[derive(Debug, Clone, Serialize, Deserialize, JsonHash)]
pub struct GoogleChromeManagementV1PrintJob {
    /// colorMode property.
    pub color_mode: Option<String>,
    /// completeTime property.
    pub complete_time: Option<String>,
    /// copyCount property.
    pub copy_count: Option<i64>,
    /// createTime property.
    pub create_time: Option<String>,
    /// documentPageCount property.
    pub document_page_count: Option<i64>,
    /// duplexMode property.
    pub duplex_mode: Option<String>,
    /// id property.
    pub id: Option<String>,
    /// printer property.
    pub printer: Option<String>,
    /// printerId property.
    pub printer_id: Option<String>,
    /// state property.
    pub state: Option<String>,
    /// title property.
    pub title: Option<String>,
    /// userEmail property.
    pub user_email: Option<String>,
    /// userId property.
    pub user_id: Option<String>,
}

// =============================================================================
// ARGS TYPES (per-endpoint)
// =============================================================================

/// Arguments for [`chromemanagement.customers.reports.enumeratePrintJobs_builder`].
#[derive(Debug, Clone, Serialize, JsonHash)]
pub struct ChromemanagementCustomersReportsEnumeratePrintJobsArgs {
    /// Path parameter: `customer`.
    pub customer: String,
    /// Query parameter: `filter`.
    pub filter: Option<String>,
    /// Query parameter: `orderBy`.
    pub order_by: Option<String>,
    /// Query parameter: `pageSize`.
    pub page_size: Option<String>,
    /// Query parameter: `pageToken`.
    pub page_token: Option<String>,
    /// Query parameter: `printerOrgUnitId`.
    pub printer_org_unit_id: Option<String>,
}

// =============================================================================
// CLIENT FUNCTIONS (per-endpoint)
// =============================================================================

// -----------------------------------------------------------------------------
// GET v1/customers/{customersId}/reports:enumeratePrintJobs
// -----------------------------------------------------------------------------

/// GET v1/customers/{customersId}/reports:enumeratePrintJobs.
///
/// Takes client and args, builds the request, optionally applies modifications,
/// and returns a `TaskIterator` for execution.
///
/// # Arguments
///
/// * `client` - HTTP client for making the request
/// * `builder_mod` - Optional closure to modify the request builder (e.g., add headers)
///
/// # Example
///
/// ```ignore
/// let task = chromemanagement_customers_reports_enumerate_print_jobs_request(&client, &args, Some(|b| {
///     b.header("X-Custom-Header", "value")
/// }))?;
/// ```
#[inline]
pub fn chromemanagement_customers_reports_enumerate_print_jobs_request<R, F>(
    client: &SimpleHttpClient<R>,
    builder_mod: Option<F>,
) -> Result<
    impl TaskIterator<
            Ready = Result<
                ApiResponse<GoogleChromeManagementV1EnumeratePrintJobsResponse>,
                super::shared::ApiError,
            >,
            Pending = super::shared::ApiPending,
            Spawner = super::shared::BoxedSendExecutionAction,
        > + Send
        + 'static,
    super::shared::ApiError,
>
where
    R: foundation_core::wire::simple_http::client::DnsResolver + Clone + Default + 'static,
    F: FnOnce(&mut ClientRequestBuilder<R>),
{
    let endpoint_url = format!(
        "https://chromemanagement.googleapis.com/v1/customers/{{customersId}}/reports:enumeratePrintJobs",
    );

    let mut builder = client
        .get(&endpoint_url)
        .map_err(|e| super::shared::ApiError::RequestBuildFailed(e.to_string()))?;

    if let Some(f) = builder_mod {
        f(&mut builder);
    }

    Ok(builder
        .build_send_request()
        .map_err(|e: foundation_core::wire::simple_http::HttpClientError| {
            super::shared::ApiError::RequestBuildFailed(e.to_string())
        })?
        .map_ready(|intro| match intro {
            super::shared::RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status: usize = intro.0.into();
                if status < 200 || status >= 300 {
                    return Err(super::shared::ApiError::HttpStatus {
                        code: status as u16,
                        headers: headers.clone(),
                        body: None,
                    });
                }
                let body =
                    foundation_core::wire::simple_http::client::body_reader::collect_string(stream);
                let parsed: GoogleChromeManagementV1EnumeratePrintJobsResponse =
                    serde_json::from_str(&body).map_err(|e: serde_json::Error| {
                        super::shared::ApiError::ParseFailed(e.to_string())
                    })?;
                Ok(ApiResponse {
                    status: status as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            super::shared::RequestIntro::Failed(e) => {
                Err(super::shared::ApiError::RequestSendFailed(e.to_string()))
            }
        })
        .map_pending(|_| super::shared::ApiPending::Sending))
}
