[package]
name = "ewe-mem"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
memchr = "2.7.2"
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
ewe-logs.workspace = true

[dev-dependencies]
syncbox = "0.2"

[lints]
workspace = true

[features]
nightly = []

[profile.bench]
debug = true
