[package]
name = "ewe_mem"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
ewe_trace.workspace = true
memchr = "2.7.2"
tracing = { version = "0.1.40" }
anyhow = { version = "1.0.80" }
thiserror = { version = "1.0.57" }

[dev-dependencies]
tracing-test = { version = "0.2.5" }

[lints]
workspace = true

[features]
nightly = []
default = []
debug_trace = ["ewe_trace/debug_trace"]

[profile.bench]
debug = true
