//! Auto-generated API clients for gcp/advisorynotifications.
//!
//! Generated by `cargo run --bin ewe_platform gen_provider_clients`.
//! DO NOT EDIT MANUALLY.
//!
//! Feature flag: `gcp/advisorynotifications`

#![cfg(feature = "gcp/advisorynotifications")]

pub mod types;

use crate::providers::gcp::clients::types::*;
use crate::providers::gcp::resources::*;
use foundation_core::valtron::{execute, StreamIterator, StreamIteratorExt, TaskIteratorExt};
use foundation_core::wire::simple_http::client::{
    body_reader, ClientRequestBuilder, RequestIntro, SimpleHttpClient, SystemDnsResolver,
};

/// GET v1/organizations/{organizationsId}/locations/{locationsId}/settings
/// Get notification settings.
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `advisorynotifications_organizations_locations_get_settings_execute()` to send, or `advisorynotifications_organizations_locations_get_settings` for simplest API.

pub fn advisorynotifications_organizations_locations_get_settings_builder(
    client: &SimpleHttpClient,
    name: &str,
) -> Result<ClientRequestBuilder<SystemDnsResolver>, ApiError> {
    // Build URL
    let url = format!(
        "https://advisorynotifications.googleapis.com/v1/organizations/{}/locations/{}/settings",
        name,
    );

    // Build request
    let builder = client
        .get(&url)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    Ok(builder)
}

/// GET v1/organizations/{organizationsId}/locations/{locationsId}/settings
/// Get notification settings.
///
/// Takes a `ClientRequestBuilder`, builds and executes the request.
/// For customization, use `advisorynotifications_organizations_locations_get_settings_builder()` then pass to this function.
///
/// # Arguments
///
/// * `builder` - ClientRequestBuilder from advisorynotifications_organizations_locations_get_settings_builder()
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn advisorynotifications_organizations_locations_get_settings_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<
            D = Result<ApiResponse<GoogleCloudAdvisorynotificationsV1Settings>, ApiError>,
            P = ApiPending,
        > + Send
        + 'static,
    ApiError,
> {
    // Get SendRequestTask from builder
    let task = builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: GoogleCloudAdvisorynotificationsV1Settings =
                    serde_json::from_str(&body)
                        .map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending);

    // Convert TaskIterator to StreamIterator
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// GET v1/organizations/{organizationsId}/locations/{locationsId}/settings
/// Get notification settings.
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `advisorynotifications_organizations_locations_get_settings_builder()` + `advisorynotifications_organizations_locations_get_settings_execute()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn advisorynotifications_organizations_locations_get_settings(
    client: &SimpleHttpClient,
    name: &str,
) -> Result<
    impl StreamIterator<
            D = Result<ApiResponse<GoogleCloudAdvisorynotificationsV1Settings>, ApiError>,
            P = ApiPending,
        > + Send
        + 'static,
    ApiError,
> {
    let builder = advisorynotifications_organizations_locations_get_settings_builder(client, name)?;
    advisorynotifications_organizations_locations_get_settings_execute(builder)
}

/// GET v1/organizations/{organizationsId}/locations/{locationsId}/settings
/// Update notification settings.
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `advisorynotifications_organizations_locations_update_settings_execute()` to send, or `advisorynotifications_organizations_locations_update_settings` for simplest API.

pub fn advisorynotifications_organizations_locations_update_settings_builder(
    client: &SimpleHttpClient,
    name: &str,
    body: &GoogleCloudAdvisorynotificationsV1Settings,
) -> Result<ClientRequestBuilder<SystemDnsResolver>, ApiError> {
    // Build URL
    let url = format!(
        "https://advisorynotifications.googleapis.com/v1/organizations/{}/locations/{}/settings",
        name,
    );

    // Build request
    let builder = client
        .get(&url)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    builder
        .body_json(body)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// GET v1/organizations/{organizationsId}/locations/{locationsId}/settings
/// Update notification settings.
///
/// Takes a `ClientRequestBuilder`, builds and executes the request.
/// For customization, use `advisorynotifications_organizations_locations_update_settings_builder()` then pass to this function.
///
/// # Arguments
///
/// * `builder` - ClientRequestBuilder from advisorynotifications_organizations_locations_update_settings_builder()
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn advisorynotifications_organizations_locations_update_settings_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<
            D = Result<ApiResponse<GoogleCloudAdvisorynotificationsV1Settings>, ApiError>,
            P = ApiPending,
        > + Send
        + 'static,
    ApiError,
> {
    // Get SendRequestTask from builder
    let task = builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: GoogleCloudAdvisorynotificationsV1Settings =
                    serde_json::from_str(&body)
                        .map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending);

    // Convert TaskIterator to StreamIterator
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// GET v1/organizations/{organizationsId}/locations/{locationsId}/settings
/// Update notification settings.
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `advisorynotifications_organizations_locations_update_settings_builder()` + `advisorynotifications_organizations_locations_update_settings_execute()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn advisorynotifications_organizations_locations_update_settings(
    client: &SimpleHttpClient,
    name: &str,
    body: &GoogleCloudAdvisorynotificationsV1Settings,
) -> Result<
    impl StreamIterator<
            D = Result<ApiResponse<GoogleCloudAdvisorynotificationsV1Settings>, ApiError>,
            P = ApiPending,
        > + Send
        + 'static,
    ApiError,
> {
    let builder =
        advisorynotifications_organizations_locations_update_settings_builder(client, name, body)?;
    advisorynotifications_organizations_locations_update_settings_execute(builder)
}

/// GET v1/organizations/{organizationsId}/locations/{locationsId}/notifications/{notificationsId}
/// Gets a notification.
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `advisorynotifications_organizations_locations_notifications_get_execute()` to send, or `advisorynotifications_organizations_locations_notifications_get` for simplest API.

pub fn advisorynotifications_organizations_locations_notifications_get_builder(
    client: &SimpleHttpClient,
    name: &str,
    languageCode: Option<&str>,
) -> Result<ClientRequestBuilder<SystemDnsResolver>, ApiError> {
    // Build URL
    let url = format!(
        "https://advisorynotifications.googleapis.com/v1/organizations/{}/locations/{}/notifications/{}",
        name,
    );

    // Build request
    let mut query_parts = Vec::new();
    if let Some(val) = languageCode {
        query_parts.push(format!("languageCode={}", val));
    }

    let url_with_query = if query_parts.is_empty() {
        url
    } else {
        format!("{}?{}", url, query_parts.join("&"))
    };

    let builder = client
        .get(&url_with_query)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    Ok(builder)
}

/// GET v1/organizations/{organizationsId}/locations/{locationsId}/notifications/{notificationsId}
/// Gets a notification.
///
/// Takes a `ClientRequestBuilder`, builds and executes the request.
/// For customization, use `advisorynotifications_organizations_locations_notifications_get_builder()` then pass to this function.
///
/// # Arguments
///
/// * `builder` - ClientRequestBuilder from advisorynotifications_organizations_locations_notifications_get_builder()
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn advisorynotifications_organizations_locations_notifications_get_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<
            D = Result<ApiResponse<GoogleCloudAdvisorynotificationsV1Notification>, ApiError>,
            P = ApiPending,
        > + Send
        + 'static,
    ApiError,
> {
    // Get SendRequestTask from builder
    let task = builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: GoogleCloudAdvisorynotificationsV1Notification =
                    serde_json::from_str(&body)
                        .map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending);

    // Convert TaskIterator to StreamIterator
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// GET v1/organizations/{organizationsId}/locations/{locationsId}/notifications/{notificationsId}
/// Gets a notification.
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `advisorynotifications_organizations_locations_notifications_get_builder()` + `advisorynotifications_organizations_locations_notifications_get_execute()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn advisorynotifications_organizations_locations_notifications_get(
    client: &SimpleHttpClient,
    name: &str,
    languageCode: Option<&str>,
) -> Result<
    impl StreamIterator<
            D = Result<ApiResponse<GoogleCloudAdvisorynotificationsV1Notification>, ApiError>,
            P = ApiPending,
        > + Send
        + 'static,
    ApiError,
> {
    let builder = advisorynotifications_organizations_locations_notifications_get_builder(
        client,
        name,
        languageCode,
    )?;
    advisorynotifications_organizations_locations_notifications_get_execute(builder)
}

/// GET v1/organizations/{organizationsId}/locations/{locationsId}/notifications
/// Lists notifications under a given parent.
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `advisorynotifications_organizations_locations_notifications_list_execute()` to send, or `advisorynotifications_organizations_locations_notifications_list` for simplest API.

pub fn advisorynotifications_organizations_locations_notifications_list_builder(
    client: &SimpleHttpClient,
    parent: &str,
    languageCode: Option<&str>,
    pageSize: Option<i32>,
    pageToken: Option<&str>,
    view: Option<&str>,
) -> Result<ClientRequestBuilder<SystemDnsResolver>, ApiError> {
    // Build URL
    let url = format!(
        "https://advisorynotifications.googleapis.com/v1/organizations/{}/locations/{}/notifications",
        parent,
    );

    // Build request
    let mut query_parts = Vec::new();
    if let Some(val) = languageCode {
        query_parts.push(format!("languageCode={}", val));
    }
    if let Some(val) = pageSize {
        query_parts.push(format!("pageSize={}", val));
    }
    if let Some(val) = pageToken {
        query_parts.push(format!("pageToken={}", val));
    }
    if let Some(val) = view {
        query_parts.push(format!("view={}", val));
    }

    let url_with_query = if query_parts.is_empty() {
        url
    } else {
        format!("{}?{}", url, query_parts.join("&"))
    };

    let builder = client
        .get(&url_with_query)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    Ok(builder)
}

/// GET v1/organizations/{organizationsId}/locations/{locationsId}/notifications
/// Lists notifications under a given parent.
///
/// Takes a `ClientRequestBuilder`, builds and executes the request.
/// For customization, use `advisorynotifications_organizations_locations_notifications_list_builder()` then pass to this function.
///
/// # Arguments
///
/// * `builder` - ClientRequestBuilder from advisorynotifications_organizations_locations_notifications_list_builder()
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn advisorynotifications_organizations_locations_notifications_list_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<
            D = Result<
                ApiResponse<GoogleCloudAdvisorynotificationsV1ListNotificationsResponse>,
                ApiError,
            >,
            P = ApiPending,
        > + Send
        + 'static,
    ApiError,
> {
    // Get SendRequestTask from builder
    let task = builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: GoogleCloudAdvisorynotificationsV1ListNotificationsResponse =
                    serde_json::from_str(&body)
                        .map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending);

    // Convert TaskIterator to StreamIterator
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// GET v1/organizations/{organizationsId}/locations/{locationsId}/notifications
/// Lists notifications under a given parent.
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `advisorynotifications_organizations_locations_notifications_list_builder()` + `advisorynotifications_organizations_locations_notifications_list_execute()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn advisorynotifications_organizations_locations_notifications_list(
    client: &SimpleHttpClient,
    parent: &str,
    languageCode: Option<&str>,
    pageSize: Option<i32>,
    pageToken: Option<&str>,
    view: Option<&str>,
) -> Result<
    impl StreamIterator<
            D = Result<
                ApiResponse<GoogleCloudAdvisorynotificationsV1ListNotificationsResponse>,
                ApiError,
            >,
            P = ApiPending,
        > + Send
        + 'static,
    ApiError,
> {
    let builder = advisorynotifications_organizations_locations_notifications_list_builder(
        client,
        parent,
        languageCode,
        pageSize,
        pageToken,
        view,
    )?;
    advisorynotifications_organizations_locations_notifications_list_execute(builder)
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/settings
/// Get notification settings.
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `advisorynotifications_projects_locations_get_settings_execute()` to send, or `advisorynotifications_projects_locations_get_settings` for simplest API.

pub fn advisorynotifications_projects_locations_get_settings_builder(
    client: &SimpleHttpClient,
    name: &str,
) -> Result<ClientRequestBuilder<SystemDnsResolver>, ApiError> {
    // Build URL
    let url = format!(
        "https://advisorynotifications.googleapis.com/v1/projects/{}/locations/{}/settings",
        name,
    );

    // Build request
    let builder = client
        .get(&url)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    Ok(builder)
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/settings
/// Get notification settings.
///
/// Takes a `ClientRequestBuilder`, builds and executes the request.
/// For customization, use `advisorynotifications_projects_locations_get_settings_builder()` then pass to this function.
///
/// # Arguments
///
/// * `builder` - ClientRequestBuilder from advisorynotifications_projects_locations_get_settings_builder()
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn advisorynotifications_projects_locations_get_settings_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<
            D = Result<ApiResponse<GoogleCloudAdvisorynotificationsV1Settings>, ApiError>,
            P = ApiPending,
        > + Send
        + 'static,
    ApiError,
> {
    // Get SendRequestTask from builder
    let task = builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: GoogleCloudAdvisorynotificationsV1Settings =
                    serde_json::from_str(&body)
                        .map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending);

    // Convert TaskIterator to StreamIterator
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/settings
/// Get notification settings.
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `advisorynotifications_projects_locations_get_settings_builder()` + `advisorynotifications_projects_locations_get_settings_execute()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn advisorynotifications_projects_locations_get_settings(
    client: &SimpleHttpClient,
    name: &str,
) -> Result<
    impl StreamIterator<
            D = Result<ApiResponse<GoogleCloudAdvisorynotificationsV1Settings>, ApiError>,
            P = ApiPending,
        > + Send
        + 'static,
    ApiError,
> {
    let builder = advisorynotifications_projects_locations_get_settings_builder(client, name)?;
    advisorynotifications_projects_locations_get_settings_execute(builder)
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/settings
/// Update notification settings.
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `advisorynotifications_projects_locations_update_settings_execute()` to send, or `advisorynotifications_projects_locations_update_settings` for simplest API.

pub fn advisorynotifications_projects_locations_update_settings_builder(
    client: &SimpleHttpClient,
    name: &str,
    body: &GoogleCloudAdvisorynotificationsV1Settings,
) -> Result<ClientRequestBuilder<SystemDnsResolver>, ApiError> {
    // Build URL
    let url = format!(
        "https://advisorynotifications.googleapis.com/v1/projects/{}/locations/{}/settings",
        name,
    );

    // Build request
    let builder = client
        .get(&url)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    builder
        .body_json(body)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/settings
/// Update notification settings.
///
/// Takes a `ClientRequestBuilder`, builds and executes the request.
/// For customization, use `advisorynotifications_projects_locations_update_settings_builder()` then pass to this function.
///
/// # Arguments
///
/// * `builder` - ClientRequestBuilder from advisorynotifications_projects_locations_update_settings_builder()
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn advisorynotifications_projects_locations_update_settings_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<
            D = Result<ApiResponse<GoogleCloudAdvisorynotificationsV1Settings>, ApiError>,
            P = ApiPending,
        > + Send
        + 'static,
    ApiError,
> {
    // Get SendRequestTask from builder
    let task = builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: GoogleCloudAdvisorynotificationsV1Settings =
                    serde_json::from_str(&body)
                        .map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending);

    // Convert TaskIterator to StreamIterator
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/settings
/// Update notification settings.
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `advisorynotifications_projects_locations_update_settings_builder()` + `advisorynotifications_projects_locations_update_settings_execute()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn advisorynotifications_projects_locations_update_settings(
    client: &SimpleHttpClient,
    name: &str,
    body: &GoogleCloudAdvisorynotificationsV1Settings,
) -> Result<
    impl StreamIterator<
            D = Result<ApiResponse<GoogleCloudAdvisorynotificationsV1Settings>, ApiError>,
            P = ApiPending,
        > + Send
        + 'static,
    ApiError,
> {
    let builder =
        advisorynotifications_projects_locations_update_settings_builder(client, name, body)?;
    advisorynotifications_projects_locations_update_settings_execute(builder)
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/notifications/{notificationsId}
/// Gets a notification.
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `advisorynotifications_projects_locations_notifications_get_execute()` to send, or `advisorynotifications_projects_locations_notifications_get` for simplest API.

pub fn advisorynotifications_projects_locations_notifications_get_builder(
    client: &SimpleHttpClient,
    name: &str,
    languageCode: Option<&str>,
) -> Result<ClientRequestBuilder<SystemDnsResolver>, ApiError> {
    // Build URL
    let url = format!(
        "https://advisorynotifications.googleapis.com/v1/projects/{}/locations/{}/notifications/{}",
        name,
    );

    // Build request
    let mut query_parts = Vec::new();
    if let Some(val) = languageCode {
        query_parts.push(format!("languageCode={}", val));
    }

    let url_with_query = if query_parts.is_empty() {
        url
    } else {
        format!("{}?{}", url, query_parts.join("&"))
    };

    let builder = client
        .get(&url_with_query)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    Ok(builder)
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/notifications/{notificationsId}
/// Gets a notification.
///
/// Takes a `ClientRequestBuilder`, builds and executes the request.
/// For customization, use `advisorynotifications_projects_locations_notifications_get_builder()` then pass to this function.
///
/// # Arguments
///
/// * `builder` - ClientRequestBuilder from advisorynotifications_projects_locations_notifications_get_builder()
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn advisorynotifications_projects_locations_notifications_get_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<
            D = Result<ApiResponse<GoogleCloudAdvisorynotificationsV1Notification>, ApiError>,
            P = ApiPending,
        > + Send
        + 'static,
    ApiError,
> {
    // Get SendRequestTask from builder
    let task = builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: GoogleCloudAdvisorynotificationsV1Notification =
                    serde_json::from_str(&body)
                        .map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending);

    // Convert TaskIterator to StreamIterator
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/notifications/{notificationsId}
/// Gets a notification.
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `advisorynotifications_projects_locations_notifications_get_builder()` + `advisorynotifications_projects_locations_notifications_get_execute()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn advisorynotifications_projects_locations_notifications_get(
    client: &SimpleHttpClient,
    name: &str,
    languageCode: Option<&str>,
) -> Result<
    impl StreamIterator<
            D = Result<ApiResponse<GoogleCloudAdvisorynotificationsV1Notification>, ApiError>,
            P = ApiPending,
        > + Send
        + 'static,
    ApiError,
> {
    let builder = advisorynotifications_projects_locations_notifications_get_builder(
        client,
        name,
        languageCode,
    )?;
    advisorynotifications_projects_locations_notifications_get_execute(builder)
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/notifications
/// Lists notifications under a given parent.
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `advisorynotifications_projects_locations_notifications_list_execute()` to send, or `advisorynotifications_projects_locations_notifications_list` for simplest API.

pub fn advisorynotifications_projects_locations_notifications_list_builder(
    client: &SimpleHttpClient,
    parent: &str,
    languageCode: Option<&str>,
    pageSize: Option<i32>,
    pageToken: Option<&str>,
    view: Option<&str>,
) -> Result<ClientRequestBuilder<SystemDnsResolver>, ApiError> {
    // Build URL
    let url = format!(
        "https://advisorynotifications.googleapis.com/v1/projects/{}/locations/{}/notifications",
        parent,
    );

    // Build request
    let mut query_parts = Vec::new();
    if let Some(val) = languageCode {
        query_parts.push(format!("languageCode={}", val));
    }
    if let Some(val) = pageSize {
        query_parts.push(format!("pageSize={}", val));
    }
    if let Some(val) = pageToken {
        query_parts.push(format!("pageToken={}", val));
    }
    if let Some(val) = view {
        query_parts.push(format!("view={}", val));
    }

    let url_with_query = if query_parts.is_empty() {
        url
    } else {
        format!("{}?{}", url, query_parts.join("&"))
    };

    let builder = client
        .get(&url_with_query)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    Ok(builder)
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/notifications
/// Lists notifications under a given parent.
///
/// Takes a `ClientRequestBuilder`, builds and executes the request.
/// For customization, use `advisorynotifications_projects_locations_notifications_list_builder()` then pass to this function.
///
/// # Arguments
///
/// * `builder` - ClientRequestBuilder from advisorynotifications_projects_locations_notifications_list_builder()
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn advisorynotifications_projects_locations_notifications_list_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<
            D = Result<
                ApiResponse<GoogleCloudAdvisorynotificationsV1ListNotificationsResponse>,
                ApiError,
            >,
            P = ApiPending,
        > + Send
        + 'static,
    ApiError,
> {
    // Get SendRequestTask from builder
    let task = builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: GoogleCloudAdvisorynotificationsV1ListNotificationsResponse =
                    serde_json::from_str(&body)
                        .map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending);

    // Convert TaskIterator to StreamIterator
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/notifications
/// Lists notifications under a given parent.
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `advisorynotifications_projects_locations_notifications_list_builder()` + `advisorynotifications_projects_locations_notifications_list_execute()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn advisorynotifications_projects_locations_notifications_list(
    client: &SimpleHttpClient,
    parent: &str,
    languageCode: Option<&str>,
    pageSize: Option<i32>,
    pageToken: Option<&str>,
    view: Option<&str>,
) -> Result<
    impl StreamIterator<
            D = Result<
                ApiResponse<GoogleCloudAdvisorynotificationsV1ListNotificationsResponse>,
                ApiError,
            >,
            P = ApiPending,
        > + Send
        + 'static,
    ApiError,
> {
    let builder = advisorynotifications_projects_locations_notifications_list_builder(
        client,
        parent,
        languageCode,
        pageSize,
        pageToken,
        view,
    )?;
    advisorynotifications_projects_locations_notifications_list_execute(builder)
}
