//! Auto-generated API clients for gcp/gmailpostmastertools.
//!
//! Generated by `cargo run --bin ewe_platform gen_provider_clients`.
//! DO NOT EDIT MANUALLY.
//!
//! Feature flag: `gcp/gmailpostmastertools`

#![cfg(feature = "gcp/gmailpostmastertools")]

pub mod types;

use crate::providers::gcp::clients::types::*;
use crate::providers::gcp::resources::*;
use foundation_core::valtron::{execute, StreamIterator, StreamIteratorExt, TaskIteratorExt};
use foundation_core::wire::simple_http::client::{
    body_reader, ClientRequestBuilder, RequestIntro, SimpleHttpClient, SystemDnsResolver,
};

/// GET v2/domainStats:batchQuery
/// Executes a batch of QueryDomainStats requests for multiple domains. Returns PERMISSION_DENIED if you don't have permission to access DomainStats for any of the requested domains.
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `gmailpostmastertools_domain_stats_batch_query_execute()` to send, or `gmailpostmastertools_domain_stats_batch_query` for simplest API.

pub fn gmailpostmastertools_domain_stats_batch_query_builder(
    client: &SimpleHttpClient,
    body: &BatchQueryDomainStatsRequest,
) -> Result<ClientRequestBuilder<SystemDnsResolver>, ApiError> {
    // Build URL
    let url = format!("https://gmailpostmastertools.googleapis.com/v2/domainStats:batchQuery",);

    // Build request
    let builder = client
        .get(&url)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    builder
        .body_json(body)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// GET v2/domainStats:batchQuery
/// Executes a batch of QueryDomainStats requests for multiple domains. Returns PERMISSION_DENIED if you don't have permission to access DomainStats for any of the requested domains.
///
/// Takes a `ClientRequestBuilder`, builds and executes the request.
/// For customization, use `gmailpostmastertools_domain_stats_batch_query_builder()` then pass to this function.
///
/// # Arguments
///
/// * `builder` - ClientRequestBuilder from gmailpostmastertools_domain_stats_batch_query_builder()
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn gmailpostmastertools_domain_stats_batch_query_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<
            D = Result<ApiResponse<BatchQueryDomainStatsResponse>, ApiError>,
            P = ApiPending,
        > + Send
        + 'static,
    ApiError,
> {
    // Get SendRequestTask from builder
    let task = builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: BatchQueryDomainStatsResponse = serde_json::from_str(&body)
                    .map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending);

    // Convert TaskIterator to StreamIterator
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// GET v2/domainStats:batchQuery
/// Executes a batch of QueryDomainStats requests for multiple domains. Returns PERMISSION_DENIED if you don't have permission to access DomainStats for any of the requested domains.
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `gmailpostmastertools_domain_stats_batch_query_builder()` + `gmailpostmastertools_domain_stats_batch_query_execute()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn gmailpostmastertools_domain_stats_batch_query(
    client: &SimpleHttpClient,
    body: &BatchQueryDomainStatsRequest,
) -> Result<
    impl StreamIterator<
            D = Result<ApiResponse<BatchQueryDomainStatsResponse>, ApiError>,
            P = ApiPending,
        > + Send
        + 'static,
    ApiError,
> {
    let builder = gmailpostmastertools_domain_stats_batch_query_builder(client, body)?;
    gmailpostmastertools_domain_stats_batch_query_execute(builder)
}

/// GET v2/domains/{domainsId}
/// Retrieves detailed information about a domain registered by you. Returns NOT_FOUND if the domain is not registered by you. Domain represents the metadata of a domain that has been registered within the system and linked to a user.
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `gmailpostmastertools_domains_get_execute()` to send, or `gmailpostmastertools_domains_get` for simplest API.

pub fn gmailpostmastertools_domains_get_builder(
    client: &SimpleHttpClient,
    name: &str,
) -> Result<ClientRequestBuilder<SystemDnsResolver>, ApiError> {
    // Build URL
    let url = format!(
        "https://gmailpostmastertools.googleapis.com/v2/domains/{}",
        name,
    );

    // Build request
    let builder = client
        .get(&url)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    Ok(builder)
}

/// GET v2/domains/{domainsId}
/// Retrieves detailed information about a domain registered by you. Returns NOT_FOUND if the domain is not registered by you. Domain represents the metadata of a domain that has been registered within the system and linked to a user.
///
/// Takes a `ClientRequestBuilder`, builds and executes the request.
/// For customization, use `gmailpostmastertools_domains_get_builder()` then pass to this function.
///
/// # Arguments
///
/// * `builder` - ClientRequestBuilder from gmailpostmastertools_domains_get_builder()
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn gmailpostmastertools_domains_get_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<Domain>, ApiError>, P = ApiPending> + Send + 'static,
    ApiError,
> {
    // Get SendRequestTask from builder
    let task = builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: Domain = serde_json::from_str(&body)
                    .map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending);

    // Convert TaskIterator to StreamIterator
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// GET v2/domains/{domainsId}
/// Retrieves detailed information about a domain registered by you. Returns NOT_FOUND if the domain is not registered by you. Domain represents the metadata of a domain that has been registered within the system and linked to a user.
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `gmailpostmastertools_domains_get_builder()` + `gmailpostmastertools_domains_get_execute()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn gmailpostmastertools_domains_get(
    client: &SimpleHttpClient,
    name: &str,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<Domain>, ApiError>, P = ApiPending> + Send + 'static,
    ApiError,
> {
    let builder = gmailpostmastertools_domains_get_builder(client, name)?;
    gmailpostmastertools_domains_get_execute(builder)
}

/// GET v2/domains/{domainsId}/complianceStatus
/// Retrieves the compliance status for a given domain. Returns PERMISSION_DENIED if you don't have permission to access compliance status for the domain.
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `gmailpostmastertools_domains_get_compliance_status_execute()` to send, or `gmailpostmastertools_domains_get_compliance_status` for simplest API.

pub fn gmailpostmastertools_domains_get_compliance_status_builder(
    client: &SimpleHttpClient,
    name: &str,
) -> Result<ClientRequestBuilder<SystemDnsResolver>, ApiError> {
    // Build URL
    let url = format!(
        "https://gmailpostmastertools.googleapis.com/v2/domains/{}/complianceStatus",
        name,
    );

    // Build request
    let builder = client
        .get(&url)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    Ok(builder)
}

/// GET v2/domains/{domainsId}/complianceStatus
/// Retrieves the compliance status for a given domain. Returns PERMISSION_DENIED if you don't have permission to access compliance status for the domain.
///
/// Takes a `ClientRequestBuilder`, builds and executes the request.
/// For customization, use `gmailpostmastertools_domains_get_compliance_status_builder()` then pass to this function.
///
/// # Arguments
///
/// * `builder` - ClientRequestBuilder from gmailpostmastertools_domains_get_compliance_status_builder()
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn gmailpostmastertools_domains_get_compliance_status_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<DomainComplianceStatus>, ApiError>, P = ApiPending>
        + Send
        + 'static,
    ApiError,
> {
    // Get SendRequestTask from builder
    let task = builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: DomainComplianceStatus = serde_json::from_str(&body)
                    .map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending);

    // Convert TaskIterator to StreamIterator
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// GET v2/domains/{domainsId}/complianceStatus
/// Retrieves the compliance status for a given domain. Returns PERMISSION_DENIED if you don't have permission to access compliance status for the domain.
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `gmailpostmastertools_domains_get_compliance_status_builder()` + `gmailpostmastertools_domains_get_compliance_status_execute()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn gmailpostmastertools_domains_get_compliance_status(
    client: &SimpleHttpClient,
    name: &str,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<DomainComplianceStatus>, ApiError>, P = ApiPending>
        + Send
        + 'static,
    ApiError,
> {
    let builder = gmailpostmastertools_domains_get_compliance_status_builder(client, name)?;
    gmailpostmastertools_domains_get_compliance_status_execute(builder)
}

/// GET v2/domains
/// Retrieves a list of all domains registered by you, along with their corresponding metadata. The order of domains in the response is unspecified and non-deterministic. Newly registered domains will not necessarily be added to the end of this list.
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `gmailpostmastertools_domains_list_execute()` to send, or `gmailpostmastertools_domains_list` for simplest API.

pub fn gmailpostmastertools_domains_list_builder(
    client: &SimpleHttpClient,
    pageSize: Option<i32>,
    pageToken: Option<&str>,
) -> Result<ClientRequestBuilder<SystemDnsResolver>, ApiError> {
    // Build URL
    let url = format!("https://gmailpostmastertools.googleapis.com/v2/domains",);

    // Build request
    let mut query_parts = Vec::new();
    if let Some(val) = pageSize {
        query_parts.push(format!("pageSize={}", val));
    }
    if let Some(val) = pageToken {
        query_parts.push(format!("pageToken={}", val));
    }

    let url_with_query = if query_parts.is_empty() {
        url
    } else {
        format!("{}?{}", url, query_parts.join("&"))
    };

    let builder = client
        .get(&url_with_query)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    Ok(builder)
}

/// GET v2/domains
/// Retrieves a list of all domains registered by you, along with their corresponding metadata. The order of domains in the response is unspecified and non-deterministic. Newly registered domains will not necessarily be added to the end of this list.
///
/// Takes a `ClientRequestBuilder`, builds and executes the request.
/// For customization, use `gmailpostmastertools_domains_list_builder()` then pass to this function.
///
/// # Arguments
///
/// * `builder` - ClientRequestBuilder from gmailpostmastertools_domains_list_builder()
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn gmailpostmastertools_domains_list_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<ListDomainsResponse>, ApiError>, P = ApiPending>
        + Send
        + 'static,
    ApiError,
> {
    // Get SendRequestTask from builder
    let task = builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: ListDomainsResponse = serde_json::from_str(&body)
                    .map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending);

    // Convert TaskIterator to StreamIterator
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// GET v2/domains
/// Retrieves a list of all domains registered by you, along with their corresponding metadata. The order of domains in the response is unspecified and non-deterministic. Newly registered domains will not necessarily be added to the end of this list.
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `gmailpostmastertools_domains_list_builder()` + `gmailpostmastertools_domains_list_execute()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn gmailpostmastertools_domains_list(
    client: &SimpleHttpClient,
    pageSize: Option<i32>,
    pageToken: Option<&str>,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<ListDomainsResponse>, ApiError>, P = ApiPending>
        + Send
        + 'static,
    ApiError,
> {
    let builder = gmailpostmastertools_domains_list_builder(client, pageSize, pageToken)?;
    gmailpostmastertools_domains_list_execute(builder)
}

/// GET v2/domains/{domainsId}/domainStats:query
/// Retrieves a list of domain statistics for a given domain and time period. Returns statistics only for dates where data is available. Returns PERMISSION_DENIED if you don't have permission to access DomainStats for the domain.
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `gmailpostmastertools_domains_domain_stats_query_execute()` to send, or `gmailpostmastertools_domains_domain_stats_query` for simplest API.

pub fn gmailpostmastertools_domains_domain_stats_query_builder(
    client: &SimpleHttpClient,
    parent: &str,
    body: &QueryDomainStatsRequest,
) -> Result<ClientRequestBuilder<SystemDnsResolver>, ApiError> {
    // Build URL
    let url = format!(
        "https://gmailpostmastertools.googleapis.com/v2/domains/{}/domainStats:query",
        parent,
    );

    // Build request
    let builder = client
        .get(&url)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    builder
        .body_json(body)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// GET v2/domains/{domainsId}/domainStats:query
/// Retrieves a list of domain statistics for a given domain and time period. Returns statistics only for dates where data is available. Returns PERMISSION_DENIED if you don't have permission to access DomainStats for the domain.
///
/// Takes a `ClientRequestBuilder`, builds and executes the request.
/// For customization, use `gmailpostmastertools_domains_domain_stats_query_builder()` then pass to this function.
///
/// # Arguments
///
/// * `builder` - ClientRequestBuilder from gmailpostmastertools_domains_domain_stats_query_builder()
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn gmailpostmastertools_domains_domain_stats_query_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<QueryDomainStatsResponse>, ApiError>, P = ApiPending>
        + Send
        + 'static,
    ApiError,
> {
    // Get SendRequestTask from builder
    let task = builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: QueryDomainStatsResponse = serde_json::from_str(&body)
                    .map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending);

    // Convert TaskIterator to StreamIterator
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// GET v2/domains/{domainsId}/domainStats:query
/// Retrieves a list of domain statistics for a given domain and time period. Returns statistics only for dates where data is available. Returns PERMISSION_DENIED if you don't have permission to access DomainStats for the domain.
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `gmailpostmastertools_domains_domain_stats_query_builder()` + `gmailpostmastertools_domains_domain_stats_query_execute()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn gmailpostmastertools_domains_domain_stats_query(
    client: &SimpleHttpClient,
    parent: &str,
    body: &QueryDomainStatsRequest,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<QueryDomainStatsResponse>, ApiError>, P = ApiPending>
        + Send
        + 'static,
    ApiError,
> {
    let builder = gmailpostmastertools_domains_domain_stats_query_builder(client, parent, body)?;
    gmailpostmastertools_domains_domain_stats_query_execute(builder)
}
