//! Auto-generated API clients for gcp/localservices.
//!
//! Generated by `cargo run --bin ewe_platform gen_provider_clients`.
//! DO NOT EDIT MANUALLY.
//!
//! Feature flag: `gcp/localservices`

#![cfg(feature = "gcp/localservices")]

pub mod types;

use crate::providers::gcp::clients::types::*;
use crate::providers::gcp::resources::*;
use foundation_core::valtron::{execute, StreamIterator, StreamIteratorExt, TaskIteratorExt};
use foundation_core::wire::simple_http::client::{
    body_reader, ClientRequestBuilder, RequestIntro, SimpleHttpClient, SystemDnsResolver,
};

/// GET v1/accountReports:search
/// Get account reports containing aggregate account data of all linked GLS accounts. Caller needs to provide their manager customer id and the associated auth credential that allows them read permissions on their linked accounts.
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `localservices_account_reports_search_execute()` to send, or `localservices_account_reports_search` for simplest API.

pub fn localservices_account_reports_search_builder(
    client: &SimpleHttpClient,
    endDate_day: Option<i32>,
    endDate_month: Option<i32>,
    endDate_year: Option<i32>,
    pageSize: Option<i32>,
    pageToken: Option<&str>,
    query: Option<&str>,
    startDate_day: Option<i32>,
    startDate_month: Option<i32>,
    startDate_year: Option<i32>,
) -> Result<ClientRequestBuilder<SystemDnsResolver>, ApiError> {
    // Build URL
    let url = format!("https://localservices.googleapis.com/v1/accountReports:search",);

    // Build request
    let mut query_parts = Vec::new();
    if let Some(val) = endDate_day {
        query_parts.push(format!("endDate_day={}", val));
    }
    if let Some(val) = endDate_month {
        query_parts.push(format!("endDate_month={}", val));
    }
    if let Some(val) = endDate_year {
        query_parts.push(format!("endDate_year={}", val));
    }
    if let Some(val) = pageSize {
        query_parts.push(format!("pageSize={}", val));
    }
    if let Some(val) = pageToken {
        query_parts.push(format!("pageToken={}", val));
    }
    if let Some(val) = query {
        query_parts.push(format!("query={}", val));
    }
    if let Some(val) = startDate_day {
        query_parts.push(format!("startDate_day={}", val));
    }
    if let Some(val) = startDate_month {
        query_parts.push(format!("startDate_month={}", val));
    }
    if let Some(val) = startDate_year {
        query_parts.push(format!("startDate_year={}", val));
    }

    let url_with_query = if query_parts.is_empty() {
        url
    } else {
        format!("{}?{}", url, query_parts.join("&"))
    };

    let builder = client
        .get(&url_with_query)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    Ok(builder)
}

/// GET v1/accountReports:search
/// Get account reports containing aggregate account data of all linked GLS accounts. Caller needs to provide their manager customer id and the associated auth credential that allows them read permissions on their linked accounts.
///
/// Takes a `ClientRequestBuilder`, builds and executes the request.
/// For customization, use `localservices_account_reports_search_builder()` then pass to this function.
///
/// # Arguments
///
/// * `builder` - ClientRequestBuilder from localservices_account_reports_search_builder()
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn localservices_account_reports_search_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<
            D = Result<
                ApiResponse<GoogleAdsHomeservicesLocalservicesV1SearchAccountReportsResponse>,
                ApiError,
            >,
            P = ApiPending,
        > + Send
        + 'static,
    ApiError,
> {
    // Get SendRequestTask from builder
    let task = builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: GoogleAdsHomeservicesLocalservicesV1SearchAccountReportsResponse =
                    serde_json::from_str(&body)
                        .map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending);

    // Convert TaskIterator to StreamIterator
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// GET v1/accountReports:search
/// Get account reports containing aggregate account data of all linked GLS accounts. Caller needs to provide their manager customer id and the associated auth credential that allows them read permissions on their linked accounts.
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `localservices_account_reports_search_builder()` + `localservices_account_reports_search_execute()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn localservices_account_reports_search(
    client: &SimpleHttpClient,
    endDate_day: Option<i32>,
    endDate_month: Option<i32>,
    endDate_year: Option<i32>,
    pageSize: Option<i32>,
    pageToken: Option<&str>,
    query: Option<&str>,
    startDate_day: Option<i32>,
    startDate_month: Option<i32>,
    startDate_year: Option<i32>,
) -> Result<
    impl StreamIterator<
            D = Result<
                ApiResponse<GoogleAdsHomeservicesLocalservicesV1SearchAccountReportsResponse>,
                ApiError,
            >,
            P = ApiPending,
        > + Send
        + 'static,
    ApiError,
> {
    let builder = localservices_account_reports_search_builder(
        client,
        endDate_day,
        endDate_month,
        endDate_year,
        pageSize,
        pageToken,
        query,
        startDate_day,
        startDate_month,
        startDate_year,
    )?;
    localservices_account_reports_search_execute(builder)
}

/// GET v1/detailedLeadReports:search
/// Get detailed lead reports containing leads that have been received by all linked GLS accounts. Caller needs to provide their manager customer id and the associated auth credential that allows them read permissions on their linked accounts.
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `localservices_detailed_lead_reports_search_execute()` to send, or `localservices_detailed_lead_reports_search` for simplest API.

pub fn localservices_detailed_lead_reports_search_builder(
    client: &SimpleHttpClient,
    endDate_day: Option<i32>,
    endDate_month: Option<i32>,
    endDate_year: Option<i32>,
    pageSize: Option<i32>,
    pageToken: Option<&str>,
    query: Option<&str>,
    startDate_day: Option<i32>,
    startDate_month: Option<i32>,
    startDate_year: Option<i32>,
) -> Result<ClientRequestBuilder<SystemDnsResolver>, ApiError> {
    // Build URL
    let url = format!("https://localservices.googleapis.com/v1/detailedLeadReports:search",);

    // Build request
    let mut query_parts = Vec::new();
    if let Some(val) = endDate_day {
        query_parts.push(format!("endDate_day={}", val));
    }
    if let Some(val) = endDate_month {
        query_parts.push(format!("endDate_month={}", val));
    }
    if let Some(val) = endDate_year {
        query_parts.push(format!("endDate_year={}", val));
    }
    if let Some(val) = pageSize {
        query_parts.push(format!("pageSize={}", val));
    }
    if let Some(val) = pageToken {
        query_parts.push(format!("pageToken={}", val));
    }
    if let Some(val) = query {
        query_parts.push(format!("query={}", val));
    }
    if let Some(val) = startDate_day {
        query_parts.push(format!("startDate_day={}", val));
    }
    if let Some(val) = startDate_month {
        query_parts.push(format!("startDate_month={}", val));
    }
    if let Some(val) = startDate_year {
        query_parts.push(format!("startDate_year={}", val));
    }

    let url_with_query = if query_parts.is_empty() {
        url
    } else {
        format!("{}?{}", url, query_parts.join("&"))
    };

    let builder = client
        .get(&url_with_query)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    Ok(builder)
}

/// GET v1/detailedLeadReports:search
/// Get detailed lead reports containing leads that have been received by all linked GLS accounts. Caller needs to provide their manager customer id and the associated auth credential that allows them read permissions on their linked accounts.
///
/// Takes a `ClientRequestBuilder`, builds and executes the request.
/// For customization, use `localservices_detailed_lead_reports_search_builder()` then pass to this function.
///
/// # Arguments
///
/// * `builder` - ClientRequestBuilder from localservices_detailed_lead_reports_search_builder()
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn localservices_detailed_lead_reports_search_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<
            D = Result<
                ApiResponse<GoogleAdsHomeservicesLocalservicesV1SearchDetailedLeadReportsResponse>,
                ApiError,
            >,
            P = ApiPending,
        > + Send
        + 'static,
    ApiError,
> {
    // Get SendRequestTask from builder
    let task = builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: GoogleAdsHomeservicesLocalservicesV1SearchDetailedLeadReportsResponse =
                    serde_json::from_str(&body).map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending);

    // Convert TaskIterator to StreamIterator
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// GET v1/detailedLeadReports:search
/// Get detailed lead reports containing leads that have been received by all linked GLS accounts. Caller needs to provide their manager customer id and the associated auth credential that allows them read permissions on their linked accounts.
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `localservices_detailed_lead_reports_search_builder()` + `localservices_detailed_lead_reports_search_execute()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn localservices_detailed_lead_reports_search(
    client: &SimpleHttpClient,
    endDate_day: Option<i32>,
    endDate_month: Option<i32>,
    endDate_year: Option<i32>,
    pageSize: Option<i32>,
    pageToken: Option<&str>,
    query: Option<&str>,
    startDate_day: Option<i32>,
    startDate_month: Option<i32>,
    startDate_year: Option<i32>,
) -> Result<
    impl StreamIterator<
            D = Result<
                ApiResponse<GoogleAdsHomeservicesLocalservicesV1SearchDetailedLeadReportsResponse>,
                ApiError,
            >,
            P = ApiPending,
        > + Send
        + 'static,
    ApiError,
> {
    let builder = localservices_detailed_lead_reports_search_builder(
        client,
        endDate_day,
        endDate_month,
        endDate_year,
        pageSize,
        pageToken,
        query,
        startDate_day,
        startDate_month,
        startDate_year,
    )?;
    localservices_detailed_lead_reports_search_execute(builder)
}
