//! Auto-generated API clients for gcp/workflowexecutions.
//!
//! Generated by `cargo run --bin ewe_platform gen_provider_clients`.
//! DO NOT EDIT MANUALLY.
//!
//! Feature flag: `gcp`

#![cfg(feature = "gcp")]


use crate::providers::gcp::clients::types::*;
use crate::providers::gcp::resources::*;
use foundation_core::valtron::{
    execute, BoxedSendExecutionAction, StreamIterator, StreamIteratorExt, TaskIterator,
    TaskIteratorExt,
};
use foundation_core::wire::simple_http::client::{
    body_reader, ClientRequestBuilder, DnsResolver, RequestIntro, SimpleHttpClient,
    SystemDnsResolver,
};
use foundation_db::state::resource_identifier::ResourceIdentifier;
use foundation_macros::JsonHash;
use serde::Serialize;

/// POST v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}:triggerPubsubExecution
/// Triggers a new execution using the latest revision of the given workflow by a P`ub/Sub` push notification.
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `workflowexecutions_projects_locations_workflows_trigger_pubsub_execution_execute()` to send, or `workflowexecutions_projects_locations_workflows_trigger_pubsub_execution` for simplest API.

pub fn workflowexecutions_projects_locations_workflows_trigger_pubsub_execution_builder<R>(
    client: &SimpleHttpClient<R>,
    workflow: &String,
) -> Result<ClientRequestBuilder<R>, ApiError>
where
    R: DnsResolver + Clone,
{
    // Build URL
    let endpoint_url = format!(
        "https://workflowexecutions.googleapis.com/v1/projects/{}/locations/{locationsId}/workflows/{workflowsId}:triggerPubsubExecution",
        workflow,
    );

    // Build request
    let builder = client
        .post(&endpoint_url)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    Ok(builder)
}

/// POST v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}:triggerPubsubExecution
/// Triggers a new execution using the latest revision of the given workflow by a P`ub/Sub` push notification.
///
/// Takes a `ClientRequestBuilder`, builds the request, applies valtron combinators,
/// and returns a `TaskIterator` for customization before execution.
///
/// Use this function when you need to:
/// - Wrap the task with custom valtron combinators
/// - Compose multiple tasks before execution
/// - Intercept task execution for logging or testing
///
/// For direct execution, use `workflowexecutions_projects_locations_workflows_trigger_pubsub_execution_execute()` or `workflowexecutions_projects_locations_workflows_trigger_pubsub_execution`.
///
/// # Arguments
///
/// * `builder` - A `ClientRequestBuilder`, typically from `workflowexecutions_projects_locations_workflows_trigger_pubsub_execution_builder()`
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn workflowexecutions_projects_locations_workflows_trigger_pubsub_execution_task(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<Execution>, ApiError>,
            Pending = ApiPending,
            Spawner = BoxedSendExecutionAction,
        > + Send
        + 'static,
    ApiError,
> {
    Ok(builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: Execution = serde_json::from_str(&body)
                    .map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending))
}

/// POST v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}:triggerPubsubExecution
/// Triggers a new execution using the latest revision of the given workflow by a P`ub/Sub` push notification.
///
/// Takes a `ClientRequestBuilder`, builds and executes the request,
/// and returns the parsed response via a `StreamIterator`.
///
/// For full customization, use `workflowexecutions_projects_locations_workflows_trigger_pubsub_execution_builder()` to create the builder,
/// modify it, then call this function with your customized builder.
/// For task-level control, use `workflowexecutions_projects_locations_workflows_trigger_pubsub_execution_task()`.
/// For the simplest API, use `workflowexecutions_projects_locations_workflows_trigger_pubsub_execution()`.
///
/// # Arguments
///
/// * `builder` - A `ClientRequestBuilder`, typically from `workflowexecutions_projects_locations_workflows_trigger_pubsub_execution_builder()`
///
/// # Errors
///
/// Returns an error if the request cannot be built.
/// HTTP errors during execution are returned via the StreamIterator.

pub fn workflowexecutions_projects_locations_workflows_trigger_pubsub_execution_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<Execution>, ApiError>, P = ApiPending> + Send + 'static,
    ApiError,
> {
    let task =
        workflowexecutions_projects_locations_workflows_trigger_pubsub_execution_task(builder)?;
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// Arguments for [`workflowexecutions_projects_locations_workflows_trigger_pubsub_execution`].
#[derive(Debug, Clone, Serialize, JsonHash)]
pub struct WorkflowexecutionsProjectsLocationsWorkflowsTriggerPubsubExecutionArgs {
    /// Path parameter: workflow
    pub workflow: String,
}

/// POST v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}:triggerPubsubExecution
/// Triggers a new execution using the latest revision of the given workflow by a P`ub/Sub` push notification.
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `workflowexecutions_projects_locations_workflows_trigger_pubsub_execution_builder()` + `workflowexecutions_projects_locations_workflows_trigger_pubsub_execution_execute()`.
/// For task-level control, use `workflowexecutions_projects_locations_workflows_trigger_pubsub_execution_task()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn workflowexecutions_projects_locations_workflows_trigger_pubsub_execution(
    client: &SimpleHttpClient,
    args: &WorkflowexecutionsProjectsLocationsWorkflowsTriggerPubsubExecutionArgs,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<Execution>, ApiError>, P = ApiPending> + Send + 'static,
    ApiError,
> {
    let builder = workflowexecutions_projects_locations_workflows_trigger_pubsub_execution_builder(
        client,
        &args.workflow,
    )?;
    workflowexecutions_projects_locations_workflows_trigger_pubsub_execution_execute(builder)
}

/// POST v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}:cancel
/// Cancels an execution of the given name.
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `workflowexecutions_projects_locations_workflows_executions_cancel_execute()` to send, or `workflowexecutions_projects_locations_workflows_executions_cancel` for simplest API.

pub fn workflowexecutions_projects_locations_workflows_executions_cancel_builder<R>(
    client: &SimpleHttpClient<R>,
    name: &String,
) -> Result<ClientRequestBuilder<R>, ApiError>
where
    R: DnsResolver + Clone,
{
    // Build URL
    let endpoint_url = format!(
        "https://workflowexecutions.googleapis.com/v1/projects/{}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}:cancel",
        name,
    );

    // Build request
    let builder = client
        .post(&endpoint_url)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    Ok(builder)
}

/// POST v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}:cancel
/// Cancels an execution of the given name.
///
/// Takes a `ClientRequestBuilder`, builds the request, applies valtron combinators,
/// and returns a `TaskIterator` for customization before execution.
///
/// Use this function when you need to:
/// - Wrap the task with custom valtron combinators
/// - Compose multiple tasks before execution
/// - Intercept task execution for logging or testing
///
/// For direct execution, use `workflowexecutions_projects_locations_workflows_executions_cancel_execute()` or `workflowexecutions_projects_locations_workflows_executions_cancel`.
///
/// # Arguments
///
/// * `builder` - A `ClientRequestBuilder`, typically from `workflowexecutions_projects_locations_workflows_executions_cancel_builder()`
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn workflowexecutions_projects_locations_workflows_executions_cancel_task(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<Execution>, ApiError>,
            Pending = ApiPending,
            Spawner = BoxedSendExecutionAction,
        > + Send
        + 'static,
    ApiError,
> {
    Ok(builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: Execution = serde_json::from_str(&body)
                    .map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending))
}

/// POST v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}:cancel
/// Cancels an execution of the given name.
///
/// Takes a `ClientRequestBuilder`, builds and executes the request,
/// and returns the parsed response via a `StreamIterator`.
///
/// For full customization, use `workflowexecutions_projects_locations_workflows_executions_cancel_builder()` to create the builder,
/// modify it, then call this function with your customized builder.
/// For task-level control, use `workflowexecutions_projects_locations_workflows_executions_cancel_task()`.
/// For the simplest API, use `workflowexecutions_projects_locations_workflows_executions_cancel()`.
///
/// # Arguments
///
/// * `builder` - A `ClientRequestBuilder`, typically from `workflowexecutions_projects_locations_workflows_executions_cancel_builder()`
///
/// # Errors
///
/// Returns an error if the request cannot be built.
/// HTTP errors during execution are returned via the StreamIterator.

pub fn workflowexecutions_projects_locations_workflows_executions_cancel_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<Execution>, ApiError>, P = ApiPending> + Send + 'static,
    ApiError,
> {
    let task = workflowexecutions_projects_locations_workflows_executions_cancel_task(builder)?;
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// Arguments for [`workflowexecutions_projects_locations_workflows_executions_cancel`].
#[derive(Debug, Clone, Serialize, JsonHash)]
pub struct WorkflowexecutionsProjectsLocationsWorkflowsExecutionsCancelArgs {
    /// Path parameter: name
    pub name: String,
}

/// POST v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}:cancel
/// Cancels an execution of the given name.
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `workflowexecutions_projects_locations_workflows_executions_cancel_builder()` + `workflowexecutions_projects_locations_workflows_executions_cancel_execute()`.
/// For task-level control, use `workflowexecutions_projects_locations_workflows_executions_cancel_task()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn workflowexecutions_projects_locations_workflows_executions_cancel(
    client: &SimpleHttpClient,
    args: &WorkflowexecutionsProjectsLocationsWorkflowsExecutionsCancelArgs,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<Execution>, ApiError>, P = ApiPending> + Send + 'static,
    ApiError,
> {
    let builder = workflowexecutions_projects_locations_workflows_executions_cancel_builder(
        client, &args.name,
    )?;
    workflowexecutions_projects_locations_workflows_executions_cancel_execute(builder)
}

/// POST v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions
/// Creates a new execution using the latest revision of the given workflow. For more information, see Execute a workflow.
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `workflowexecutions_projects_locations_workflows_executions_create_execute()` to send, or `workflowexecutions_projects_locations_workflows_executions_create` for simplest API.

pub fn workflowexecutions_projects_locations_workflows_executions_create_builder<R>(
    client: &SimpleHttpClient<R>,
    parent: &String,
) -> Result<ClientRequestBuilder<R>, ApiError>
where
    R: DnsResolver + Clone,
{
    // Build URL
    let endpoint_url = format!(
        "https://workflowexecutions.googleapis.com/v1/projects/{}/locations/{locationsId}/workflows/{workflowsId}/executions",
        parent,
    );

    // Build request
    let builder = client
        .post(&endpoint_url)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    Ok(builder)
}

/// POST v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions
/// Creates a new execution using the latest revision of the given workflow. For more information, see Execute a workflow.
///
/// Takes a `ClientRequestBuilder`, builds the request, applies valtron combinators,
/// and returns a `TaskIterator` for customization before execution.
///
/// Use this function when you need to:
/// - Wrap the task with custom valtron combinators
/// - Compose multiple tasks before execution
/// - Intercept task execution for logging or testing
///
/// For direct execution, use `workflowexecutions_projects_locations_workflows_executions_create_execute()` or `workflowexecutions_projects_locations_workflows_executions_create`.
///
/// # Arguments
///
/// * `builder` - A `ClientRequestBuilder`, typically from `workflowexecutions_projects_locations_workflows_executions_create_builder()`
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn workflowexecutions_projects_locations_workflows_executions_create_task(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<Execution>, ApiError>,
            Pending = ApiPending,
            Spawner = BoxedSendExecutionAction,
        > + Send
        + 'static,
    ApiError,
> {
    Ok(builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: Execution = serde_json::from_str(&body)
                    .map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending))
}

/// POST v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions
/// Creates a new execution using the latest revision of the given workflow. For more information, see Execute a workflow.
///
/// Takes a `ClientRequestBuilder`, builds and executes the request,
/// and returns the parsed response via a `StreamIterator`.
///
/// For full customization, use `workflowexecutions_projects_locations_workflows_executions_create_builder()` to create the builder,
/// modify it, then call this function with your customized builder.
/// For task-level control, use `workflowexecutions_projects_locations_workflows_executions_create_task()`.
/// For the simplest API, use `workflowexecutions_projects_locations_workflows_executions_create()`.
///
/// # Arguments
///
/// * `builder` - A `ClientRequestBuilder`, typically from `workflowexecutions_projects_locations_workflows_executions_create_builder()`
///
/// # Errors
///
/// Returns an error if the request cannot be built.
/// HTTP errors during execution are returned via the StreamIterator.

pub fn workflowexecutions_projects_locations_workflows_executions_create_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<Execution>, ApiError>, P = ApiPending> + Send + 'static,
    ApiError,
> {
    let task = workflowexecutions_projects_locations_workflows_executions_create_task(builder)?;
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// Arguments for [`workflowexecutions_projects_locations_workflows_executions_create`].
#[derive(Debug, Clone, Serialize, JsonHash)]
pub struct WorkflowexecutionsProjectsLocationsWorkflowsExecutionsCreateArgs {
    /// Path parameter: parent
    pub parent: String,
}

/// POST v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions
/// Creates a new execution using the latest revision of the given workflow. For more information, see Execute a workflow.
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `workflowexecutions_projects_locations_workflows_executions_create_builder()` + `workflowexecutions_projects_locations_workflows_executions_create_execute()`.
/// For task-level control, use `workflowexecutions_projects_locations_workflows_executions_create_task()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn workflowexecutions_projects_locations_workflows_executions_create(
    client: &SimpleHttpClient,
    args: &WorkflowexecutionsProjectsLocationsWorkflowsExecutionsCreateArgs,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<Execution>, ApiError>, P = ApiPending> + Send + 'static,
    ApiError,
> {
    let builder = workflowexecutions_projects_locations_workflows_executions_create_builder(
        client,
        &args.parent,
    )?;
    workflowexecutions_projects_locations_workflows_executions_create_execute(builder)
}

/// POST v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}:deleteExecutionHistory
/// Deletes all step entries for an execution.
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `workflowexecutions_projects_locations_workflows_executions_delete_execution_history_execute()` to send, or `workflowexecutions_projects_locations_workflows_executions_delete_execution_history` for simplest API.

pub fn workflowexecutions_projects_locations_workflows_executions_delete_execution_history_builder<
    R,
>(
    client: &SimpleHttpClient<R>,
    name: &String,
) -> Result<ClientRequestBuilder<R>, ApiError>
where
    R: DnsResolver + Clone,
{
    // Build URL
    let endpoint_url = format!(
        "https://workflowexecutions.googleapis.com/v1/projects/{}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}:deleteExecutionHistory",
        name,
    );

    // Build request
    let builder = client
        .post(&endpoint_url)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    Ok(builder)
}

/// POST v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}:deleteExecutionHistory
/// Deletes all step entries for an execution.
///
/// Takes a `ClientRequestBuilder`, builds the request, applies valtron combinators,
/// and returns a `TaskIterator` for customization before execution.
///
/// Use this function when you need to:
/// - Wrap the task with custom valtron combinators
/// - Compose multiple tasks before execution
/// - Intercept task execution for logging or testing
///
/// For direct execution, use `workflowexecutions_projects_locations_workflows_executions_delete_execution_history_execute()` or `workflowexecutions_projects_locations_workflows_executions_delete_execution_history`.
///
/// # Arguments
///
/// * `builder` - A `ClientRequestBuilder`, typically from `workflowexecutions_projects_locations_workflows_executions_delete_execution_history_builder()`
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn workflowexecutions_projects_locations_workflows_executions_delete_execution_history_task(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<Empty>, ApiError>,
            Pending = ApiPending,
            Spawner = BoxedSendExecutionAction,
        > + Send
        + 'static,
    ApiError,
> {
    Ok(builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: Empty = serde_json::from_str(&body)
                    .map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending))
}

/// POST v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}:deleteExecutionHistory
/// Deletes all step entries for an execution.
///
/// Takes a `ClientRequestBuilder`, builds and executes the request,
/// and returns the parsed response via a `StreamIterator`.
///
/// For full customization, use `workflowexecutions_projects_locations_workflows_executions_delete_execution_history_builder()` to create the builder,
/// modify it, then call this function with your customized builder.
/// For task-level control, use `workflowexecutions_projects_locations_workflows_executions_delete_execution_history_task()`.
/// For the simplest API, use `workflowexecutions_projects_locations_workflows_executions_delete_execution_history()`.
///
/// # Arguments
///
/// * `builder` - A `ClientRequestBuilder`, typically from `workflowexecutions_projects_locations_workflows_executions_delete_execution_history_builder()`
///
/// # Errors
///
/// Returns an error if the request cannot be built.
/// HTTP errors during execution are returned via the StreamIterator.

pub fn workflowexecutions_projects_locations_workflows_executions_delete_execution_history_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<Empty>, ApiError>, P = ApiPending> + Send + 'static,
    ApiError,
> {
    let task =
        workflowexecutions_projects_locations_workflows_executions_delete_execution_history_task(
            builder,
        )?;
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// Arguments for [`workflowexecutions_projects_locations_workflows_executions_delete_execution_history`].
#[derive(Debug, Clone, Serialize, JsonHash)]
pub struct WorkflowexecutionsProjectsLocationsWorkflowsExecutionsDeleteExecutionHistoryArgs {
    /// Path parameter: name
    pub name: String,
}

/// POST v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}:deleteExecutionHistory
/// Deletes all step entries for an execution.
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `workflowexecutions_projects_locations_workflows_executions_delete_execution_history_builder()` + `workflowexecutions_projects_locations_workflows_executions_delete_execution_history_execute()`.
/// For task-level control, use `workflowexecutions_projects_locations_workflows_executions_delete_execution_history_task()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn workflowexecutions_projects_locations_workflows_executions_delete_execution_history(
    client: &SimpleHttpClient,
    args: &WorkflowexecutionsProjectsLocationsWorkflowsExecutionsDeleteExecutionHistoryArgs,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<Empty>, ApiError>, P = ApiPending> + Send + 'static,
    ApiError,
> {
    let builder = workflowexecutions_projects_locations_workflows_executions_delete_execution_history_builder(client, &args.name)?;
    workflowexecutions_projects_locations_workflows_executions_delete_execution_history_execute(
        builder,
    )
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}:exportData
/// Returns all metadata stored about an execution, excluding most data that is already accessible using other API methods.
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `workflowexecutions_projects_locations_workflows_executions_export_data_execute()` to send, or `workflowexecutions_projects_locations_workflows_executions_export_data` for simplest API.

pub fn workflowexecutions_projects_locations_workflows_executions_export_data_builder<R>(
    client: &SimpleHttpClient<R>,
    name: &String,
) -> Result<ClientRequestBuilder<R>, ApiError>
where
    R: DnsResolver + Clone,
{
    // Build URL
    let endpoint_url = format!(
        "https://workflowexecutions.googleapis.com/v1/projects/{}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}:exportData",
        name,
    );

    // Build request
    let builder = client
        .get(&endpoint_url)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    Ok(builder)
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}:exportData
/// Returns all metadata stored about an execution, excluding most data that is already accessible using other API methods.
///
/// Takes a `ClientRequestBuilder`, builds the request, applies valtron combinators,
/// and returns a `TaskIterator` for customization before execution.
///
/// Use this function when you need to:
/// - Wrap the task with custom valtron combinators
/// - Compose multiple tasks before execution
/// - Intercept task execution for logging or testing
///
/// For direct execution, use `workflowexecutions_projects_locations_workflows_executions_export_data_execute()` or `workflowexecutions_projects_locations_workflows_executions_export_data`.
///
/// # Arguments
///
/// * `builder` - A `ClientRequestBuilder`, typically from `workflowexecutions_projects_locations_workflows_executions_export_data_builder()`
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn workflowexecutions_projects_locations_workflows_executions_export_data_task(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<ExportDataResponse>, ApiError>,
            Pending = ApiPending,
            Spawner = BoxedSendExecutionAction,
        > + Send
        + 'static,
    ApiError,
> {
    Ok(builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: ExportDataResponse = serde_json::from_str(&body)
                    .map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending))
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}:exportData
/// Returns all metadata stored about an execution, excluding most data that is already accessible using other API methods.
///
/// Takes a `ClientRequestBuilder`, builds and executes the request,
/// and returns the parsed response via a `StreamIterator`.
///
/// For full customization, use `workflowexecutions_projects_locations_workflows_executions_export_data_builder()` to create the builder,
/// modify it, then call this function with your customized builder.
/// For task-level control, use `workflowexecutions_projects_locations_workflows_executions_export_data_task()`.
/// For the simplest API, use `workflowexecutions_projects_locations_workflows_executions_export_data()`.
///
/// # Arguments
///
/// * `builder` - A `ClientRequestBuilder`, typically from `workflowexecutions_projects_locations_workflows_executions_export_data_builder()`
///
/// # Errors
///
/// Returns an error if the request cannot be built.
/// HTTP errors during execution are returned via the StreamIterator.

pub fn workflowexecutions_projects_locations_workflows_executions_export_data_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<ExportDataResponse>, ApiError>, P = ApiPending>
        + Send
        + 'static,
    ApiError,
> {
    let task =
        workflowexecutions_projects_locations_workflows_executions_export_data_task(builder)?;
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// Arguments for [`workflowexecutions_projects_locations_workflows_executions_export_data`].
#[derive(Debug, Clone, Serialize, JsonHash)]
pub struct WorkflowexecutionsProjectsLocationsWorkflowsExecutionsExportDataArgs {
    /// Path parameter: name
    pub name: String,
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}:exportData
/// Returns all metadata stored about an execution, excluding most data that is already accessible using other API methods.
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `workflowexecutions_projects_locations_workflows_executions_export_data_builder()` + `workflowexecutions_projects_locations_workflows_executions_export_data_execute()`.
/// For task-level control, use `workflowexecutions_projects_locations_workflows_executions_export_data_task()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn workflowexecutions_projects_locations_workflows_executions_export_data(
    client: &SimpleHttpClient,
    args: &WorkflowexecutionsProjectsLocationsWorkflowsExecutionsExportDataArgs,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<ExportDataResponse>, ApiError>, P = ApiPending>
        + Send
        + 'static,
    ApiError,
> {
    let builder = workflowexecutions_projects_locations_workflows_executions_export_data_builder(
        client, &args.name,
    )?;
    workflowexecutions_projects_locations_workflows_executions_export_data_execute(builder)
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}
/// Returns an execution of the given name.
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `workflowexecutions_projects_locations_workflows_executions_get_execute()` to send, or `workflowexecutions_projects_locations_workflows_executions_get` for simplest API.

pub fn workflowexecutions_projects_locations_workflows_executions_get_builder<R>(
    client: &SimpleHttpClient<R>,
    name: &String,
    view: &Option<String>,
) -> Result<ClientRequestBuilder<R>, ApiError>
where
    R: DnsResolver + Clone,
{
    // Build URL
    let endpoint_url = format!(
        "https://workflowexecutions.googleapis.com/v1/projects/{}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}",
        name,
    );

    // Build request
    let mut query_parts = Vec::new();
    if let Some(val) = view.as_ref() {
        query_parts.push(format!("view={}", val));
    }

    let url_with_query = if query_parts.is_empty() {
        endpoint_url
    } else {
        format!("{}?{}", endpoint_url, query_parts.join("&"))
    };

    let builder = client
        .get(&url_with_query)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    Ok(builder)
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}
/// Returns an execution of the given name.
///
/// Takes a `ClientRequestBuilder`, builds the request, applies valtron combinators,
/// and returns a `TaskIterator` for customization before execution.
///
/// Use this function when you need to:
/// - Wrap the task with custom valtron combinators
/// - Compose multiple tasks before execution
/// - Intercept task execution for logging or testing
///
/// For direct execution, use `workflowexecutions_projects_locations_workflows_executions_get_execute()` or `workflowexecutions_projects_locations_workflows_executions_get`.
///
/// # Arguments
///
/// * `builder` - A `ClientRequestBuilder`, typically from `workflowexecutions_projects_locations_workflows_executions_get_builder()`
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn workflowexecutions_projects_locations_workflows_executions_get_task(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<Execution>, ApiError>,
            Pending = ApiPending,
            Spawner = BoxedSendExecutionAction,
        > + Send
        + 'static,
    ApiError,
> {
    Ok(builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: Execution = serde_json::from_str(&body)
                    .map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending))
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}
/// Returns an execution of the given name.
///
/// Takes a `ClientRequestBuilder`, builds and executes the request,
/// and returns the parsed response via a `StreamIterator`.
///
/// For full customization, use `workflowexecutions_projects_locations_workflows_executions_get_builder()` to create the builder,
/// modify it, then call this function with your customized builder.
/// For task-level control, use `workflowexecutions_projects_locations_workflows_executions_get_task()`.
/// For the simplest API, use `workflowexecutions_projects_locations_workflows_executions_get()`.
///
/// # Arguments
///
/// * `builder` - A `ClientRequestBuilder`, typically from `workflowexecutions_projects_locations_workflows_executions_get_builder()`
///
/// # Errors
///
/// Returns an error if the request cannot be built.
/// HTTP errors during execution are returned via the StreamIterator.

pub fn workflowexecutions_projects_locations_workflows_executions_get_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<Execution>, ApiError>, P = ApiPending> + Send + 'static,
    ApiError,
> {
    let task = workflowexecutions_projects_locations_workflows_executions_get_task(builder)?;
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// Arguments for [`workflowexecutions_projects_locations_workflows_executions_get`].
#[derive(Debug, Clone, Serialize, JsonHash)]
pub struct WorkflowexecutionsProjectsLocationsWorkflowsExecutionsGetArgs {
    /// Path parameter: name
    pub name: String,
    /// Query parameter: view
    pub view: Option<String>,
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}
/// Returns an execution of the given name.
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `workflowexecutions_projects_locations_workflows_executions_get_builder()` + `workflowexecutions_projects_locations_workflows_executions_get_execute()`.
/// For task-level control, use `workflowexecutions_projects_locations_workflows_executions_get_task()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn workflowexecutions_projects_locations_workflows_executions_get(
    client: &SimpleHttpClient,
    args: &WorkflowexecutionsProjectsLocationsWorkflowsExecutionsGetArgs,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<Execution>, ApiError>, P = ApiPending> + Send + 'static,
    ApiError,
> {
    let builder = workflowexecutions_projects_locations_workflows_executions_get_builder(
        client, &args.name, &args.view,
    )?;
    workflowexecutions_projects_locations_workflows_executions_get_execute(builder)
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions
/// Returns a list of executions which belong to the workflow with the given name. The method returns executions of all workflow revisions. Returned executions are ordered by their start time (newest first).
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `workflowexecutions_projects_locations_workflows_executions_list_execute()` to send, or `workflowexecutions_projects_locations_workflows_executions_list` for simplest API.

pub fn workflowexecutions_projects_locations_workflows_executions_list_builder<R>(
    client: &SimpleHttpClient<R>,
    parent: &String,
    filter: &Option<String>,
    orderBy: &Option<String>,
    pageSize: &Option<String>,
    pageToken: &Option<String>,
    view: &Option<String>,
) -> Result<ClientRequestBuilder<R>, ApiError>
where
    R: DnsResolver + Clone,
{
    // Build URL
    let endpoint_url = format!(
        "https://workflowexecutions.googleapis.com/v1/projects/{}/locations/{locationsId}/workflows/{workflowsId}/executions",
        parent,
    );

    // Build request
    let mut query_parts = Vec::new();
    if let Some(val) = filter.as_ref() {
        query_parts.push(format!("filter={}", val));
    }
    if let Some(val) = orderBy.as_ref() {
        query_parts.push(format!("orderBy={}", val));
    }
    if let Some(val) = pageSize.as_ref() {
        query_parts.push(format!("pageSize={}", val));
    }
    if let Some(val) = pageToken.as_ref() {
        query_parts.push(format!("pageToken={}", val));
    }
    if let Some(val) = view.as_ref() {
        query_parts.push(format!("view={}", val));
    }

    let url_with_query = if query_parts.is_empty() {
        endpoint_url
    } else {
        format!("{}?{}", endpoint_url, query_parts.join("&"))
    };

    let builder = client
        .get(&url_with_query)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    Ok(builder)
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions
/// Returns a list of executions which belong to the workflow with the given name. The method returns executions of all workflow revisions. Returned executions are ordered by their start time (newest first).
///
/// Takes a `ClientRequestBuilder`, builds the request, applies valtron combinators,
/// and returns a `TaskIterator` for customization before execution.
///
/// Use this function when you need to:
/// - Wrap the task with custom valtron combinators
/// - Compose multiple tasks before execution
/// - Intercept task execution for logging or testing
///
/// For direct execution, use `workflowexecutions_projects_locations_workflows_executions_list_execute()` or `workflowexecutions_projects_locations_workflows_executions_list`.
///
/// # Arguments
///
/// * `builder` - A `ClientRequestBuilder`, typically from `workflowexecutions_projects_locations_workflows_executions_list_builder()`
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn workflowexecutions_projects_locations_workflows_executions_list_task(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<ListExecutionsResponse>, ApiError>,
            Pending = ApiPending,
            Spawner = BoxedSendExecutionAction,
        > + Send
        + 'static,
    ApiError,
> {
    Ok(builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: ListExecutionsResponse = serde_json::from_str(&body)
                    .map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending))
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions
/// Returns a list of executions which belong to the workflow with the given name. The method returns executions of all workflow revisions. Returned executions are ordered by their start time (newest first).
///
/// Takes a `ClientRequestBuilder`, builds and executes the request,
/// and returns the parsed response via a `StreamIterator`.
///
/// For full customization, use `workflowexecutions_projects_locations_workflows_executions_list_builder()` to create the builder,
/// modify it, then call this function with your customized builder.
/// For task-level control, use `workflowexecutions_projects_locations_workflows_executions_list_task()`.
/// For the simplest API, use `workflowexecutions_projects_locations_workflows_executions_list()`.
///
/// # Arguments
///
/// * `builder` - A `ClientRequestBuilder`, typically from `workflowexecutions_projects_locations_workflows_executions_list_builder()`
///
/// # Errors
///
/// Returns an error if the request cannot be built.
/// HTTP errors during execution are returned via the StreamIterator.

pub fn workflowexecutions_projects_locations_workflows_executions_list_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<ListExecutionsResponse>, ApiError>, P = ApiPending>
        + Send
        + 'static,
    ApiError,
> {
    let task = workflowexecutions_projects_locations_workflows_executions_list_task(builder)?;
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// Arguments for [`workflowexecutions_projects_locations_workflows_executions_list`].
#[derive(Debug, Clone, Serialize, JsonHash)]
pub struct WorkflowexecutionsProjectsLocationsWorkflowsExecutionsListArgs {
    /// Path parameter: parent
    pub parent: String,
    /// Query parameter: filter
    pub filter: Option<String>,
    /// Query parameter: orderBy
    pub orderBy: Option<String>,
    /// Query parameter: pageSize
    pub pageSize: Option<String>,
    /// Query parameter: pageToken
    pub pageToken: Option<String>,
    /// Query parameter: view
    pub view: Option<String>,
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions
/// Returns a list of executions which belong to the workflow with the given name. The method returns executions of all workflow revisions. Returned executions are ordered by their start time (newest first).
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `workflowexecutions_projects_locations_workflows_executions_list_builder()` + `workflowexecutions_projects_locations_workflows_executions_list_execute()`.
/// For task-level control, use `workflowexecutions_projects_locations_workflows_executions_list_task()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn workflowexecutions_projects_locations_workflows_executions_list(
    client: &SimpleHttpClient,
    args: &WorkflowexecutionsProjectsLocationsWorkflowsExecutionsListArgs,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<ListExecutionsResponse>, ApiError>, P = ApiPending>
        + Send
        + 'static,
    ApiError,
> {
    let builder = workflowexecutions_projects_locations_workflows_executions_list_builder(
        client,
        &args.parent,
        &args.filter,
        &args.orderBy,
        &args.pageSize,
        &args.pageToken,
        &args.view,
    )?;
    workflowexecutions_projects_locations_workflows_executions_list_execute(builder)
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}/callbacks
/// Returns a list of active callbacks that belong to the execution with the given name. The returned callbacks are ordered by callback ID.
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `workflowexecutions_projects_locations_workflows_executions_callbacks_list_execute()` to send, or `workflowexecutions_projects_locations_workflows_executions_callbacks_list` for simplest API.

pub fn workflowexecutions_projects_locations_workflows_executions_callbacks_list_builder<R>(
    client: &SimpleHttpClient<R>,
    parent: &String,
    pageSize: &Option<String>,
    pageToken: &Option<String>,
) -> Result<ClientRequestBuilder<R>, ApiError>
where
    R: DnsResolver + Clone,
{
    // Build URL
    let endpoint_url = format!(
        "https://workflowexecutions.googleapis.com/v1/projects/{}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}/callbacks",
        parent,
    );

    // Build request
    let mut query_parts = Vec::new();
    if let Some(val) = pageSize.as_ref() {
        query_parts.push(format!("pageSize={}", val));
    }
    if let Some(val) = pageToken.as_ref() {
        query_parts.push(format!("pageToken={}", val));
    }

    let url_with_query = if query_parts.is_empty() {
        endpoint_url
    } else {
        format!("{}?{}", endpoint_url, query_parts.join("&"))
    };

    let builder = client
        .get(&url_with_query)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    Ok(builder)
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}/callbacks
/// Returns a list of active callbacks that belong to the execution with the given name. The returned callbacks are ordered by callback ID.
///
/// Takes a `ClientRequestBuilder`, builds the request, applies valtron combinators,
/// and returns a `TaskIterator` for customization before execution.
///
/// Use this function when you need to:
/// - Wrap the task with custom valtron combinators
/// - Compose multiple tasks before execution
/// - Intercept task execution for logging or testing
///
/// For direct execution, use `workflowexecutions_projects_locations_workflows_executions_callbacks_list_execute()` or `workflowexecutions_projects_locations_workflows_executions_callbacks_list`.
///
/// # Arguments
///
/// * `builder` - A `ClientRequestBuilder`, typically from `workflowexecutions_projects_locations_workflows_executions_callbacks_list_builder()`
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn workflowexecutions_projects_locations_workflows_executions_callbacks_list_task(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<ListCallbacksResponse>, ApiError>,
            Pending = ApiPending,
            Spawner = BoxedSendExecutionAction,
        > + Send
        + 'static,
    ApiError,
> {
    Ok(builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: ListCallbacksResponse = serde_json::from_str(&body)
                    .map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending))
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}/callbacks
/// Returns a list of active callbacks that belong to the execution with the given name. The returned callbacks are ordered by callback ID.
///
/// Takes a `ClientRequestBuilder`, builds and executes the request,
/// and returns the parsed response via a `StreamIterator`.
///
/// For full customization, use `workflowexecutions_projects_locations_workflows_executions_callbacks_list_builder()` to create the builder,
/// modify it, then call this function with your customized builder.
/// For task-level control, use `workflowexecutions_projects_locations_workflows_executions_callbacks_list_task()`.
/// For the simplest API, use `workflowexecutions_projects_locations_workflows_executions_callbacks_list()`.
///
/// # Arguments
///
/// * `builder` - A `ClientRequestBuilder`, typically from `workflowexecutions_projects_locations_workflows_executions_callbacks_list_builder()`
///
/// # Errors
///
/// Returns an error if the request cannot be built.
/// HTTP errors during execution are returned via the StreamIterator.

pub fn workflowexecutions_projects_locations_workflows_executions_callbacks_list_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<ListCallbacksResponse>, ApiError>, P = ApiPending>
        + Send
        + 'static,
    ApiError,
> {
    let task =
        workflowexecutions_projects_locations_workflows_executions_callbacks_list_task(builder)?;
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// Arguments for [`workflowexecutions_projects_locations_workflows_executions_callbacks_list`].
#[derive(Debug, Clone, Serialize, JsonHash)]
pub struct WorkflowexecutionsProjectsLocationsWorkflowsExecutionsCallbacksListArgs {
    /// Path parameter: parent
    pub parent: String,
    /// Query parameter: pageSize
    pub pageSize: Option<String>,
    /// Query parameter: pageToken
    pub pageToken: Option<String>,
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}/callbacks
/// Returns a list of active callbacks that belong to the execution with the given name. The returned callbacks are ordered by callback ID.
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `workflowexecutions_projects_locations_workflows_executions_callbacks_list_builder()` + `workflowexecutions_projects_locations_workflows_executions_callbacks_list_execute()`.
/// For task-level control, use `workflowexecutions_projects_locations_workflows_executions_callbacks_list_task()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn workflowexecutions_projects_locations_workflows_executions_callbacks_list(
    client: &SimpleHttpClient,
    args: &WorkflowexecutionsProjectsLocationsWorkflowsExecutionsCallbacksListArgs,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<ListCallbacksResponse>, ApiError>, P = ApiPending>
        + Send
        + 'static,
    ApiError,
> {
    let builder =
        workflowexecutions_projects_locations_workflows_executions_callbacks_list_builder(
            client,
            &args.parent,
            &args.pageSize,
            &args.pageToken,
        )?;
    workflowexecutions_projects_locations_workflows_executions_callbacks_list_execute(builder)
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}/stepEntries/{stepEntriesId}
/// Gets a step entry.
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `workflowexecutions_projects_locations_workflows_executions_step_entries_get_execute()` to send, or `workflowexecutions_projects_locations_workflows_executions_step_entries_get` for simplest API.

pub fn workflowexecutions_projects_locations_workflows_executions_step_entries_get_builder<R>(
    client: &SimpleHttpClient<R>,
    name: &String,
    view: &Option<String>,
) -> Result<ClientRequestBuilder<R>, ApiError>
where
    R: DnsResolver + Clone,
{
    // Build URL
    let endpoint_url = format!(
        "https://workflowexecutions.googleapis.com/v1/projects/{}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}/stepEntries/{stepEntriesId}",
        name,
    );

    // Build request
    let mut query_parts = Vec::new();
    if let Some(val) = view.as_ref() {
        query_parts.push(format!("view={}", val));
    }

    let url_with_query = if query_parts.is_empty() {
        endpoint_url
    } else {
        format!("{}?{}", endpoint_url, query_parts.join("&"))
    };

    let builder = client
        .get(&url_with_query)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    Ok(builder)
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}/stepEntries/{stepEntriesId}
/// Gets a step entry.
///
/// Takes a `ClientRequestBuilder`, builds the request, applies valtron combinators,
/// and returns a `TaskIterator` for customization before execution.
///
/// Use this function when you need to:
/// - Wrap the task with custom valtron combinators
/// - Compose multiple tasks before execution
/// - Intercept task execution for logging or testing
///
/// For direct execution, use `workflowexecutions_projects_locations_workflows_executions_step_entries_get_execute()` or `workflowexecutions_projects_locations_workflows_executions_step_entries_get`.
///
/// # Arguments
///
/// * `builder` - A `ClientRequestBuilder`, typically from `workflowexecutions_projects_locations_workflows_executions_step_entries_get_builder()`
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn workflowexecutions_projects_locations_workflows_executions_step_entries_get_task(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<StepEntry>, ApiError>,
            Pending = ApiPending,
            Spawner = BoxedSendExecutionAction,
        > + Send
        + 'static,
    ApiError,
> {
    Ok(builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: StepEntry = serde_json::from_str(&body)
                    .map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending))
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}/stepEntries/{stepEntriesId}
/// Gets a step entry.
///
/// Takes a `ClientRequestBuilder`, builds and executes the request,
/// and returns the parsed response via a `StreamIterator`.
///
/// For full customization, use `workflowexecutions_projects_locations_workflows_executions_step_entries_get_builder()` to create the builder,
/// modify it, then call this function with your customized builder.
/// For task-level control, use `workflowexecutions_projects_locations_workflows_executions_step_entries_get_task()`.
/// For the simplest API, use `workflowexecutions_projects_locations_workflows_executions_step_entries_get()`.
///
/// # Arguments
///
/// * `builder` - A `ClientRequestBuilder`, typically from `workflowexecutions_projects_locations_workflows_executions_step_entries_get_builder()`
///
/// # Errors
///
/// Returns an error if the request cannot be built.
/// HTTP errors during execution are returned via the StreamIterator.

pub fn workflowexecutions_projects_locations_workflows_executions_step_entries_get_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<StepEntry>, ApiError>, P = ApiPending> + Send + 'static,
    ApiError,
> {
    let task =
        workflowexecutions_projects_locations_workflows_executions_step_entries_get_task(builder)?;
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// Arguments for [`workflowexecutions_projects_locations_workflows_executions_step_entries_get`].
#[derive(Debug, Clone, Serialize, JsonHash)]
pub struct WorkflowexecutionsProjectsLocationsWorkflowsExecutionsStepEntriesGetArgs {
    /// Path parameter: name
    pub name: String,
    /// Query parameter: view
    pub view: Option<String>,
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}/stepEntries/{stepEntriesId}
/// Gets a step entry.
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `workflowexecutions_projects_locations_workflows_executions_step_entries_get_builder()` + `workflowexecutions_projects_locations_workflows_executions_step_entries_get_execute()`.
/// For task-level control, use `workflowexecutions_projects_locations_workflows_executions_step_entries_get_task()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn workflowexecutions_projects_locations_workflows_executions_step_entries_get(
    client: &SimpleHttpClient,
    args: &WorkflowexecutionsProjectsLocationsWorkflowsExecutionsStepEntriesGetArgs,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<StepEntry>, ApiError>, P = ApiPending> + Send + 'static,
    ApiError,
> {
    let builder =
        workflowexecutions_projects_locations_workflows_executions_step_entries_get_builder(
            client, &args.name, &args.view,
        )?;
    workflowexecutions_projects_locations_workflows_executions_step_entries_get_execute(builder)
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}/stepEntries
/// Lists step entries for the corresponding workflow execution. Returned entries are ordered by their create_time.
///
/// Returns `ClientRequestBuilder` for customization.
/// Use `workflowexecutions_projects_locations_workflows_executions_step_entries_list_execute()` to send, or `workflowexecutions_projects_locations_workflows_executions_step_entries_list` for simplest API.

pub fn workflowexecutions_projects_locations_workflows_executions_step_entries_list_builder<R>(
    client: &SimpleHttpClient<R>,
    parent: &String,
    filter: &Option<String>,
    orderBy: &Option<String>,
    pageSize: &Option<String>,
    pageToken: &Option<String>,
    skip: &Option<String>,
    view: &Option<String>,
) -> Result<ClientRequestBuilder<R>, ApiError>
where
    R: DnsResolver + Clone,
{
    // Build URL
    let endpoint_url = format!(
        "https://workflowexecutions.googleapis.com/v1/projects/{}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}/stepEntries",
        parent,
    );

    // Build request
    let mut query_parts = Vec::new();
    if let Some(val) = filter.as_ref() {
        query_parts.push(format!("filter={}", val));
    }
    if let Some(val) = orderBy.as_ref() {
        query_parts.push(format!("orderBy={}", val));
    }
    if let Some(val) = pageSize.as_ref() {
        query_parts.push(format!("pageSize={}", val));
    }
    if let Some(val) = pageToken.as_ref() {
        query_parts.push(format!("pageToken={}", val));
    }
    if let Some(val) = skip.as_ref() {
        query_parts.push(format!("skip={}", val));
    }
    if let Some(val) = view.as_ref() {
        query_parts.push(format!("view={}", val));
    }

    let url_with_query = if query_parts.is_empty() {
        endpoint_url
    } else {
        format!("{}?{}", endpoint_url, query_parts.join("&"))
    };

    let builder = client
        .get(&url_with_query)
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?;

    Ok(builder)
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}/stepEntries
/// Lists step entries for the corresponding workflow execution. Returned entries are ordered by their create_time.
///
/// Takes a `ClientRequestBuilder`, builds the request, applies valtron combinators,
/// and returns a `TaskIterator` for customization before execution.
///
/// Use this function when you need to:
/// - Wrap the task with custom valtron combinators
/// - Compose multiple tasks before execution
/// - Intercept task execution for logging or testing
///
/// For direct execution, use `workflowexecutions_projects_locations_workflows_executions_step_entries_list_execute()` or `workflowexecutions_projects_locations_workflows_executions_step_entries_list`.
///
/// # Arguments
///
/// * `builder` - A `ClientRequestBuilder`, typically from `workflowexecutions_projects_locations_workflows_executions_step_entries_list_builder()`
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn workflowexecutions_projects_locations_workflows_executions_step_entries_list_task(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl TaskIterator<
            Ready = Result<ApiResponse<ListStepEntriesResponse>, ApiError>,
            Pending = ApiPending,
            Spawner = BoxedSendExecutionAction,
        > + Send
        + 'static,
    ApiError,
> {
    Ok(builder
        .build_send_request()
        .map_err(|e| ApiError::RequestBuildFailed(e.to_string()))?
        .map_ready(|intro| match intro {
            RequestIntro::Success {
                stream,
                intro,
                headers,
                ..
            } => {
                let status_code: usize = intro.0.into();

                if status_code < 200 || status_code >= 300 {
                    // Capture body for error parsing
                    let body = body_reader::collect_string(stream);
                    // Try to parse as structured API error
                    if let Ok(error_body) = serde_json::from_str::<ApiErrorBody>(&body) {
                        return Err(ApiError::ApiError(error_body.error));
                    }
                    // Fall back to raw HTTP status error
                    return Err(ApiError::HttpStatus {
                        code: status_code as u16,
                        headers: headers.clone(),
                        body: Some(body),
                    });
                }

                let body = body_reader::collect_string(stream);
                let parsed: ListStepEntriesResponse = serde_json::from_str(&body)
                    .map_err(|e| ApiError::ParseFailed(e.to_string()))?;

                Ok(ApiResponse {
                    status: status_code as u16,
                    headers: headers.clone(),
                    body: parsed,
                })
            }
            RequestIntro::Failed(e) => Err(ApiError::RequestSendFailed(e.to_string())),
        })
        .map_pending(|_| ApiPending::Sending))
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}/stepEntries
/// Lists step entries for the corresponding workflow execution. Returned entries are ordered by their create_time.
///
/// Takes a `ClientRequestBuilder`, builds and executes the request,
/// and returns the parsed response via a `StreamIterator`.
///
/// For full customization, use `workflowexecutions_projects_locations_workflows_executions_step_entries_list_builder()` to create the builder,
/// modify it, then call this function with your customized builder.
/// For task-level control, use `workflowexecutions_projects_locations_workflows_executions_step_entries_list_task()`.
/// For the simplest API, use `workflowexecutions_projects_locations_workflows_executions_step_entries_list()`.
///
/// # Arguments
///
/// * `builder` - A `ClientRequestBuilder`, typically from `workflowexecutions_projects_locations_workflows_executions_step_entries_list_builder()`
///
/// # Errors
///
/// Returns an error if the request cannot be built.
/// HTTP errors during execution are returned via the StreamIterator.

pub fn workflowexecutions_projects_locations_workflows_executions_step_entries_list_execute(
    builder: ClientRequestBuilder<SystemDnsResolver>,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<ListStepEntriesResponse>, ApiError>, P = ApiPending>
        + Send
        + 'static,
    ApiError,
> {
    let task =
        workflowexecutions_projects_locations_workflows_executions_step_entries_list_task(builder)?;
    execute(task, None).map_err(|e| ApiError::RequestBuildFailed(e.to_string()))
}

/// Arguments for [`workflowexecutions_projects_locations_workflows_executions_step_entries_list`].
#[derive(Debug, Clone, Serialize, JsonHash)]
pub struct WorkflowexecutionsProjectsLocationsWorkflowsExecutionsStepEntriesListArgs {
    /// Path parameter: parent
    pub parent: String,
    /// Query parameter: filter
    pub filter: Option<String>,
    /// Query parameter: orderBy
    pub orderBy: Option<String>,
    /// Query parameter: pageSize
    pub pageSize: Option<String>,
    /// Query parameter: pageToken
    pub pageToken: Option<String>,
    /// Query parameter: skip
    pub skip: Option<String>,
    /// Query parameter: view
    pub view: Option<String>,
}

/// GET v1/projects/{projectsId}/locations/{locationsId}/workflows/{workflowsId}/executions/{executionsId}/stepEntries
/// Lists step entries for the corresponding workflow execution. Returned entries are ordered by their create_time.
///
/// Simplest API - builds and executes the request in one call.
/// For customization, use `workflowexecutions_projects_locations_workflows_executions_step_entries_list_builder()` + `workflowexecutions_projects_locations_workflows_executions_step_entries_list_execute()`.
/// For task-level control, use `workflowexecutions_projects_locations_workflows_executions_step_entries_list_task()`.
///
/// # Errors
///
/// Returns an error if the request cannot be built.

pub fn workflowexecutions_projects_locations_workflows_executions_step_entries_list(
    client: &SimpleHttpClient,
    args: &WorkflowexecutionsProjectsLocationsWorkflowsExecutionsStepEntriesListArgs,
) -> Result<
    impl StreamIterator<D = Result<ApiResponse<ListStepEntriesResponse>, ApiError>, P = ApiPending>
        + Send
        + 'static,
    ApiError,
> {
    let builder =
        workflowexecutions_projects_locations_workflows_executions_step_entries_list_builder(
            client,
            &args.parent,
            &args.filter,
            &args.orderBy,
            &args.pageSize,
            &args.pageToken,
            &args.skip,
            &args.view,
        )?;
    workflowexecutions_projects_locations_workflows_executions_step_entries_list_execute(builder)
}

// =============================================================================
// ResourceIdentifier implementation for Execution
// =============================================================================

/// ResourceIdentifier implementation for Execution with WorkflowexecutionsProjectsLocationsWorkflowsTriggerPubsubExecutionArgs input.
///
/// WHY: Enables automatic state tracking via StoreStateIdentifierTask.
///
/// HOW: Computes resource ID from input path parameters.
impl ResourceIdentifier<WorkflowexecutionsProjectsLocationsWorkflowsTriggerPubsubExecutionArgs>
    for Execution
{
    fn generate_resource_id(
        &self,
        input: &WorkflowexecutionsProjectsLocationsWorkflowsTriggerPubsubExecutionArgs,
    ) -> String {
        format!("gcp::workflowexecutions::Execution/{}", input.workflow)
    }

    fn resource_kind(&self) -> &'static str {
        "gcp::workflowexecutions::Execution"
    }

    fn provider(&self) -> &'static str {
        "gcp"
    }
}

// =============================================================================
// ResourceIdentifier implementation for Execution
// =============================================================================

/// ResourceIdentifier implementation for Execution with WorkflowexecutionsProjectsLocationsWorkflowsExecutionsCancelArgs input.
///
/// WHY: Enables automatic state tracking via StoreStateIdentifierTask.
///
/// HOW: Computes resource ID from input path parameters.
impl ResourceIdentifier<WorkflowexecutionsProjectsLocationsWorkflowsExecutionsCancelArgs>
    for Execution
{
    fn generate_resource_id(
        &self,
        input: &WorkflowexecutionsProjectsLocationsWorkflowsExecutionsCancelArgs,
    ) -> String {
        format!("gcp::workflowexecutions::Execution/{}", input.name)
    }

    fn resource_kind(&self) -> &'static str {
        "gcp::workflowexecutions::Execution"
    }

    fn provider(&self) -> &'static str {
        "gcp"
    }
}

// =============================================================================
// ResourceIdentifier implementation for Execution
// =============================================================================

/// ResourceIdentifier implementation for Execution with WorkflowexecutionsProjectsLocationsWorkflowsExecutionsCreateArgs input.
///
/// WHY: Enables automatic state tracking via StoreStateIdentifierTask.
///
/// HOW: Computes resource ID from input path parameters.
impl ResourceIdentifier<WorkflowexecutionsProjectsLocationsWorkflowsExecutionsCreateArgs>
    for Execution
{
    fn generate_resource_id(
        &self,
        input: &WorkflowexecutionsProjectsLocationsWorkflowsExecutionsCreateArgs,
    ) -> String {
        format!("gcp::workflowexecutions::Execution/{}", input.parent)
    }

    fn resource_kind(&self) -> &'static str {
        "gcp::workflowexecutions::Execution"
    }

    fn provider(&self) -> &'static str {
        "gcp"
    }
}

// =============================================================================
// ResourceIdentifier implementation for Empty
// =============================================================================

/// ResourceIdentifier implementation for Empty with WorkflowexecutionsProjectsLocationsWorkflowsExecutionsDeleteExecutionHistoryArgs input.
///
/// WHY: Enables automatic state tracking via StoreStateIdentifierTask.
///
/// HOW: Computes resource ID from input path parameters.
impl
    ResourceIdentifier<
        WorkflowexecutionsProjectsLocationsWorkflowsExecutionsDeleteExecutionHistoryArgs,
    > for Empty
{
    fn generate_resource_id(
        &self,
        input: &WorkflowexecutionsProjectsLocationsWorkflowsExecutionsDeleteExecutionHistoryArgs,
    ) -> String {
        format!("gcp::workflowexecutions::Empty/{}", input.name)
    }

    fn resource_kind(&self) -> &'static str {
        "gcp::workflowexecutions::Empty"
    }

    fn provider(&self) -> &'static str {
        "gcp"
    }
}

// =============================================================================
// ResourceIdentifier implementation for ExportDataResponse
// =============================================================================

/// ResourceIdentifier implementation for ExportDataResponse with WorkflowexecutionsProjectsLocationsWorkflowsExecutionsExportDataArgs input.
///
/// WHY: Enables automatic state tracking via StoreStateIdentifierTask.
///
/// HOW: Computes resource ID from input path parameters.
impl ResourceIdentifier<WorkflowexecutionsProjectsLocationsWorkflowsExecutionsExportDataArgs>
    for ExportDataResponse
{
    fn generate_resource_id(
        &self,
        input: &WorkflowexecutionsProjectsLocationsWorkflowsExecutionsExportDataArgs,
    ) -> String {
        format!("gcp::workflowexecutions::ExportDataResponse/{}", input.name)
    }

    fn resource_kind(&self) -> &'static str {
        "gcp::workflowexecutions::ExportDataResponse"
    }

    fn provider(&self) -> &'static str {
        "gcp"
    }
}

// =============================================================================
// ResourceIdentifier implementation for Execution
// =============================================================================

/// ResourceIdentifier implementation for Execution with WorkflowexecutionsProjectsLocationsWorkflowsExecutionsGetArgs input.
///
/// WHY: Enables automatic state tracking via StoreStateIdentifierTask.
///
/// HOW: Computes resource ID from input path parameters.
impl ResourceIdentifier<WorkflowexecutionsProjectsLocationsWorkflowsExecutionsGetArgs>
    for Execution
{
    fn generate_resource_id(
        &self,
        input: &WorkflowexecutionsProjectsLocationsWorkflowsExecutionsGetArgs,
    ) -> String {
        format!("gcp::workflowexecutions::Execution/{}", input.name)
    }

    fn resource_kind(&self) -> &'static str {
        "gcp::workflowexecutions::Execution"
    }

    fn provider(&self) -> &'static str {
        "gcp"
    }
}

// =============================================================================
// ResourceIdentifier implementation for ListExecutionsResponse
// =============================================================================

/// ResourceIdentifier implementation for ListExecutionsResponse with WorkflowexecutionsProjectsLocationsWorkflowsExecutionsListArgs input.
///
/// WHY: Enables automatic state tracking via StoreStateIdentifierTask.
///
/// HOW: Computes resource ID from input path parameters.
impl ResourceIdentifier<WorkflowexecutionsProjectsLocationsWorkflowsExecutionsListArgs>
    for ListExecutionsResponse
{
    fn generate_resource_id(
        &self,
        input: &WorkflowexecutionsProjectsLocationsWorkflowsExecutionsListArgs,
    ) -> String {
        format!(
            "gcp::workflowexecutions::ListExecutionsResponse/{}",
            input.parent
        )
    }

    fn resource_kind(&self) -> &'static str {
        "gcp::workflowexecutions::ListExecutionsResponse"
    }

    fn provider(&self) -> &'static str {
        "gcp"
    }
}

// =============================================================================
// ResourceIdentifier implementation for ListCallbacksResponse
// =============================================================================

/// ResourceIdentifier implementation for ListCallbacksResponse with WorkflowexecutionsProjectsLocationsWorkflowsExecutionsCallbacksListArgs input.
///
/// WHY: Enables automatic state tracking via StoreStateIdentifierTask.
///
/// HOW: Computes resource ID from input path parameters.
impl ResourceIdentifier<WorkflowexecutionsProjectsLocationsWorkflowsExecutionsCallbacksListArgs>
    for ListCallbacksResponse
{
    fn generate_resource_id(
        &self,
        input: &WorkflowexecutionsProjectsLocationsWorkflowsExecutionsCallbacksListArgs,
    ) -> String {
        format!(
            "gcp::workflowexecutions::ListCallbacksResponse/{}",
            input.parent
        )
    }

    fn resource_kind(&self) -> &'static str {
        "gcp::workflowexecutions::ListCallbacksResponse"
    }

    fn provider(&self) -> &'static str {
        "gcp"
    }
}

// =============================================================================
// ResourceIdentifier implementation for StepEntry
// =============================================================================

/// ResourceIdentifier implementation for StepEntry with WorkflowexecutionsProjectsLocationsWorkflowsExecutionsStepEntriesGetArgs input.
///
/// WHY: Enables automatic state tracking via StoreStateIdentifierTask.
///
/// HOW: Computes resource ID from input path parameters.
impl ResourceIdentifier<WorkflowexecutionsProjectsLocationsWorkflowsExecutionsStepEntriesGetArgs>
    for StepEntry
{
    fn generate_resource_id(
        &self,
        input: &WorkflowexecutionsProjectsLocationsWorkflowsExecutionsStepEntriesGetArgs,
    ) -> String {
        format!("gcp::workflowexecutions::StepEntry/{}", input.name)
    }

    fn resource_kind(&self) -> &'static str {
        "gcp::workflowexecutions::StepEntry"
    }

    fn provider(&self) -> &'static str {
        "gcp"
    }
}

// =============================================================================
// ResourceIdentifier implementation for ListStepEntriesResponse
// =============================================================================

/// ResourceIdentifier implementation for ListStepEntriesResponse with WorkflowexecutionsProjectsLocationsWorkflowsExecutionsStepEntriesListArgs input.
///
/// WHY: Enables automatic state tracking via StoreStateIdentifierTask.
///
/// HOW: Computes resource ID from input path parameters.
impl ResourceIdentifier<WorkflowexecutionsProjectsLocationsWorkflowsExecutionsStepEntriesListArgs>
    for ListStepEntriesResponse
{
    fn generate_resource_id(
        &self,
        input: &WorkflowexecutionsProjectsLocationsWorkflowsExecutionsStepEntriesListArgs,
    ) -> String {
        format!(
            "gcp::workflowexecutions::ListStepEntriesResponse/{}",
            input.parent
        )
    }

    fn resource_kind(&self) -> &'static str {
        "gcp::workflowexecutions::ListStepEntriesResponse"
    }

    fn provider(&self) -> &'static str {
        "gcp"
    }
}
