mod foundation_macros_arrow_json_schema_tests;
mod foundation_macros_arrow_schema_tests;
mod foundation_macros_json_hash_tests;
mod foundation_macros_json_schema_tests;
mod foundation_macros_scaffold_tests;
mod foundation_macros_wasm_entrypoint_tests;
